import {test,expect,type Page} from '../../frontend/node_modules/@playwright/test';
import path from 'node:path';
import {selectOption} from './select';
let projectId:string,videoId:string;
async function state(request:any){return (await request.get(`/api/projects/${projectId}`)).json()}
async function drag(page:Page,a:number[],b:number[]){const v=await page.getByTestId('canvas').evaluate(e=>{const r=e.getBoundingClientRect();return {x:r.x+Number(e.getAttribute('data-offset-x')),y:r.y+Number(e.getAttribute('data-offset-y')),s:Number(e.getAttribute('data-scale'))}});await page.mouse.move(v.x+a[0]*v.s,v.y+a[1]*v.s);await page.mouse.down();await page.mouse.move(v.x+b[0]*v.s,v.y+b[1]*v.s,{steps:8});await page.mouse.up()}
async function copyTo(page:Page,target:string){await page.getByRole('button',{name:'Copy to class…',exact:true}).click();await selectOption(page,'Target class',target);await page.getByRole('button',{name:'Copy boxes',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0)}
async function saved(page:Page){await expect(page.locator('.save-status')).toHaveText('Saved')}
async function ready(page:Page,f:number){await expect(page.getByTestId('canvas')).toHaveAttribute('data-frame',String(f))}
async function reopen(page:Page){await page.reload();await expect(page.getByRole('heading',{name:'Your projects'})).toBeVisible();await page.getByTestId('open-project-'+projectId).click();await page.getByTestId('open-video-'+videoId).click();}
async function validatedExport(request:any){
 const revision=(await state(request)).revision;
 const checked=await request.post(`/api/videos/${videoId}/validate`,{data:{revision,visual_confirmed:true,coverage:'selected_people'}});expect(checked.ok()).toBeTruthy();const report=await checked.json();expect(report.passed,JSON.stringify(report.errors)).toBe(true);expect(report.mode).toBe('structural');
 const response=await request.post(`/api/projects/${projectId}/exports`,{data:{format:'annotations_json',video_id:videoId,revision,validation_id:report.validation_id}});expect(response.ok()).toBeTruthy();const job=(await response.json()).id;
 await expect.poll(async()=> (await (await request.get('/api/jobs/'+job)).json()).status,{timeout:30000}).toBe('completed');return (await (await request.get('/api/jobs/'+job)).json()).export_id;
}
const obs=(p:any)=>Object.values(p.state.observations) as any[];
const at=(p:any,f:number)=>obs(p).find(o=>o.frame_index===f);
test.beforeEach(async({page,request})=>{
 const r=await request.post('/api/projects',{data:{name:'Browser acceptance '+Date.now(),classes:['person_visible','person_extended']}});projectId=(await r.json()).id;
 const v=await request.post(`/api/projects/${projectId}/videos/local`,{data:{path:'tests/fixtures/numbered.mp4'}});videoId=(await v.json()).video_id;
 await expect.poll(async()=> (await state(request)).videos[videoId].status).toBe('ready');
 await page.route('**/api/updates/check*',route=>route.fulfill({json:{status:'current',current_version:'test',can_install:false}}));
 await page.goto('/');await expect(page.getByRole('heading',{name:'Your projects'})).toBeVisible();await page.getByTestId('open-project-'+projectId).click();await page.getByTestId('open-video-'+videoId).click();await ready(page,0);
});
test('simple workspace, explicit save and keyboard save retain annotations',async({page,request})=>{
 for(const name of ['Export','Manual ready','Visible person','Configure detector','Review / reject suggestions','New project'])await expect(page.getByRole('button',{name,exact:true})).toHaveCount(0);
 await page.getByRole('button',{name:'Toggle shortcuts',exact:true}).click();await expect(page.getByText('Shortcuts',{exact:true})).toBeVisible();await page.getByTestId('canvas').press('n');await drag(page,[100,80],[220,310]);await page.getByRole('button',{name:'Save',exact:true}).click();await saved(page);
 let p=await state(request);expect(obs(p)).toHaveLength(1);expect(obs(p)[0].boxes?.['class:person_visible'][0]).toBeCloseTo(100,0);expect(obs(p)[0].boxes?.['class:person_extended']).toBeUndefined();
 await page.getByTestId('canvas').press('Control+s');await saved(page);expect((await state(request)).revision).toBe(p.revision);
 await reopen(page);await ready(page,0);expect((await state(request)).state).toEqual(p.state);
});
test('new video inherits project classes and opens editor',async({page,request})=>{
 await page.getByRole('button',{name:'New video',exact:true}).click();
 const response=page.waitForResponse(r=>r.url().endsWith('/videos')&&r.request().method()==='POST');
 await page.getByLabel('Upload video').setInputFiles(path.resolve('../tests/fixtures/numbered.mp4'));
 const result=await (await response).json();videoId=result.video_id;
 // The upload response precedes project loading; the previous canvas can still show frame 0 behind the dialog.
 await expect(page.getByRole('dialog')).toHaveCount(0);await ready(page,0);
 const library=await (await request.get('/api/video-library')).json();projectId=library.find((v:any)=>v.id===videoId).project_id;
 expect((await state(request)).classes).toEqual(['person_visible','person_extended']);
 await page.getByTestId('canvas').press('n');await expect(page.getByRole('button',{name:'Select Track 1',exact:true})).toHaveAttribute('aria-pressed','true');await page.getByTestId('canvas').press('i');await expect(page.getByLabel('Class name',{exact:true})).toHaveValue('person_visible');await page.getByLabel('Class name',{exact:true}).fill('Visitor');await page.getByRole('button',{name:'Save ID',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0);await saved(page);expect((await state(request)).classes).toContain('Visitor');
});
test('reuse later ID before earlier frame; class, color, interpolation and undo persist',async({page,request})=>{
 await page.getByLabel('Go to frame').fill('20');await ready(page,20);await page.getByTestId('canvas').press('n');await drag(page,[200,80],[300,300]);await page.keyboard.press('i');await page.getByLabel('Track ID',{exact:true}).fill('7');await page.getByLabel('Class name',{exact:true}).fill('Worker');await page.getByRole('button',{name:'Box color #fb923c',exact:true}).click();await page.getByRole('button',{name:'Save ID',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0);await saved(page);
 const original=Object.keys((await state(request)).state.identities)[0];await page.getByLabel('Go to frame').fill('5');await ready(page,5);await page.getByTestId('canvas').press('n');await page.getByRole('button',{name:'Select class Worker',exact:true}).click();await drag(page,[110,80],[210,300]);await saved(page);const before=(await state(request)).state;
 await page.keyboard.press('i');await selectOption(page,'Existing track ID','Track 7');await expect(page.getByLabel('Track ID',{exact:true})).toHaveValue('7');await selectOption(page,'Existing track ID','New number / current person');await expect(page.getByLabel('Track ID',{exact:true})).toHaveValue('1');await selectOption(page,'Existing track ID','Track 7');await page.getByRole('button',{name:'Save ID',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0);await saved(page);
 let p=await state(request);expect(Object.keys(p.state.identities)).toEqual([original]);expect(p.state.identities[original]).toMatchObject({person_id:7,box_styles:{'class:Worker':{class_name:'Worker',color:'#fb923c'}}});expect(obs(p)).toHaveLength(16);expect(at(p,10).boxes?.['class:Worker'][0]).toBeCloseTo(140,0);
 await page.getByTestId('canvas').press('Control+z');await saved(page);expect((await state(request)).state).toEqual(before);await page.keyboard.press('Control+Shift+z');await saved(page);await reopen(page);await ready(page,5);await page.getByTestId('canvas').press('i');await expect(page.getByRole('button',{name:'Box color #fb923c',exact:true})).toHaveAttribute('aria-pressed','true');
});
test('keyframes always interpolate despite an old off preference, corrections change neighbors and gaps remain empty',async({page,request})=>{
 await page.evaluate(()=>localStorage.setItem('frameinsight:interpolate','off'));await reopen(page);await ready(page,0);await expect(page.getByRole('checkbox',{name:'Auto-interpolate',exact:true})).toHaveCount(0);
 await page.getByTestId('canvas').press('n');await drag(page,[100,80],[200,300]);await page.getByLabel('Go to frame').fill('10');await ready(page,10);await drag(page,[200,80],[300,300]);await saved(page);expect(obs(await state(request))).toHaveLength(11);
 await page.getByLabel('Go to frame').fill('5');await ready(page,5);await drag(page,[200,190],[220,190]);await saved(page);let p=await state(request);expect(at(p,5).provenance['class:person_visible'].human_corrected).toBe(true);expect(at(p,5).boxes?.['class:person_visible'][0]).toBeCloseTo(170,0);expect(at(p,3).boxes?.['class:person_visible'][0]).toBeCloseTo(142,0);
 await page.getByTestId('canvas').press('Control+z');await saved(page);expect(at(await state(request),5).boxes?.['class:person_visible'][0]).toBeCloseTo(150,0);
 await page.getByLabel('Go to frame').fill('15');await ready(page,15);await drag(page,[210,80],[310,300]);await saved(page);await page.getByTestId('canvas').press('Shift+Delete');await page.getByLabel('First frame to delete').fill('11');await page.getByLabel('Last frame to delete').fill('14');await page.getByRole('button',{name:'Delete boxes',exact:true}).click();await saved(page);p=await state(request);expect(obs(p).some(o=>o.frame_index>=11&&o.frame_index<15)).toBe(false);
});
test('eye and focus preserve work, delete can be cancelled or undone',async({page,request})=>{
 await page.getByTestId('canvas').press('n');await drag(page,[100,80],[200,300]);await page.keyboard.press('n');await drag(page,[130,90],[230,310]);await saved(page);const before=await state(request);
 await page.getByRole('button',{name:'Focus Track 2',exact:true}).click();await expect(page.getByRole('button',{name:'Show Track 1',exact:true})).toBeVisible();await reopen(page);await ready(page,0);await expect(page.getByRole('button',{name:'Show Track 1',exact:true})).toBeVisible();expect((await state(request)).state).toEqual(before.state);
 await page.getByRole('button',{name:'Show all tracks'}).click();await page.getByRole('button',{name:'Delete Track 1',exact:true}).click();await page.getByRole('button',{name:'Cancel',exact:true}).click();expect((await state(request)).state).toEqual(before.state);
 await page.getByRole('button',{name:'Delete Track 1',exact:true}).click();await page.getByRole('button',{name:'Delete track and annotations'}).click();await saved(page);expect(Object.keys((await state(request)).state.identities)).toHaveLength(1);await page.getByTestId('canvas').press('Control+z');await saved(page);expect((await state(request)).state).toEqual(before.state);
});
test('finish confirms review, validates without rendering, exports annotations only and edits reopen finished work',async({page,request})=>{
 const renderRequests:string[]=[];page.on('request',r=>{if(r.method()==='POST'&&r.url().includes('/review-jobs'))renderRequests.push(r.url())});
 await page.getByTestId('canvas').press('n');await drag(page,[100,80],[200,300]);await page.getByRole('button',{name:'Finish',exact:true}).click();await expect(page.getByRole('dialog',{name:'Review before finishing',exact:true})).toBeVisible();await expect(page.getByRole('link',{name:'Download annotations (.json)'})).toHaveCount(0);
 await page.getByRole('button',{name:'Back to editing',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0);await ready(page,0);
 await page.getByRole('button',{name:'Finish',exact:true}).click();await page.getByRole('button',{name:'I reviewed — continue',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0);await expect(page.getByRole('heading',{name:'Validate & export',exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Prepare validated JSON'})).toBeDisabled();await expect(page.getByTestId('review-video')).toHaveCount(0);
 await selectOption(page,'Annotation coverage','Only the objects I chose to annotate');await page.getByRole('button',{name:'Run annotation validation'}).click();await expect(page.getByTestId('validation-report')).toContainText('Validation passed');await page.getByRole('button',{name:'Prepare validated JSON'}).click();
 const link=page.getByRole('link',{name:'Download annotations (.json)'});await expect(link).toBeVisible();const doc=await (await request.get((await link.getAttribute('href'))!)).json();expect(doc.video_scope).toBe(videoId);expect(doc.media_included).toBe(false);expect(doc.annotation_index).toHaveLength(1);expect(doc.state.reviews).toEqual({});expect(renderRequests).toEqual([]);
 await page.getByRole('button',{name:'Back to annotation',exact:true}).click();await ready(page,0);await page.locator('.project-switch').click();await expect(page.getByTestId('video-row-'+videoId)).toContainText('Finished');await page.getByTestId('open-video-'+videoId).click();await ready(page,0);await drag(page,[150,190],[160,190]);await saved(page);await page.locator('.project-switch').click();await expect(page.getByTestId('video-row-'+videoId)).toContainText('In progress');
});
test('offline edits are retained and Save retries after reconnect',async({page,request,context})=>{
 await page.getByTestId('canvas').press('n');await saved(page);await context.setOffline(true);await drag(page,[100,80],[200,300]);await expect(page.locator('.save-status')).toHaveText('Save failed');await page.getByRole('button',{name:'Save',exact:true}).click();await expect(page.locator('.save-status')).toHaveText('Save failed');await context.setOffline(false);await page.getByRole('button',{name:'Save',exact:true}).click();await saved(page);expect(obs(await state(request))).toHaveLength(1);
});
test('navigation during drag commits on its original frame and cursor survives reopening',async({page,request})=>{
 await page.getByTestId('canvas').press('n');const v=await page.getByTestId('canvas').evaluate(e=>{const r=e.getBoundingClientRect();return {x:r.x+Number(e.getAttribute('data-offset-x')),y:r.y+Number(e.getAttribute('data-offset-y')),s:Number(e.getAttribute('data-scale'))}});await page.mouse.move(v.x+100*v.s,v.y+80*v.s);await page.mouse.down();await page.mouse.move(v.x+200*v.s,v.y+300*v.s);await page.keyboard.press('f');await page.mouse.up();await ready(page,1);await saved(page);expect(obs(await state(request))[0].frame_index).toBe(0);const before=await state(request);await reopen(page);await ready(page,1);expect((await state(request)).state).toEqual(before.state);
});
test('hidden range deletes interpolated boxes, preserves other people, and survives undo, redo, export and reload',async({page,request})=>{
 await page.getByTestId('canvas').press('n');await drag(page,[100,80],[200,300]);await page.getByLabel('Go to frame').fill('20');await ready(page,20);await drag(page,[200,80],[300,300]);await saved(page);
 const who=Object.keys((await state(request)).state.identities)[0];
 await page.getByLabel('Go to frame').fill('10');await ready(page,10);await page.getByTestId('canvas').press('n');await drag(page,[350,80],[450,300]);await saved(page);await page.locator('.person').filter({hasText:'Track 1'}).click();
 const before=(await state(request)).state;
 await page.getByRole('button',{name:'Delete range',exact:true}).click();await page.getByLabel('First frame to delete').fill('8');await page.getByLabel('Last frame to delete').fill('12');await expect(page.getByRole('dialog')).toContainText('5 boxes');await page.getByRole('button',{name:'Cancel',exact:true}).click();expect((await state(request)).state).toEqual(before);
 await page.getByTestId('canvas').press('Shift+Delete');await page.getByLabel('First frame to delete').fill('8');await page.getByLabel('Last frame to delete').fill('12');await page.getByRole('button',{name:'Delete boxes',exact:true}).click();await saved(page);
 let p=await state(request);const gap=Object.values(p.state.intervals) as any[];expect(gap).toMatchObject([{identity_uuid:who,start:8,end:12}]);expect(obs(p).filter(o=>o.identity_uuid===who&&o.frame_index>=8&&o.frame_index<=12)).toHaveLength(0);expect(obs(p).filter(o=>o.identity_uuid!==who)).toHaveLength(1);await expect(page.locator('.gap-banner')).toContainText('Interpolation paused');
 await page.getByTestId('canvas').press('Control+z');await saved(page);expect((await state(request)).state).toEqual(before);await page.keyboard.press('Control+Shift+z');await saved(page);expect((await state(request)).state).toEqual(p.state);
 await page.getByRole('button',{name:'Go to frame 13',exact:true}).click();await ready(page,13);await drag(page,[215,190],[225,190]);await saved(page);await page.getByTestId('canvas').press('k');await saved(page);p=await state(request);expect(obs(p).filter(o=>o.identity_uuid===who&&o.frame_index>=8&&o.frame_index<=12)).toHaveLength(0);expect(obs(p).find(o=>o.identity_uuid===who&&o.frame_index===16)!.boxes?.['class:person_visible'][0]).toBeGreaterThan(180);
 await reopen(page);await ready(page,13);await page.getByLabel('Go to frame').fill('10');await ready(page,10);await expect(page.locator('.gap-banner')).toContainText('Interpolation paused');
 const exportId=await validatedExport(request);const exported=await (await request.get('/api/exports/'+exportId)).json();expect(Object.values(exported.state.intervals)).toMatchObject([{start:8,end:12,reason:'unknown'}]);expect(exported.presence_intervals.find((r:any)=>r.identity_uuid===who&&r.class_key==='class:person_visible'&&r.start===8)).toMatchObject({end:12,status:'absent',basis:'explicit_gap',reason:'unknown'});expect(exported.annotation_index.filter((o:any)=>o.identity_uuid===who&&o.frame_index>=8&&o.frame_index<=12)).toHaveLength(0);
});

test('restore deleted range preserves new endpoints, supports exact undo, and recovers originals in a fresh browser',async({page,request,browser})=>{
 await page.getByTestId('canvas').press('n');await drag(page,[100,80],[200,300]);await page.getByLabel('Go to frame').fill('20');await ready(page,20);await drag(page,[200,80],[300,300]);await saved(page);const original=(await state(request)).state;
 await page.getByTestId('canvas').press('Shift+Delete');await page.getByLabel('First frame to delete').fill('8');await page.getByLabel('Last frame to delete').fill('12');await page.getByRole('button',{name:'Delete boxes',exact:true}).click();await saved(page);
 await page.getByLabel('Go to frame').fill('8');await ready(page,8);await drag(page,[130,80],[230,300]);await page.getByLabel('Go to frame').fill('12');await ready(page,12);await drag(page,[190,80],[290,300]);await saved(page);const blocked=(await state(request)).state;expect(at({state:blocked},10)).toBeUndefined();
 await page.getByRole('button',{name:'Restore range',exact:true}).click();await page.getByLabel('First frame to restore').fill('8');await page.getByLabel('Last frame to restore').fill('12');await expect(page.getByRole('dialog')).toContainText('3 boxes to restore');await expect(page.getByRole('dialog')).toContainText('2 existing boxes kept');
 await page.route(`**/api/projects/${projectId}/operations`,route=>route.abort('failed'));await page.getByRole('radio',{name:/Recover deleted boxes/}).check();await expect(page.getByRole('dialog')).toContainText('Saved history could not be loaded');await expect(page.getByRole('button',{name:'Recover deleted boxes',exact:true})).toBeDisabled();await expect(page.locator('.restore-preview')).toHaveCount(0);expect((await state(request)).state).toEqual(blocked);
 await page.unroute(`**/api/projects/${projectId}/operations`);await page.getByRole('radio',{name:/Fill between my boxes/}).check();await page.getByRole('button',{name:'Remove gap & fill boxes',exact:true}).click();await saved(page);
 const restored=await state(request);expect(at(restored,10).boxes?.['class:person_visible'][0]).toBeCloseTo(160,0);expect(at(restored,8)).toEqual(at({state:blocked},8));expect(at(restored,12)).toEqual(at({state:blocked},12));expect(Object.values(restored.state.intervals)).toHaveLength(0);
 await page.getByTestId('canvas').press('Control+z');await saved(page);expect((await state(request)).state).toEqual(blocked);
 const fresh=await browser.newContext({baseURL:new URL(page.url()).origin,viewport:{width:1440,height:960}});
 let releaseHistory!:()=>void,requested=false;const waitingHistory=new Promise<void>(resolve=>{releaseHistory=resolve});await fresh.route(`**/api/projects/${projectId}/operations`,async route=>{requested=true;await waitingHistory;await route.continue()});
 try{
  const other=await fresh.newPage();await other.goto('/');await other.getByTestId('open-project-'+projectId).click();await other.getByTestId('open-video-'+videoId).click();await ready(other,0);await other.locator('.person').filter({hasText:'Track 1'}).click();await other.getByLabel('Go to frame').fill('10');await ready(other,10);await expect(other.locator('.gap-banner')).toContainText('Interpolation paused');
  await other.locator('.gap-banner').getByRole('button',{name:'Restore deleted range',exact:true}).click();await other.getByLabel('First frame to restore').fill('8');await other.getByLabel('Last frame to restore').fill('12');expect(requested).toBe(false);await other.getByRole('radio',{name:/Recover deleted boxes/}).check();await expect.poll(()=>requested).toBe(true);await expect(other.getByRole('button',{name:'Recover deleted boxes',exact:true})).toBeDisabled();await expect(other.locator('.restore-preview')).toHaveCount(0);await expect(other.getByRole('dialog')).toContainText('Loading saved edit history');expect((await state(request)).state).toEqual(blocked);releaseHistory();await expect(other.getByRole('dialog')).toContainText('3 boxes to restore');await other.getByRole('button',{name:'Recover deleted boxes',exact:true}).click();await saved(other);
  const recovered=await state(request);expect(at(recovered,10).boxes?.['class:person_visible']).toEqual(at({state:original},10).boxes?.['class:person_visible']);expect(at(recovered,8)).toEqual(at({state:blocked},8));expect(at(recovered,12)).toEqual(at({state:blocked},12));expect(Object.values(recovered.state.intervals)).toHaveLength(0);
  await other.getByTestId('canvas').press('Control+z');await saved(other);expect((await state(request)).state).toEqual(blocked);await other.getByTestId('canvas').press('Control+Shift+z');await saved(other);await reopen(other);await ready(other,10);expect((await state(request)).state).toEqual(recovered.state);
 }finally{releaseHistory();await fresh.close();}
});

test('missing boxes are automatically not visible; Delete saves absence and drawing restores it without G or H',async({page,request})=>{
 await page.getByTestId('canvas').press('n');
 await drag(page,[100,80],[200,300]);await page.getByLabel('Go to frame').fill('10');await ready(page,10);await drag(page,[200,80],[300,300]);await saved(page);
 await page.getByLabel('Go to frame').fill('5');await ready(page,5);
 await page.getByTestId('canvas').press('Delete');await saved(page);let p=await state(request);expect(at(p,5)).toBeUndefined();expect(Object.values(p.state.intervals)).toMatchObject([{start:5,end:5,reason:'unknown'}]);await expect(page.locator('.gap-banner')).toContainText('Interpolation paused');
 await page.getByTestId('canvas').press('k');await saved(page);expect(at(await state(request),5)).toBeUndefined();
 await drag(page,[140,80],[240,300]);await saved(page);p=await state(request);expect(at(p,5).boxes?.['class:person_visible'][0]).toBeCloseTo(140,0);expect(Object.values(p.state.intervals)).toHaveLength(0);await expect(page.locator('.gap-banner')).toHaveCount(0);
 await page.getByTestId('canvas').press('Control+z');await saved(page);expect(at(await state(request),5)).toBeUndefined();await expect(page.locator('.gap-banner')).toContainText('Interpolation paused');await page.keyboard.press('Control+Shift+z');await saved(page);expect(at(await state(request),5).boxes?.['class:person_visible']).toBeDefined();
 await page.getByLabel('Go to frame').fill('15');await ready(page,15);await expect(page.locator('.gap-banner')).toContainText('No person_visible box yet');await drag(page,[230,80],[330,300]);await saved(page);expect(at(await state(request),15).boxes?.['class:person_visible']).toBeDefined();
 await reopen(page);await ready(page,15);await page.getByLabel('Go to frame').fill('23');await ready(page,23);await expect(page.locator('.gap-banner')).toContainText('No person_visible box yet');
});
test('video library deletion can be cancelled and removes only the selected video',async({page,request})=>{
 await page.getByTestId('canvas').press('n');await drag(page,[100,80],[200,300]);await saved(page);
 const second=await request.post('/api/projects',{data:{name:'Keep this video',classes:['person_visible','person_extended']}});const otherProject=(await second.json()).id;const added=await request.post(`/api/projects/${otherProject}/videos/local`,{data:{path:'tests/fixtures/numbered.mp4'}});const otherVideo=(await added.json()).video_id;
 await expect.poll(async()=> (await (await request.get('/api/projects/'+otherProject)).json()).videos[otherVideo].status).toBe('ready');
 await page.locator('.project-switch').click();await page.getByTestId('delete-video-'+videoId).click();await expect(page.getByRole('dialog',{name:'Delete video'})).toContainText('numbered.mp4');await page.getByRole('button',{name:'Cancel',exact:true}).click();await expect(page.getByTestId('open-video-'+videoId)).toBeVisible();
 await page.getByTestId('delete-video-'+videoId).click();await page.getByRole('button',{name:'Delete video and annotations',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0);await expect(page.getByTestId('open-video-'+videoId)).toHaveCount(0);await expect(page.getByTestId('open-video-'+otherVideo)).toHaveCount(0);expect((await request.get('/api/projects/'+projectId)).status()).toBe(200);
 await page.reload();await page.getByTestId('open-project-'+otherProject).click();await expect(page.getByTestId('open-video-'+videoId)).toHaveCount(0);await page.getByTestId('open-video-'+otherVideo).click();await ready(page,0);
});

test('visible and extended boxes share an ID with independent interpolation, deletion, undo and JSON rows',async({page,request})=>{
 await page.getByTestId('canvas').press('n');await drag(page,[120,100],[180,240]);await page.keyboard.press('i');await page.getByLabel('Track ID',{exact:true}).fill('1');await page.getByLabel('Class name',{exact:true}).fill('person_visible');await page.getByRole('button',{name:'Save ID',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0);await saved(page);
 await page.getByTestId('canvas').press('2');await drag(page,[100,80],[200,300]);await saved(page);
 await page.getByTestId('canvas').press('i');await expect(page.getByLabel('Class name',{exact:true})).toHaveValue('person_extended');await page.getByLabel('Class name',{exact:true}).fill('person_extended');await page.getByRole('button',{name:'Box color #fbbf24',exact:true}).click();await page.getByRole('button',{name:'Save ID',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0);await saved(page);
 await page.getByLabel('Go to frame').fill('10');await ready(page,10);await drag(page,[200,80],[300,300]);await page.getByTestId('canvas').press('1');await drag(page,[220,100],[280,240]);await saved(page);
 let p=await state(request);expect(Object.keys(p.state.identities)).toHaveLength(1);expect(obs(p)).toHaveLength(11);expect(at(p,5).boxes?.['class:person_visible'][0]).toBeCloseTo(170,0);expect(at(p,5).boxes?.['class:person_extended'][0]).toBeCloseTo(150,0);
 const extended=structuredClone(at(p,5).boxes?.['class:person_extended']),extProvenance=structuredClone(at(p,5).provenance['class:person_extended']);
 await page.getByLabel('Go to frame').fill('5');await ready(page,5);await drag(page,[200,170],[210,170]);await saved(page);p=await state(request);expect(at(p,5).boxes?.['class:person_extended']).toEqual(extended);expect(at(p,5).provenance['class:person_extended']).toEqual(extProvenance);expect(at(p,5).provenance['class:person_visible'].human_corrected).toBe(true);
 await page.getByTestId('canvas').press('Delete');await saved(page);p=await state(request);expect(at(p,5).boxes?.['class:person_visible']).toBeUndefined();expect(at(p,5).boxes?.['class:person_extended']).toEqual(extended);
 await page.getByTestId('canvas').press('Control+z');await saved(page);expect(at(await state(request),5).boxes?.['class:person_visible']).toBeDefined();await page.keyboard.press('Control+Shift+z');await saved(page);expect(at(await state(request),5).boxes?.['class:person_visible']).toBeUndefined();await page.getByTestId('canvas').press('k');await saved(page);expect(at(await state(request),5).boxes?.['class:person_visible']).toBeUndefined();
 await drag(page,[175,100],[235,240]);await saved(page);await page.getByTestId('canvas').press('2');await page.getByRole('button',{name:'Hide class person_visible',exact:true}).click();await saved(page);const before=(await state(request)).state;await reopen(page);await ready(page,5);expect((await state(request)).state).toEqual(before);await expect(page.getByRole('button',{name:'Select class person_extended',exact:true})).toHaveAttribute('aria-pressed','true');
 const exportId=await validatedExport(request);const doc=await (await request.get('/api/exports/'+exportId)).json();
 expect(doc.schema_version).toBe(3);const rows=doc.annotation_index.filter((r:any)=>r.frame_index===5);expect(rows).toHaveLength(2);expect(rows.map((r:any)=>r.person_id)).toEqual([1,1]);expect(rows[0].identity_uuid).toBe(rows[1].identity_uuid);expect(rows.map((r:any)=>r.class_name).sort()).toEqual(['person_extended','person_visible']);expect(rows.find((r:any)=>r.class_name==='person_extended').color).toBe('#fbbf24');expect(doc.frame_annotations.find((r:any)=>r.frame_index===5).boxes['class:person_extended']).toEqual(extended);
});

test('I links an older extended-class track to visible ID on the same frame and undo restores both tracks',async({page,request})=>{
 await page.getByTestId('canvas').press('n');await drag(page,[130,120],[190,240]);await page.keyboard.press('i');await page.getByLabel('Track ID',{exact:true}).fill('7');await page.getByLabel('Class name',{exact:true}).fill('person_visible');await page.getByRole('button',{name:'Save ID',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0);await saved(page);
 const first=Object.keys((await state(request)).state.identities)[0];
 await page.getByTestId('canvas').press('n');await drag(page,[100,80],[220,300]);await saved(page);let p=await state(request);const second=Object.keys(p.state.identities).find(id=>id!==first)!;const identity=p.state.identities[second];
 const sourceObservation=obs(p).find(o=>o.identity_uuid===second);const legacyObservation={...sourceObservation,person_visible:sourceObservation.boxes['class:person_visible'],provenance:{person_visible:sourceObservation.provenance['class:person_visible']}};delete legacyObservation.boxes;
 const response=await request.post(`/api/projects/${projectId}/operations`,{data:{id:crypto.randomUUID(),base_revision:p.revision,label:'Legacy fixture',changes:[{collection:'identities',id:second,before:identity,after:Object.fromEntries(Object.entries({...identity,class_name:'person_extended',color:'#ffaa00'}).filter(([key])=>key!=='box_styles'))},{collection:'observations',id:sourceObservation.id,before:sourceObservation,after:legacyObservation}]}});expect(response.ok()).toBeTruthy();await reopen(page);await ready(page,0);await page.locator('.person').filter({hasText:'Track 1'}).click();await drag(page,[110,190],[115,190]);await saved(page);const before=(await state(request)).state;expect(before.identities[second].box_styles).toBeUndefined();
 await page.getByTestId('canvas').press('i');await expect(page.getByLabel('Class name',{exact:true})).toHaveValue('person_extended');await selectOption(page,'Existing track ID','Track 7');await expect(page.getByLabel('Class name',{exact:true})).toHaveValue('person_extended');await page.getByRole('button',{name:'Save ID',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0);await saved(page);
 p=await state(request);expect(Object.keys(p.state.identities)).toEqual([first]);expect(obs(p)).toHaveLength(1);expect(at(p,0).boxes?.['class:person_visible'][0]).toBeCloseTo(130,0);expect(at(p,0).person_ext).toEqual((Object.values(before.observations) as any[]).find(o=>o.identity_uuid===second).person_visible);expect(p.state.identities[first].person_id).toBe(7);
 await page.getByTestId('canvas').press('Control+z');await saved(page);expect((await state(request)).state).toEqual(before);await page.keyboard.press('Control+Shift+z');await saved(page);await reopen(page);await ready(page,0);expect((await state(request)).state).toEqual(p.state);
});

test('a new extended-first person can set its ID and later receive a visible box',async({page,request})=>{
 await page.getByTestId('canvas').press('n');await page.keyboard.press('2');await drag(page,[100,60],[220,310]);await saved(page);let p=await state(request);expect(at(p,0).boxes?.['class:person_extended']).toBeDefined();expect(at(p,0).boxes?.['class:person_visible']).toBeUndefined();
 await page.getByTestId('canvas').press('i');await expect(page.getByLabel('Class name',{exact:true})).toHaveValue('person_extended');await page.getByLabel('Track ID',{exact:true}).fill('9');await page.getByRole('button',{name:'Save ID',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0);await saved(page);
 const ext=at(await state(request),0).boxes?.['class:person_extended'];await page.getByTestId('canvas').press('1');await drag(page,[130,120],[190,240]);await saved(page);p=await state(request);expect(at(p,0).boxes?.['class:person_extended']).toEqual(ext);expect(at(p,0).boxes?.['class:person_visible']).toBeDefined();expect(Object.keys(p.state.identities)).toHaveLength(1);expect(Object.values(p.state.identities)[0]).toMatchObject({person_id:9});
});

test('class buttons group both classes under one person and persist random colors',async({page,request})=>{
 await page.getByTestId('canvas').press('n');await drag(page,[120,100],[180,240]);
 await page.getByRole('button',{name:'Add class',exact:true}).click();await page.getByLabel('New class name').fill('Silhouette');await page.getByRole('button',{name:'Create class',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0);
 await drag(page,[100,80],[200,300]);await saved(page);
 await expect(page.locator('.person-row')).toHaveCount(1);await expect(page.locator('.person-classes')).toContainText('person_visible');await expect(page.locator('.person-classes')).toContainText('Silhouette');
 let p=await state(request);const person:any=Object.values(p.state.identities)[0];const styles=person.box_styles;
 expect(styles['class:person_visible'].color).not.toBe(styles['class:Silhouette'].color);expect(styles['class:Silhouette'].color).toBe(p.class_colors.Silhouette);
 const classes=page.locator('.class-bar');await classes.getByRole('button',{name:'Select class person_visible',exact:true}).click();await expect(page.getByRole('button',{name:'Select class person_visible',exact:true})).toHaveAttribute('aria-pressed','true');
 await classes.getByRole('button',{name:'Select class Silhouette',exact:true}).click();await expect(page.getByRole('button',{name:'Select class Silhouette',exact:true})).toHaveAttribute('aria-pressed','true');
 await reopen(page);await ready(page,0);await expect(page.locator('.person-row')).toHaveCount(1);expect((await state(request)).state.identities[person.id].box_styles).toEqual(styles);
 await page.getByTestId('canvas').press('i');await page.getByRole('dialog').getByRole('button',{name:'Add class',exact:true}).click();await page.getByLabel('Class name',{exact:true}).fill('Estimated body');await page.getByRole('button',{name:'Save ID',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0);await saved(page);
 p=await state(request);expect(p.state.identities[person.id].box_styles['class:Estimated body'].color).toBe(p.class_colors['Estimated body']);expect(p.class_colors['Estimated body']).not.toBe(styles['class:Silhouette'].color);await expect(classes.getByRole('button',{name:'Select class Estimated body',exact:true})).toBeVisible();
});

test('manual zoom and pan survive drawing, resizing panels and switching frames',async({page,request})=>{
 const canvas=page.getByTestId('canvas');await canvas.press('n');
 const initial=Number(await canvas.getAttribute('data-scale'));const rect=(await canvas.boundingBox())!;
 await page.mouse.move(rect.x+rect.width/2,rect.y+rect.height/2);await page.mouse.wheel(0,-300);
 await expect.poll(async()=>Number(await canvas.getAttribute('data-scale'))).toBeGreaterThan(initial);
 const zoom=await canvas.getAttribute('data-scale');const view=async()=>[await canvas.getAttribute('data-offset-x'),await canvas.getAttribute('data-offset-y'),await canvas.getAttribute('data-scale')];
 // Pan with the key held, then draw in the central visible source region.
 await page.keyboard.down('Space');await page.mouse.move(rect.x+rect.width/2,rect.y+rect.height/2);await page.mouse.down();await page.mouse.move(rect.x+rect.width/2+20,rect.y+rect.height/2+10);await page.mouse.up();await page.keyboard.up('Space');
 const before=await view();await drag(page,[290,140],[350,220]);await saved(page);expect(await view()).toEqual(before);
 await page.getByRole('button',{name:'Toggle shortcuts',exact:true}).click();await expect(page.locator('.shortcut-panel')).toBeVisible();await page.getByRole('button',{name:'Toggle shortcuts',exact:true}).click();await expect(page.locator('.shortcut-panel')).toHaveCount(0);expect(await canvas.getAttribute('data-scale')).toBe(zoom);
 await page.getByRole('button',{name:'Toggle tracks panel',exact:true}).click();await expect(page.locator('.people-panel')).toHaveCount(0);expect(await view()).toEqual(before);
 await page.getByLabel('Go to frame').fill('10');await ready(page,10);await drag(page,[300,140],[360,220]);await saved(page);expect(await view()).toEqual(before);
 expect(at(await state(request),0).boxes?.['class:person_visible'][0]).toBeCloseTo(290,0);expect(at(await state(request),5).boxes?.['class:person_visible'][0]).toBeCloseTo(295,0);
 await page.getByRole('button',{name:'Fit video',exact:true}).click();await expect.poll(async()=>canvas.getAttribute('data-scale')).not.toBe(zoom);
});

test('copy Visible to Extended selects a separate colored box; resize, undo, reload and JSON retain the same ID',async({page,request})=>{
 const copy=page.getByRole('button',{name:'Copy to class…',exact:true});await expect(copy).toBeDisabled();
 await page.getByTestId('canvas').press('n');await drag(page,[120,100],[200,240]);await page.keyboard.press('i');await page.getByLabel('Track ID',{exact:true}).fill('7');await page.getByLabel('Class name',{exact:true}).fill('person_visible');await page.getByRole('button',{name:'Save ID',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0);await saved(page);
 const before=(await state(request)).state;const canvas=page.getByTestId('canvas');const scale=await canvas.getAttribute('data-scale');
 await copyTo(page,'person_extended');await saved(page);await expect(page.getByRole('button',{name:'Select class person_extended',exact:true})).toHaveAttribute('aria-pressed','true');await expect(copy).toBeEnabled();await expect(canvas).toHaveAttribute('data-scale',scale!);
 let p=await state(request);const id=Object.keys(p.state.identities)[0];expect(Object.keys(p.state.identities)).toHaveLength(1);expect(p.state.identities[id].person_id).toBe(7);expect(at(p,0).boxes?.['class:person_extended']).toEqual(at(p,0).boxes?.['class:person_visible']);expect(at(p,0).geometry_link).toBe('independent');expect(p.state.identities[id].box_styles['class:person_visible'].color).not.toBe(p.state.identities[id].box_styles['class:person_extended'].color);
 await canvas.press('Control+z');await saved(page);expect((await state(request)).state).toEqual(before);await expect(copy).toBeEnabled();await canvas.press('Control+Shift+z');await saved(page);
 await drag(page,[160,240],[160,310]);await saved(page);p=await state(request);expect(at(p,0).boxes?.['class:person_extended'][3]).toBeCloseTo(310,0);expect(at(p,0).boxes?.['class:person_visible']).toEqual(Object.values(before.observations).map((o:any)=>o.boxes?.['class:person_visible'])[0]);expect(at(p,0).provenance['class:person_visible']).toEqual(Object.values(before.observations).map((o:any)=>o.provenance['class:person_visible'])[0]);
 const persisted=p.state;await reopen(page);await ready(page,0);expect((await state(request)).state).toEqual(persisted);await expect(page.getByRole('button',{name:'Select class person_extended',exact:true})).toHaveAttribute('aria-pressed','true');
 const exportId=await validatedExport(request);const doc=await (await request.get('/api/exports/'+exportId)).json();const rows=doc.annotation_index.filter((r:any)=>r.frame_index===0);expect(rows).toHaveLength(2);expect(rows.map((r:any)=>r.person_id)).toEqual([7,7]);expect(Object.fromEntries(rows.map((r:any)=>[r.class_name,r.color]))).toEqual({person_visible:p.class_colors.person_visible,person_extended:p.class_colors.person_extended});expect(rows.map((r:any)=>r.class_name).sort()).toEqual(['person_extended','person_visible']);
 await page.getByLabel('Go to frame').fill('1');await ready(page,1);await expect(copy).toBeEnabled();
});

test('one click copies all visible frames from anywhere; spaced corrections interpolate and undo restores the whole copy',async({page,request})=>{
 await page.getByTestId('canvas').press('n');await drag(page,[100,100],[180,240]);await page.getByLabel('Go to frame').fill('10');await ready(page,10);await drag(page,[200,100],[280,240]);await saved(page);
 const before=(await state(request)).state;const visible=obs(await state(request)).map(o=>({frame:o.frame_index,box:o.boxes?.['class:person_visible'],provenance:o.provenance['class:person_visible']})).sort((a,b)=>a.frame-b.frame);
 const copy=page.getByRole('button',{name:'Copy to class…',exact:true});
 await page.getByLabel('Go to frame').fill('20');await ready(page,20);await expect(copy).toBeEnabled();await copy.click();await expect(page.getByRole('combobox',{name:'Source class',exact:true})).toBeFocused();await expect(page.getByRole('dialog')).toContainText('11 frames');
 // Replacing the target options must retain the parent's new selection, rather than clearing it through the hidden form select.
 await selectOption(page,'Source class','person_extended');await expect(page.getByRole('combobox',{name:'Target class',exact:true})).toContainText('person_visible');await expect(page.getByRole('dialog')).toContainText('0 frames');await expect(page.getByRole('button',{name:'Copy boxes',exact:true})).toBeDisabled();
 await selectOption(page,'Source class','person_visible');await expect(page.getByRole('combobox',{name:'Target class',exact:true})).toContainText('person_extended');await expect(page.getByRole('dialog')).toContainText('11 frames');await expect(page.getByRole('button',{name:'Copy boxes',exact:true})).toBeEnabled();await page.getByRole('button',{name:'Copy boxes',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0);await saved(page);await expect(copy).toBeEnabled();let p=await state(request);expect(obs(p).filter(o=>o.boxes?.['class:person_extended'])).toHaveLength(11);for(const o of obs(p))expect(o.boxes?.['class:person_extended']).toEqual(o.boxes?.['class:person_visible']);expect(at(p,20)).toBeUndefined();
 await page.getByTestId('canvas').press('Control+z');await saved(page);expect((await state(request)).state).toEqual(before);await page.getByTestId('canvas').press('Control+Shift+z');await saved(page);
 await page.getByLabel('Go to frame').fill('0');await ready(page,0);await drag(page,[140,240],[140,280]);await page.getByLabel('Go to frame').fill('10');await ready(page,10);await drag(page,[240,240],[240,320]);await saved(page);p=await state(request);expect(at(p,5).boxes?.['class:person_extended'][3]).toBeCloseTo(300,0);expect(at(p,10).provenance['class:person_extended'].human_corrected).toBe(true);expect(obs(p).map(o=>({frame:o.frame_index,box:o.boxes?.['class:person_visible'],provenance:o.provenance['class:person_visible']})).sort((a,b)=>a.frame-b.frame)).toEqual(visible);
 await page.getByRole('button',{name:'Delete range',exact:true}).click();await page.getByLabel('First frame to delete').fill('3');await page.getByLabel('Last frame to delete').fill('7');await page.getByRole('button',{name:'Delete boxes',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0);await saved(page);
 const corrected=at(await state(request),10).boxes?.['class:person_extended'];await page.getByRole('button',{name:'Select class person_visible',exact:true}).click();await copyTo(page,'person_extended');await saved(page);p=await state(request);for(const f of [3,4,5,6,7])expect(at(p,f).boxes?.['class:person_extended']).toEqual(at(p,f).boxes?.['class:person_visible']);expect(at(p,10).boxes?.['class:person_extended']).toEqual(corrected);
 const persisted=p.state;await reopen(page);await ready(page,10);expect((await state(request)).state).toEqual(persisted);
});

test('automatic dimming keeps overlapping interiors bright, follows resize and zoom, and never changes annotations',async({page,request})=>{
 await page.evaluate(()=>localStorage.setItem('frameinsight:dimOutside','off'));await reopen(page);await ready(page,0);
 const canvas=page.getByTestId('canvas');await expect(page.getByRole('checkbox',{name:'Dim outside boxes',exact:true})).toHaveCount(0);
 const pixels=async(points:number[][])=>canvas.evaluate((host,points)=>{
  const layers=Array.from(host.querySelectorAll('canvas')),first=layers[0],combined=document.createElement('canvas');combined.width=first.width;combined.height=first.height;const ctx=combined.getContext('2d')!;
  for(const layer of layers)ctx.drawImage(layer,0,0);const ratio=first.width/host.clientWidth,s=Number(host.getAttribute('data-scale')),x=Number(host.getAttribute('data-offset-x')),y=Number(host.getAttribute('data-offset-y'));
  const sample=(context:CanvasRenderingContext2D)=>points.map(([px,py])=>Array.from(context.getImageData(Math.round((x+px*s)*ratio),Math.round((y+py*s)*ratio),1,1).data));
  return {source:sample(first.getContext('2d')!),composite:sample(ctx)};
 },points);
 const points=[[150,150],[240,280],[190,190],[400,180]],empty=await pixels(points);expect(empty.composite).toEqual(empty.source);
 await canvas.press('n');await drag(page,[100,100],[220,240]);await canvas.press('2');await drag(page,[130,130],[260,310]);await saved(page);const before=await state(request);
 await expect.poll(async()=>{const p=await pixels(points);return p.composite[3][2]/p.source[3][2]}).toBeLessThan(.8);
 const dimmed=await pixels(points);expect(dimmed.composite.slice(0,3)).toEqual(dimmed.source.slice(0,3));expect((await state(request)).state).toEqual(before.state);expect((await state(request)).revision).toBe(before.revision);
 await page.getByRole('button',{name:'Hide class person_visible',exact:true}).click();await expect.poll(async()=>{const p=await pixels([[110,160]]);return p.composite[0][2]/p.source[0][2]}).toBeLessThan(.8);await page.getByRole('button',{name:'Show class person_visible',exact:true}).click();await expect.poll(async()=>{const p=await pixels([[110,160]]);return p.composite[0]}).toEqual((await pixels([[110,160]])).source[0]);expect((await state(request)).revision).toBe(before.revision);
 // The mask follows the live bottom-edge preview, before the edit is saved.
 const view=await canvas.evaluate(e=>{const r=e.getBoundingClientRect();return {x:r.x+Number(e.getAttribute('data-offset-x')),y:r.y+Number(e.getAttribute('data-offset-y')),s:Number(e.getAttribute('data-scale'))}});
 const originalPixel=(await pixels([[190,320]])).composite[0][2];await page.mouse.move(view.x+195*view.s,view.y+310*view.s);await page.mouse.down();await page.mouse.move(view.x+195*view.s,view.y+335*view.s,{steps:8});await expect.poll(async()=> (await pixels([[190,320]])).composite[0][2]).toBeGreaterThan(originalPixel);await page.mouse.up();await saved(page);
 let p=await state(request);expect(at(p,0).boxes?.['class:person_extended'][3]).toBeCloseTo(335,0);expect(at(p,0).boxes?.['class:person_visible']).toEqual(at(before,0).boxes?.['class:person_visible']);const corrected=p.state;
 const rect=(await canvas.boundingBox())!;await page.mouse.move(rect.x+rect.width/2,rect.y+rect.height/2);await page.mouse.wheel(0,-100);await expect.poll(async()=>Number(await canvas.getAttribute('data-scale'))).toBeGreaterThan(view.s);const zoom=await canvas.getAttribute('data-scale');
 const zoomed=await pixels(points);expect(zoomed.composite[3][2]).toBeLessThan(zoomed.source[3][2]*.8);expect(zoomed.composite.slice(0,3)).toEqual(zoomed.source.slice(0,3));await expect(canvas).toHaveAttribute('data-scale',zoom!);expect((await state(request)).state).toEqual(corrected);
 p=await state(request);await reopen(page);await ready(page,0);await expect.poll(async()=>{const p=await pixels(points);return p.composite[3][2]/p.source[3][2]}).toBeLessThan(.8);expect((await state(request)).state).toEqual(p.state);
 await page.getByLabel('Go to frame').fill('10');await ready(page,10);await expect(canvas.locator('canvas')).toHaveCount(2);const noBoxes=await pixels(points);expect(noBoxes.composite).toEqual(noBoxes.source);expect((await state(request)).revision).toBe(p.revision);
});

test('three arbitrary classes remain independent under one track through copy, hiding, corrections, reload and JSON3 export',async({page,request})=>{
 projectId=(await(await request.post('/api/projects',{data:{name:'Three arbitrary classes '+Date.now(),classes:['Face','Torso','Bag']}})).json()).id;
 videoId=(await(await request.post(`/api/projects/${projectId}/videos/local`,{data:{path:'tests/fixtures/numbered.mp4'}})).json()).video_id;
 await expect.poll(async()=>(await state(request)).videos[videoId].status).toBe('ready');await page.reload();await page.getByTestId('open-project-'+projectId).click();await page.getByTestId('open-video-'+videoId).click();await ready(page,0);
 const select=async(name:string)=>page.getByRole('button',{name:'Select class '+name,exact:true}).click();
 const canvas=page.getByTestId('canvas');await canvas.press('n');await drag(page,[110,60],[150,110]);await page.getByLabel('Go to frame').fill('10');await ready(page,10);await drag(page,[210,60],[250,110]);await saved(page);
 await select('Torso');await drag(page,[200,120],[280,260]);await page.getByLabel('Go to frame').fill('0');await ready(page,0);await drag(page,[100,120],[180,260]);await saved(page);
 await select('Face');await copyTo(page,'Bag');await saved(page);const copied=await state(request);expect(Object.keys(copied.state.identities)).toHaveLength(1);expect(obs(copied)).toHaveLength(11);
 for(const row of obs(copied)){expect(row.person_visible).toBeNull();expect(row.person_ext).toBeNull();expect(Object.keys(row.boxes).sort()).toEqual(['class:Bag','class:Face','class:Torso']);expect(row.boxes['class:Bag']).toEqual(row.boxes['class:Face']);}
 const originalFace=obs(copied).map(o=>[o.frame_index,o.boxes['class:Face'],o.provenance['class:Face']]),originalTorso=obs(copied).map(o=>[o.frame_index,o.boxes['class:Torso'],o.provenance['class:Torso']]);
 // Torso's label covers Bag's bottom handle: left-drag resizes Bag, right-click still targets the label.
 const handle=await canvas.evaluate(element=>{const r=element.getBoundingClientRect(),scale=Number(element.getAttribute('data-scale')),x=Number(element.getAttribute('data-offset-x'))+130*scale,y=Number(element.getAttribute('data-offset-y'))+110*scale;const torso=JSON.parse(element.getAttribute('data-labels')||'[]').find((badge:any)=>badge.className==='Torso');return {x:r.x+x,y:r.y+y,overlaps:!!torso&&x>=torso.x&&x<=torso.x+torso.width&&y>=torso.y&&y<=torso.y+torso.height}});
 expect(handle.overlaps).toBe(true);await page.mouse.move(handle.x,handle.y);await expect(canvas).toHaveCSS('cursor','ns-resize');await page.mouse.click(handle.x,handle.y,{button:'right'});await expect(page.getByRole('menu')).toContainText('Track 1 · Torso');await page.keyboard.press('Escape');await select('Bag');
 await drag(page,[130,110],[130,150]);await saved(page);await expect(page.getByRole('button',{name:'Select class Bag',exact:true})).toHaveAttribute('aria-pressed','true');expect(at(await state(request),0).boxes['class:Bag'][3]).toBeCloseTo(150,0);await page.getByLabel('Go to frame').fill('10');await ready(page,10);await drag(page,[230,110],[230,190]);await saved(page);
 let p=await state(request);expect(at(p,5).boxes['class:Bag'][3]).toBeCloseTo(170,0);expect(obs(p).map(o=>[o.frame_index,o.boxes['class:Face'],o.provenance['class:Face']])).toEqual(originalFace);expect(obs(p).map(o=>[o.frame_index,o.boxes['class:Torso'],o.provenance['class:Torso']])).toEqual(originalTorso);
 const before=p.state,revision=p.revision;await page.getByRole('button',{name:'Hide class Face',exact:true}).click();await page.getByRole('button',{name:'Hide class Torso',exact:true}).click();await expect(page.getByRole('button',{name:'Show class Face',exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Show class Torso',exact:true})).toBeVisible();expect((await state(request)).revision).toBe(revision);expect((await state(request)).state).toEqual(before);
 await reopen(page);await ready(page,10);await expect(page.getByRole('button',{name:'Show class Face',exact:true})).toBeVisible();expect((await state(request)).state).toEqual(before);
 const exportId=await validatedExport(request);const doc=await(await request.get('/api/exports/'+exportId)).json();expect(doc.schema_version).toBe(3);expect(doc.media_included).toBe(false);expect(doc.annotation_index).toHaveLength(33);expect(new Set(doc.annotation_index.map((r:any)=>r.person_id))).toEqual(new Set([1]));expect(new Set(doc.annotation_index.map((r:any)=>r.class_name))).toEqual(new Set(['Face','Torso','Bag']));expect(new Set(doc.annotation_index.map((r:any)=>r.class_key))).toEqual(new Set(['class:Face','class:Torso','class:Bag']));
 expect(doc.frame_annotations.find((r:any)=>r.frame_index===5).boxes).toEqual(at({state:before},5).boxes);expect(doc.state).toEqual(before);
});

test('canvas tools and context menu select the actual box, preserve pan, edit, delete and undo safely',async({page,request})=>{
 const canvas=page.getByTestId('canvas');await canvas.press('n');await drag(page,[100,80],[200,300]);await canvas.press('n');await drag(page,[350,80],[450,300]);await saved(page);const original=(await state(request)).state;
 const clickSource=async(x:number,y:number,button:'left'|'right'='left')=>{const v=await canvas.evaluate(e=>{const r=e.getBoundingClientRect();return{x:r.x+Number(e.getAttribute('data-offset-x')),y:r.y+Number(e.getAttribute('data-offset-y')),s:Number(e.getAttribute('data-scale'))}});await page.mouse.click(v.x+x*v.s,v.y+y*v.s,{button});};
 await clickSource(150,190,'right');await expect(page.getByRole('menu')).toBeVisible();await expect(page.getByRole('button',{name:'Select Track 1',exact:true,includeHidden:true})).toHaveAttribute('aria-pressed','true');expect((await state(request)).state).toEqual(original);
 await page.getByRole('menuitem',{name:'Change ID or class… I',exact:true}).click();await expect(page.getByLabel('Track ID',{exact:true})).toHaveValue('1');await expect(page.getByRole('button',{name:'Box color #ff0000',exact:true})).toHaveCount(0);await expect(page.getByRole('button',{name:'Box color #ffffff',exact:true})).toHaveCount(0);await page.keyboard.press('Escape');
 await clickSource(150,190,'right');await page.getByRole('menuitem',{name:'Copy to class…',exact:true}).click();await selectOption(page,'Target class','person_extended');await page.getByRole('button',{name:'Copy boxes',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0);await saved(page);const copied=(await state(request)).state;
 await clickSource(150,190,'right');await page.getByRole('menuitem',{name:'Delete box on this frame Delete',exact:true}).click();await saved(page);let p=await state(request);const first:any=Object.values(p.state.identities).find((i:any)=>i.person_id===1),row=obs(p).find(o=>o.identity_uuid===first.id);expect(row.boxes['class:person_extended']).toBeUndefined();expect(row.boxes['class:person_visible']).toBeDefined();await expect(page.getByRole('menu')).toHaveCount(0);await canvas.press('Control+z');await expect.poll(async()=>(await state(request)).state).toEqual(copied);await saved(page);
 const tools=page.getByRole('toolbar',{name:'Canvas tools',exact:true});await expect(canvas.getByRole('toolbar')).toHaveCount(0);
 await tools.getByRole('button',{name:'Hand tool (H)',exact:true}).click();await expect(canvas).toHaveAttribute('data-tool','hand');const x=await canvas.getAttribute('data-offset-x');await drag(page,[150,190],[170,195]);expect(await canvas.getAttribute('data-offset-x')).not.toBe(x);expect((await state(request)).state).toEqual(copied);
 await tools.getByRole('button',{name:'Select and move (V)',exact:true}).click();await expect(canvas).toHaveAttribute('data-tool','select');await clickSource(400,190);await expect(page.getByRole('button',{name:'Select Track 2',exact:true})).toHaveAttribute('aria-pressed','true');expect((await state(request)).state).toEqual(copied);
 await tools.getByRole('button',{name:'Draw box (B)',exact:true}).click();await expect(canvas).toHaveAttribute('data-tool','draw');await drag(page,[340,70],[460,310]);await saved(page);p=await state(request);const second:any=Object.values(p.state.identities).find((i:any)=>i.person_id===2);expect(obs(p).find(o=>o.identity_uuid===second.id).boxes['class:person_visible'][0]).toBeCloseTo(340,0);
 const scale=Number(await canvas.getAttribute('data-scale'));await tools.getByRole('button',{name:'Zoom in',exact:true}).click();await expect.poll(async()=>Number(await canvas.getAttribute('data-scale'))).toBeGreaterThan(scale);const zoomed=Number(await canvas.getAttribute('data-scale'));await tools.getByRole('button',{name:'Zoom out',exact:true}).click();await expect.poll(async()=>Number(await canvas.getAttribute('data-scale'))).toBeLessThan(zoomed);
 await tools.getByRole('button',{name:'Fit video',exact:true}).click();const fitted=await canvas.evaluate(element=>({width:element.clientWidth,height:element.clientHeight,x:Number(element.getAttribute('data-offset-x')),y:Number(element.getAttribute('data-offset-y')),scale:Number(element.getAttribute('data-scale'))}));expect(fitted.x).toBeCloseTo((fitted.width-p.videos[videoId].width*fitted.scale)/2,0);expect(fitted.y).toBeCloseTo((fitted.height-p.videos[videoId].height*fitted.scale)/2,0);expect((await state(request)).state).toEqual(p.state);
 for(const [key,tool] of [['h','hand'],['b','draw'],['v','select']]){await canvas.press(key);await expect(canvas).toHaveAttribute('data-tool',tool)}
 const timeline=page.getByRole('region',{name:'Annotation timeline'});await expect(timeline.getByRole('button',{name:'Frames 0–0: Present',exact:true})).toBeVisible();await canvas.press('Delete');await saved(page);await expect(timeline.getByRole('button',{name:'Frames 0–0: Hidden',exact:true})).toHaveCSS('background-color','rgb(239, 68, 68)');await expect(timeline.getByRole('button',{name:'Frames 1–1: Hidden',exact:true})).toHaveCSS('background-color','rgb(239, 68, 68)');await expect(timeline.getByText('No box',{exact:true})).toHaveCount(0);
});

test('context copy-previous is disabled on an existing class box and does not replace corrections',async({page,request})=>{
 const canvas=page.getByTestId('canvas');await canvas.press('n');await drag(page,[100,80],[200,300]);await page.getByLabel('Go to frame').fill('10');await ready(page,10);await drag(page,[200,80],[300,300]);await page.getByLabel('Go to frame').fill('5');await ready(page,5);await drag(page,[200,190],[210,190]);await saved(page);const before=(await state(request)).state;
 const v=await canvas.evaluate(e=>{const r=e.getBoundingClientRect();return{x:r.x+Number(e.getAttribute('data-offset-x')),y:r.y+Number(e.getAttribute('data-offset-y')),s:Number(e.getAttribute('data-scale'))}});await page.mouse.click(v.x+205*v.s,v.y+190*v.s,{button:'right'});await expect(page.getByRole('menuitem',{name:'Copy previous box C',exact:true})).toBeDisabled();
 // Keep Radix's real closing menu mounted so the CI timing regression is deterministic.
 const exitStyle=await page.addStyleTag({content:'@keyframes regression-menu-close { from { opacity: 1; } to { opacity: 0; } } .canvas-context-menu[data-state="closed"] { animation: regression-menu-close 30s linear !important; }'});
 await expect.poll(()=>page.evaluate(()=>document.activeElement?.closest('[role="menu"]')?.getAttribute('data-state'))).toBe('open');
 await page.keyboard.press('Escape');await expect(page.locator('[role="menu"][data-state="closed"]')).toHaveCount(1);expect((await state(request)).state).toEqual(before);
 expect(await page.evaluate(()=>document.activeElement?.closest('[role="menu"]')?.getAttribute('data-state'))).toBe('closed');
 await page.keyboard.press('Delete');await expect.poll(async()=>!!at(await state(request),5)?.boxes?.['class:person_visible']).toBe(false);await saved(page);const deleted=(await state(request)).state;
 await page.keyboard.press('h');await expect(canvas).toHaveAttribute('data-tool','hand');await page.keyboard.press('v');await expect(canvas).toHaveAttribute('data-tool','select');
 await exitStyle.evaluate(element=>element.remove());await expect(page.getByRole('menu')).toHaveCount(0);
 await page.mouse.click(v.x+205*v.s,v.y+190*v.s,{button:'right'});await expect(page.getByRole('menuitem',{name:'Copy previous box C',exact:true})).toBeEnabled();await page.getByRole('menuitem',{name:'Copy previous box C',exact:true}).click();await saved(page);expect(at(await state(request),5).boxes['class:person_visible']).toEqual(at({state:before},4).boxes['class:person_visible']);await canvas.press('Control+z');await saved(page);expect((await state(request)).state).toEqual(deleted);await canvas.press('Control+z');await saved(page);expect((await state(request)).state).toEqual(before);
});

test('collision-shifted class badges select their exact box and share safe context actions',async({page,request})=>{
 const canvas=page.getByTestId('canvas');await canvas.press('n');await drag(page,[120,100],[220,300]);await copyTo(page,'person_extended');await saved(page);
 await canvas.press('n');await page.getByRole('button',{name:'Select class person_visible',exact:true}).click();await drag(page,[120,100],[220,300]);await saved(page);
 const before=await state(request),first:any=Object.values(before.state.identities).find((identity:any)=>identity.person_id===1),second:any=Object.values(before.state.identities).find((identity:any)=>identity.person_id===2);
 type Badge={x:number;y:number;width:number;height:number;identity:string;geometry:string;className:string};
 const badges=async()=>JSON.parse((await canvas.getAttribute('data-labels'))||'[]') as Badge[];
 const target=async()=>{const label=(await badges()).find(badge=>badge.identity===first.id&&badge.geometry==='class:person_extended');expect(label).toBeDefined();return label!};
 const clickBadge=async(button:'left'|'right')=>{const label=await target(),host=(await canvas.boundingBox())!;await page.mouse.click(host.x+label.x+label.width/2,host.y+label.y+label.height/2,{button});};
 await expect.poll(async()=>(await badges()).length).toBe(3);
 const label=await target(),painted=await badges(),view=await canvas.evaluate(element=>({x:Number(element.getAttribute('data-offset-x')),y:Number(element.getAttribute('data-offset-y')),scale:Number(element.getAttribute('data-scale'))}));
 expect(label.className).toBe('person_extended');expect(Math.max(Math.abs(label.x-(view.x+120*view.scale)),Math.abs(label.y-(view.y+100*view.scale-label.height-7)))).toBeGreaterThan(2);
 for(const other of painted.filter(badge=>badge.identity!==first.id||badge.geometry!=='class:person_extended')){
  expect(label.x+label.width<=other.x||other.x+other.width<=label.x||label.y+label.height<=other.y||other.y+other.height<=label.y).toBe(true);
 }
 // A normal badge click, even in draw mode with the wrong track active, selects without drawing.
 await page.getByRole('button',{name:'Draw box (B)',exact:true}).click();await clickBadge('left');await expect(page.getByRole('button',{name:'Select Track 1',exact:true})).toHaveAttribute('aria-pressed','true');await expect(page.getByRole('button',{name:'Select class person_extended',exact:true})).toHaveAttribute('aria-pressed','true');await saved(page);expect((await state(request)).state).toEqual(before.state);expect((await state(request)).revision).toBe(before.revision);
 await page.getByRole('button',{name:'Select Track 2',exact:true}).click();await page.getByRole('button',{name:'Select class person_visible',exact:true}).click();await clickBadge('right');
 const menu=page.getByRole('menu');await expect(menu).toContainText('Track 1 · person_extended');const badgeActions=await menu.getByRole('menuitem').allTextContents();await page.keyboard.press('Escape');
 // The class/ID badge and the selected underlying box expose the same menu.
 const host=(await canvas.boundingBox())!;await page.mouse.click(host.x+view.x+170*view.scale,host.y+view.y+200*view.scale,{button:'right'});await expect(menu).toContainText('Track 1 · person_extended');expect(await menu.getByRole('menuitem').allTextContents()).toEqual(badgeActions);await page.keyboard.press('Escape');
 await page.getByRole('button',{name:'Select Track 2',exact:true}).click();await page.getByRole('button',{name:'Select class person_visible',exact:true}).click();await clickBadge('right');await menu.getByRole('menuitem',{name:'Change ID or class… I',exact:true}).click();await expect(page.getByLabel('Track ID',{exact:true})).toHaveValue('1');await expect(page.getByLabel('Class name',{exact:true})).toHaveValue('person_extended');await page.keyboard.press('Escape');expect((await state(request)).state).toEqual(before.state);
 await page.getByRole('button',{name:'Select Track 2',exact:true}).click();await page.getByRole('button',{name:'Select class person_visible',exact:true}).click();await clickBadge('right');await menu.getByRole('menuitem',{name:'Delete box on this frame Delete',exact:true}).click();await saved(page);
 const after=await state(request),firstRow=obs(after).find(row=>row.identity_uuid===first.id);expect(firstRow.boxes['class:person_extended']).toBeUndefined();expect(firstRow.boxes['class:person_visible']).toEqual(obs(before).find(row=>row.identity_uuid===first.id).boxes['class:person_visible']);expect(obs(after).find(row=>row.identity_uuid===second.id)).toEqual(obs(before).find(row=>row.identity_uuid===second.id));
 await canvas.press('Control+z');await saved(page);expect((await state(request)).state).toEqual(before.state);
});
