"""Standalone video preparation: create a new MP4 before annotation/import."""
import json
import math
import os
import shutil
import struct
import uuid
from fractions import Fraction
from pathlib import Path
from concurrent.futures import ThreadPoolExecutor
import av
from fastapi import APIRouter, UploadFile, File
from fastapi.responses import FileResponse
from pydantic import BaseModel, ConfigDict, Field, StrictInt
from . import db
from .config import DATA
from .video import new_job
from .export_names import json_filename

router = APIRouter(prefix='/api/video-trims')
POOL = ThreadPoolExecutor(max_workers=1, thread_name_prefix='video-trim')
EXTENSIONS = {'.mp4','.mov','.avi','.mkv','.webm','.m4v'}


class Section(BaseModel):
    model_config = ConfigDict(extra='forbid')
    start: StrictInt = Field(ge=0)
    end: StrictInt = Field(ge=0)


class TrimRequest(BaseModel):
    model_config = ConfigDict(extra='forbid')
    sections: list[Section] = Field(min_length=1, max_length=100)
    name: str = Field(default='trimmed.mp4', max_length=180)


def normalize(sections, count):
    merged=[]
    for r in sorted(sections,key=lambda r:r['start']):
        start,end=r['start'],r['end']
        if type(start) is not int or type(end) is not int or not 0<=start<=end<count:
            raise ValueError('Choose valid source-frame boundaries for every section.')
        if merged and start<=merged[-1]['end']+1:merged[-1]['end']=max(end,merged[-1]['end'])
        else:merged.append({'start':start,'end':end})
    if not merged:raise ValueError('Keep at least one section.')
    return merged


def trim_job(jid, kind):
    job=db.job_get(jid)
    if job.get('kind')!=kind:raise ValueError('This is not a video preparation job.')
    return job


def folder(jid):
    # Job IDs are generated by this app; arbitrary paths never enter this helper.
    return DATA/'video-trims'/str(uuid.UUID(jid))


def metadata(jid):
    job=trim_job(jid,'trim_scan')
    if job['status']!='completed':raise ValueError('Wait for the video scan to finish.')
    return json.loads((folder(jid)/'metadata.json').read_text())


def cancelled(jid):
    return db.job_get(jid)['status']=='cancelled'


def scan_video(jid):
    try:
        job=trim_job(jid,'trim_scan')
        if job['status']=='cancelled':return
        db.job_update(jid,status='running',phase='Reading source frame timing')
        rows=[];display_matrix=None
        with av.open(job['source']) as source:
            if not source.streams.video:raise ValueError('This file has no video stream.')
            stream=source.streams.video[0];tb=stream.time_base
            width,height=stream.codec_context.width,stream.codec_context.height
            for n,frame in enumerate(source.decode(stream)):
                if n==0:
                    for data in frame.side_data:
                        if data.type.name=='DISPLAYMATRIX':display_matrix=list(struct.unpack('=9i',bytes(data)))
                if n%50==0:
                    if cancelled(jid):return
                    db.job_update(jid,progress=n,total=stream.frames or None)
                if frame.pts is None or frame.time_base!=tb:raise ValueError('The source needs consistent frame timestamps before it can be trimmed.')
                if rows and frame.pts<=rows[-1]['pts']:raise ValueError('The source frame timestamps are not increasing.')
                if (frame.width,frame.height)!=(width,height):raise ValueError('The source changes dimensions; use a constant-size video.')
                if rows:rows[-1]['duration']=frame.pts-rows[-1]['pts']
                rows.append({'pts':frame.pts,'duration':frame.duration or 0})
            if not rows:raise ValueError('No video frames could be decoded.')
            rate=Fraction(stream.average_rate or 25)
            if rows[-1]['duration']<=0:rows[-1]['duration']=rows[-2]['duration'] if len(rows)>1 else max(1,round(1/rate/tb))
            sar=Fraction(stream.sample_aspect_ratio or 1)
            info={'name':job['name'],'width':width,'height':height,'sample_aspect_num':sar.numerator,'sample_aspect_den':sar.denominator,'frame_count':len(rows),'time_base_num':tb.numerator,'time_base_den':tb.denominator,'rate_num':rate.numerator,'rate_den':rate.denominator,'stream_index':stream.index,'has_audio':bool(source.streams.audio),'frames':rows}
        info['display_matrix']=display_matrix
        (folder(jid)/'metadata.json').write_text(json.dumps(info))
        if not cancelled(jid):db.job_update(jid,status='completed',progress=len(rows),total=len(rows),metadata={k:v for k,v in info.items() if k!='frames'})
    except Exception as e:
        if not cancelled(jid):db.job_update(jid,status='failed',error=str(e))


@router.post('')
def upload(file:UploadFile=File(...)):
    name=Path(file.filename or 'video.mp4').name;suffix=Path(name).suffix.lower()
    if suffix not in EXTENSIONS:raise ValueError('Choose an MP4, MOV, AVI, MKV, WebM or M4V video.')
    job=new_job('video-preparation','trim_scan',name=name)
    dest=folder(job['id']);dest.mkdir(parents=True,exist_ok=True);source=dest/('source'+suffix)
    try:
        with source.open('wb') as target:shutil.copyfileobj(file.file,target,1024*1024)
        db.job_update(job['id'],source=str(source));POOL.submit(scan_video,job['id'])
    except Exception as e:
        source.unlink(missing_ok=True);db.job_update(job['id'],status='failed',error=str(e));raise
    return db.job_get(job['id'])


@router.get('/{jid}/frames/{frame_index}')
def preview_frame(jid:str,frame_index:int):
    info=metadata(jid)
    if not 0<=frame_index<info['frame_count']:raise ValueError('Frame is outside this video.')
    dest=folder(jid)/f'preview-{frame_index}.jpg'
    if not dest.exists():
        source=trim_job(jid,'trim_scan')['source'];pts=info['frames'][frame_index]['pts']
        with av.open(source) as container:
            stream=container.streams.video[0];container.seek(pts,stream=stream,backward=True)
            for frame in container.decode(stream):
                if frame.pts==pts:
                    image=frame.to_image();image.thumbnail((1280,720));tmp=dest.with_name(dest.name+'.'+str(uuid.uuid4())+'.tmp');image.save(tmp,format='JPEG',quality=85);os.replace(tmp,dest);break
                if frame.pts is not None and frame.pts>pts:break
        if not dest.exists():raise ValueError('This source cannot seek to the requested frame.')
    return FileResponse(dest,media_type='image/jpeg',headers={'Cache-Control':'private, max-age=86400, immutable'})


@router.post('/{jid}/render')
def render(jid:str,body:TrimRequest):
    info=metadata(jid);sections=normalize([r.model_dump() for r in body.sections],info['frame_count'])
    name=body.name.strip();name=name[:-4] if name.lower().endswith('.mp4') else name
    name=json_filename(name)[:-5]+'.mp4'
    job=new_job('video-preparation','video_trim',source_job_id=jid,sections=sections,name=name,total=sum(r['end']-r['start']+1 for r in sections))
    POOL.submit(render_video,job['id'])
    return job


def render_video(jid):
    partial=None
    try:
        job=trim_job(jid,'video_trim')
        if job['status']=='cancelled':return
        scan=trim_job(job['source_job_id'],'trim_scan');info=metadata(scan['id'])
        db.job_update(jid,status='running',phase='Creating new video')
        tb=Fraction(info['time_base_num'],info['time_base_den']);rows=info['frames'];rate=Fraction(info['rate_num'],info['rate_den'])
        kept={};sections=[];cursor=0
        for r in job['sections']:
            start=rows[r['start']]['pts'];end=rows[r['end']]['pts']+rows[r['end']]['duration']
            sections.append((start*tb,end*tb,cursor*tb))
            for n in range(r['start'],r['end']+1):kept[n]=(cursor+rows[n]['pts']-start,rows[n]['duration'])
            cursor+=end-start
        dest=folder(jid);dest.mkdir(parents=True,exist_ok=True);path=dest/'video.mp4';partial=dest/'video.partial.mp4'
        count=0;packet_durations={};audio_end=0
        with av.open(scan['source']) as source, av.open(str(partial),'w',format='mp4',options={'movflags':'+faststart'}) as output:
            video=source.streams.video[0];audio=source.streams.audio[0] if source.streams.audio else None
            encoded=output.add_stream('libx264',rate=rate);encoded.width=info['width'];encoded.height=info['height']
            # 4:4:4 supports odd dimensions without adding or removing any pixels.
            encoded.pix_fmt='yuv444p' if info['width']%2 or info['height']%2 else 'yuv420p'
            encoded.sample_aspect_ratio=Fraction(info.get('sample_aspect_num',1),info.get('sample_aspect_den',1))
            if info.get('display_matrix'):encoded.set_display_matrix(info['display_matrix'])
            encoded.time_base=tb;encoded.codec_context.time_base=tb;encoded.options={'crf':'18','preset':'fast','bf':'0','threads':'2'}
            sound=None;resampler=None
            if audio:
                sound=output.add_stream('aac',rate=48000);sound.layout='stereo';sound.bit_rate=128000;sound.time_base=Fraction(1,48000)
                resampler=av.AudioResampler(format='fltp',layout='stereo',rate=48000)
            def encode_audio(frame):
                nonlocal audio_end
                if frame.pts is None or frame.time_base is None:raise ValueError('The audio stream has no reliable timestamps.')
                timestamp=frame.pts*frame.time_base
                for start,end,offset in sections:
                    first=max(0,math.ceil((start-timestamp)*48000));last=min(frame.samples,math.ceil((end-timestamp)*48000))
                    if first>=last:continue
                    pts=round((offset+timestamp+Fraction(first,48000)-start)*48000)
                    # Rounding at a cut must not produce overlapping audio samples.
                    if pts<audio_end:first+=audio_end-pts;pts=audio_end
                    if first>=last:continue
                    out=av.AudioFrame(format='fltp',layout='stereo',samples=last-first)
                    for channel,plane in enumerate(frame.planes):
                        samples=bytes(memoryview(plane)[first*4:last*4]);out.planes[channel].update(samples+bytes(out.planes[channel].buffer_size-len(samples)))
                    out.sample_rate=48000;out.time_base=Fraction(1,48000);out.pts=pts;audio_end=pts+out.samples
                    for packet in sound.encode(out):output.mux(packet)
            n=-1
            for decoded,frame in enumerate(source.decode(*([video,audio] if audio else [video]))):
                if decoded%30==0 and cancelled(jid):return
                if isinstance(frame,av.AudioFrame):
                    for resampled in resampler.resample(frame):encode_audio(resampled)
                    continue
                n+=1
                if n not in kept:continue
                if frame.pts!=rows[n]['pts']:raise ValueError('Source timing changed since the scan. Choose the video again.')
                pts,duration=kept[n]
                frame.pts=pts;frame.time_base=tb;frame.duration=duration;packet_durations[pts]=duration
                for packet in encoded.encode(frame):packet.duration=packet_durations[packet.pts];output.mux(packet)
                count+=1
                if count%10==0:db.job_update(jid,progress=count)
            if resampler:
                for frame in resampler.resample(None):encode_audio(frame)
                for packet in sound.encode():output.mux(packet)
            for packet in encoded.encode():packet.duration=packet_durations[packet.pts];output.mux(packet)
        if cancelled(jid):return
        db.job_update(jid,phase='Checking the new video')
        with av.open(str(partial)) as check:
            if (check.streams.video[0].width,check.streams.video[0].height)!=(info['width'],info['height']):raise ValueError('Output dimensions changed; the new video was not saved.')
            actual=[f.pts*f.time_base for f in check.decode(check.streams.video[0])]
            expected=[pts*tb for pts,_ in kept.values()]
            if actual!=expected or count!=job['total']:raise ValueError('Output frame verification failed. The original video is unchanged.')
            duration=check.streams.video[0].duration*check.streams.video[0].time_base
            if abs(duration-cursor*tb)>check.streams.video[0].time_base:raise ValueError('Output duration verification failed.')
        os.replace(partial,path)
        if not cancelled(jid):db.job_update(jid,status='completed',progress=count,frame_count=count,duration_seconds=float(cursor*tb),audio_included=audio_end>0,download_url=f'/api/video-trims/{jid}/download',preview_url=f'/api/video-trims/{jid}/video')
    except Exception as e:
        if not cancelled(jid):db.job_update(jid,status='failed',error=str(e))
    finally:
        if partial:partial.unlink(missing_ok=True)


def output_file(jid):
    job=trim_job(jid,'video_trim');path=folder(jid)/'video.mp4'
    if job['status']!='completed' or not path.is_file():raise ValueError('Create the video successfully before saving it.')
    return job,path


@router.get('/{jid}/video')
def preview_output(jid:str):
    _,path=output_file(jid)
    return FileResponse(path,media_type='video/mp4')


@router.get('/{jid}/download')
def download(jid:str,filename:str|None=None):
    job,path=output_file(jid)
    name=filename if filename is not None else job['name']
    name=name[:-4] if name.lower().endswith('.mp4') else name
    name=json_filename(name)[:-5]+'.mp4'
    return FileResponse(path,media_type='video/mp4',filename=name,headers={'X-Content-Type-Options':'nosniff'})
