import {Textarea} from './components/ui/textarea';
import {NativeSelect} from './components/ui/native-select';
import {Checkbox} from './components/ui/checkbox';
import {Input} from './components/ui/input';
import {ProjectSettings} from './ProjectSettings';
import {CopyClass} from './CopyClass';
import {Button} from './components/ui/button';
import {CopyToClassIcon,DeleteRangeIcon,RestoreRangeIcon} from './components/AnnotationIcons';
import {useEffect,useRef,useState,useMemo,type ComponentProps} from 'react';
import {MousePointer2,SquareDashed,Hand,Minus,Tags,Activity,ArrowLeft,ArrowRight,Check,CheckCheck,ChevronDown,ChevronLeft,ChevronRight,Download,FolderOpen,HelpCircle,Layers,Maximize,MoreHorizontal,Pause,Play,Plus,Redo2,Search,Settings2,ShieldCheck,Undo2,Upload,X,AlertTriangle,Eye,EyeOff,ScanLine,Link2,PanelLeftClose,PanelRightClose,Trash2,Focus,Save} from 'lucide-react';
import {VideoLibrary,NewVideo,NewProject} from './VideoLibrary';
import {AnnotationImport} from './AnnotationImport';
import {Modal} from './components/AppDialog';
import {Onboarding} from './components/Onboarding';
import {APP_VERSION} from './release';
import {ReviewFinish} from './ReviewFinish';
import {RestoreRange} from './RestoreRange';
import {NEW_BOX_COLORS,isAllowedNewBoxColor} from './colors';
import {FrameTimeline} from './FrameTimeline';
import {UpdateNotice} from './UpdateNotice';
import {BackupProject} from './BackupProject';
import {EditorCanvas,type CanvasHandle,type CanvasControlsState} from './Canvas';
import {api,post} from './api';
import {useStore} from './store';
import {isGeometryInterpolated} from './interpolation';
import {VISIBLE_ONLY,boxStyle,geometryLabel,legacyExtended,classColor,geometries,getBox,boxKeys,orderedGeometryKeys,geometryForClass} from './types';
import {timelineBins as buildTimelineBins} from './timeline';
import {currentObservation,frameObservations,observationIssues,type Project,type Job,type Proposal,type FrameInfo,type Geometry,type Domain,uuid} from './types';
const defaultKeys:Record<string,string>={hiddenRange:'shift+delete',save:'ctrl+s',next:'f',previous:'d',ahead:'shift+f',back:'shift+d',a:'1',b:'2',swap:'tab',new:'n',id:'i',equal:'e',occluded:'o',estimated:'r',unknown:'u',copy:'c',approve:'enter',approveStay:'shift+enter',complete:'ctrl+enter',gap:'g',resume:'h',finish:'t',remove:'delete',undo:'ctrl+z',redo:'ctrl+shift+z',fit:'0',help:'?',issues:']',interpolate:'k'};
if(VISIBLE_ONLY)for(const key of ['equal','estimated','unknown','approve','approveStay'])delete defaultKeys[key];
if(VISIBLE_ONLY){defaultKeys.advance='enter';for(const key of ['complete','occluded','issues','gap','resume','finish'])delete defaultKeys[key];}
const keyDescriptions:Record<string,string>={hiddenRange:'Delete boxes in a frame range',save:'Save your work',advance:'Next frame (automatically saved)',next:'Next exact frame',previous:'Previous exact frame',ahead:'Forward 10 frames',back:'Back 10 frames',a:'Select first class',b:'Select second class',swap:'Next class',new:'New track',id:'Choose track ID, class and color',equal:'Clear person · A = B',occluded:'Toggle external occlusion',estimated:'Full extent estimated',unknown:'Full extent unknown',copy:'Copy previous box',approve:'Approve person and advance',approveStay:'Approve person, stay',complete:'Whole-frame completeness check',gap:'Start invisible gap',resume:'Resume / decide returning identity',finish:'End this track’s track here',remove:'Delete box on this frame',undo:'Undo',redo:'Redo',fit:'Fit image',help:'Search shortcuts',issues:'Next review issue',interpolate:'Fill between keyframes'};
function keyName(e:KeyboardEvent){return ((e.ctrlKey||e.metaKey)?'ctrl+':'')+(e.shiftKey&&e.key!=='?'?'shift+':'')+e.key.toLowerCase();}
function clock(seconds:number|null|undefined){if(seconds==null)return 'PTS unavailable';return `${Math.floor(seconds/60).toString().padStart(2,'0')}:${(seconds%60).toFixed(3).padStart(6,'0')}`;}
function CanvasToolButton({label,title,children,...props}:ComponentProps<typeof Button>&{label:string}){
 return <Button variant="ghost" size="icon-sm" className="size-7 [&_svg:not([class*='size-'])]:size-[18px] aria-pressed:bg-accent aria-pressed:border-input" aria-label={label} title={title||label} {...props}>{children}</Button>;
}
export default function App(){
 const s=useStore(),{project,videoId,frame,activeId,geometry,saveStatus,notice}=s;
 const [projects,setProjects]=useState<{id:string;name:string}[]>([]),[modal,setModal]=useState(''),[loading,setLoading]=useState(false),[error,setError]=useState(''),[library,setLibrary]=useState<any[]>([]),[jobs,setJobs]=useState<Job[]>([]),[proposals,setProposals]=useState<Proposal[]>([]),[ledger,setLedger]=useState<FrameInfo[]>([]),[models,setModels]=useState<any[]>([]),[playing,setPlaying]=useState(false),[showProposals,setShowProposals]=useState(true),[threshold,setThreshold]=useState(.25),[cacheKey,setCacheKey]=useState(''),[leftOpen,setLeftOpen]=useState(true),[rightOpen,setRightOpen]=useState(false),[filter,setFilter]=useState(''),[keys,setKeys]=useState<Record<string,string>>(()=>{try{return Object.fromEntries(Object.entries({...defaultKeys,...JSON.parse(localStorage.getItem('frameinsight:keys')||'{}')}).filter(([key,value])=>key in defaultKeys&&typeof value==='string')) as Record<string,string>}catch{return defaultKeys}}),[workerStatus,setWorkerStatus]=useState(false);
 const [libraryProject,setLibraryProject]=useState<string|null>(null),[libraryRevision,setLibraryRevision]=useState(0);
 const [screen,setScreen]=useState<'home'|'editor'|'finish'>('home'),[uploadBusy,setUploadBusy]=useState(false);
 const [hiddenClasses,setHiddenClasses]=useState<Record<string,boolean>>({});
 useEffect(()=>{try{const saved=JSON.parse(localStorage.getItem('frameinsight:classVisibility:'+project?.id)||'{}');setHiddenClasses(Object.fromEntries(Object.entries(saved).filter(([,value])=>value===true)) as Record<string,boolean>);}catch{setHiddenClasses({})}},[project?.id]);
 function setClassVisibility(name:string,hidden:boolean){setHiddenClasses(current=>{const next={...current,[name]:hidden};try{localStorage.setItem('frameinsight:classVisibility:'+project?.id,JSON.stringify(next))}catch{}return next});}
 const [playbackRate,setPlaybackRate]=useState(.5),[finishConfirmed,setFinishConfirmed]=useState(false);
 const [canvasControls,setCanvasControls]=useState<CanvasControlsState>({tool:'select',scale:1,ready:false});
 const [restoreJob,setRestoreJob]=useState<any>(null);
 const [form,setForm]=useState<Record<string,string>>({}),[checkAll,setCheckAll]=useState(false),[diagnostics,setDiagnostics]=useState<any>(null);
 const canvas=useRef<CanvasHandle>(null),note=useRef<HTMLTextAreaElement>(null),playTimer=useRef<number>(0),spaceTime=useRef(0),lastStep=useRef(0);
 const activeGpuJob=jobs.find(j=>j.kind==='proposals'&&j.video_id===videoId&&['running','queued'].includes(j.status));
 const video=project?.videos[videoId],active=currentObservation(project,videoId,frame,activeId),identity=project?.state.identities[activeId];
 const frameObs=frameObservations(project,videoId,frame);
 const activeGap=project&&Object.values(project.state.intervals).find(g=>g.video_id===videoId&&g.identity_uuid===activeId&&(!g.geometry||g.geometry===geometry)&&g.start<=frame&&(g.end===null||frame<=g.end));
 const review=project?.state.reviews[videoId+':'+frame];
 const issues=useMemo(()=>project?Object.values(project.state.observations).filter(o=>o.video_id===videoId).flatMap(o=>{const messages=observationIssues(o);if(!VISIBLE_ONLY&&o.review_state!=='approved')messages.push('Observation not approved');if(project.state.segments[o.segment_id]?.status==='unresolved')messages.push('Unresolved return identity');return messages.length?[{o,messages}]:[]}):[],[project?.state.observations,project?.state.segments,videoId]);
 const unknownFullCount=useMemo(()=>project?Object.values(project.state.observations).filter(o=>o.video_id===videoId&&o.full_quality==='unknown').length:0,[project?.state.observations,videoId]);
 const unresolvedLinkCount=useMemo(()=>project?Object.values(project.state.links).filter(l=>l.relation==='unresolved').length:0,[project?.state.links]);
 useEffect(()=>{if(!restoreJob?.id||['completed','failed'].includes(restoreJob.status))return;const timer=setInterval(()=>void api('/jobs/'+restoreJob.id).then(j=>{setRestoreJob(j);if(j.status==='completed')void refreshProjects()}),1500);return()=>clearInterval(timer)},[restoreJob?.id,restoreJob?.status]);
 async function refreshProjects(){setProjects(await api('/projects'))}

 useEffect(()=>{if(!project)return;let gone=false;let socket:WebSocket|null=null;let retry=0;
 const connect=()=>{socket=new WebSocket(`${location.protocol==='https:'?'wss':'ws'}://${location.host}/api/projects/${project.id}/events`);socket.onmessage=e=>{if(gone)return;const data=JSON.parse(e.data);if(data.heartbeat)return;setJobs(data.jobs);setWorkerStatus(data.worker.running);const current=useStore.getState();if(current.project?.id===project.id&&!current.settingsSaving){useStore.setState({project:{...current.project,videos:data.videos}});if(!current.pending.length&&data.revision>current.project.revision)void api<Project>('/projects/'+project.id).then(remote=>{const live=useStore.getState();if(live.project?.id===remote.id&&!live.settingsSaving&&!live.pending.length&&remote.revision>live.project.revision){useStore.setState({project:remote,history:[],redoStack:[]});live.toast('Project refreshed from server; operation history remains saved.')}}).catch(()=>{});}};socket.onclose=()=>{if(!gone)retry=window.setTimeout(connect,2500)};};connect();return()=>{gone=true;clearTimeout(retry);socket?.close()};},[project?.id]);
 useEffect(()=>{if(!videoId)return;let gone=false;void api<FrameInfo[]>('/videos/'+videoId+'/ledger').then(x=>{if(!gone){setLedger(x);useStore.setState({frameTimes:{...useStore.getState().frameTimes,[videoId]:x.map(f=>f.seconds)}})}});return()=>{gone=true}},[videoId,video?.frame_count]);
 useEffect(()=>{if(VISIBLE_ONLY||!videoId)return;let gone=false;setProposals([]);const fetch=()=>void api<Proposal[]>(`/videos/${videoId}/proposals?start=${frame}&end=${frame}`).then(x=>{if(!gone)setProposals(x)});fetch();const timer=setInterval(fetch,2000);return()=>{gone=true;clearInterval(timer)}},[videoId,frame]);
 useEffect(()=>{if(VISIBLE_ONLY)return;const j=jobs.find(j=>j.kind==='proposals'&&j.video_id===videoId&&j.status==='running');if(j)void post(`/jobs/${j.id}/priority/${frame}`)},[videoId,frame]);
 useEffect(()=>{if(!playing||screen!=='editor')return;const tick=()=>{const st=useStore.getState(),v=st.project?.videos[st.videoId];if(!v||st.frame>=v.frame_count-1){setPlaying(false);return;}if(canvas.current?.isReady())st.navigate(st.frame+1);playTimer.current=window.setTimeout(tick,Math.max(16,(((ledger[st.frame+1]?.seconds??0)-(ledger[st.frame]?.seconds??0))*1000||100)/playbackRate));};playTimer.current=window.setTimeout(tick,100);return()=>clearTimeout(playTimer.current)},[playing,ledger,playbackRate,screen]);
 useEffect(()=>{if(note.current)note.current.value=active?.evidence_note||''},[active?.id,active?.evidence_note]);
 function editObservation(label:string,fn:Parameters<typeof s.editObservation>[1]){if(!canvas.current?.isReady()){s.toast('Wait for the exact frame to load');return;}s.editObservation(label,fn)}
 function open(name:string,initial:Record<string,string>={}){if(['complete','unknown','suggestions','identity'].includes(name)&&!canvas.current?.isReady()){s.toast('Wait for the exact frame to load');return;}canvas.current?.finish();setPlaying(false);setForm(initial);setError('');setCheckAll(false);setFilter('');setModal(name)}
 function step(delta:number){canvas.current?.finish();setPlaying(false);s.navigate(useStore.getState().frame+delta)}
 function nextIssue(){const next=issues.find(i=>i.o.frame_index>frame)||issues[0];if(next){canvas.current?.finish();s.navigate(next.o.frame_index);s.selectPerson(next.o.identity_uuid);}else s.toast('No observation issues in this video. Whole-frame completeness still needs checking.');}
 function act(action:string){
  if(action==='pause'){setPlaying(false);return;}
  if(VISIBLE_ONLY&&['equal','estimated','unknown','approve','approveStay'].includes(action))return;
  if(action==='save'){void task(async()=>{canvas.current?.finish();await s.saveNow();s.toast('All changes saved.');});return;}
  if(action==='help'){open('help');return;}if(!video)return;
  if(['advance','next','previous','ahead','back'].includes(action)){step({advance:1,next:1,previous:-1,ahead:10,back:-10}[action]!);return;}
  if(action==='undo'||action==='redo'){canvas.current?.finish();s[action]();return;}
  if(action==='fit'){canvas.current?.fit();return;}
  if(!canvas.current?.isReady()){s.toast('Wait for the exact frame to load');return;}
  canvas.current?.finish();
  if(action==='a'||action==='b'||action==='swap'){const index=action==='a'?0:action==='b'?1:(classNames.indexOf(boxStyle(identity,geometry).class_name)+1)%classNames.length;if(classNames[index])chooseClass(classNames[index]);}
  else if(action==='new')s.newPerson();else if(action==='id'&&identity){const g=legacyExtended(identity)?'person_ext':geometry;open('id',{id:String(identity.person_id??''),target:'',geometry:g,...boxStyle(identity,g),color:identity.box_styles?.[g]?.color||(legacyExtended(identity)||g==='person_visible'&&identity.color?boxStyle(identity,g).color:classColor(project,boxStyle(identity,g).class_name))});}else if(action==='equal')s.equal();
  else if(action==='occluded')editObservation('Toggle occlusion',o=>{o.occluded=!o.occluded;if(o.occluded)o.geometry_link='independent'});
  else if(action==='estimated')editObservation('Full extent estimated',o=>{o.full_quality='estimated'});
  else if(action==='unknown')open('unknown',{note:active?.evidence_note||''});
  else if(action==='hiddenRange'&&activeId)open('hiddenRange',{start:String(frame),end:String(frame)});
  else if(action==='restoreRange'&&activeId)open('restoreRange',{start:String(activeGap?.start??frame),end:String(activeGap?.end??frame)});
  else if(action==='copyClass'){open('copyClass',{class_name:classNames.find(name=>name!==boxStyle(identity,geometry).class_name)||''});}else if(action==='copy')s.copyPrevious();else if(action==='remove')s.setBox(s.geometry,null);
  else if(action==='approve'||action==='approveStay'){if(s.approve()&&action==='approve')s.navigate(frame+1)}
  else if(action==='complete')open('complete');else if(action==='gap'&&activeId)open('gap',{reason:'occlusion',note:''});
  else if(action==='resume'&&activeId)open('resume',{relation:'same',note:''});
  else if(action==='finish'&&activeId){const finished=s.commit('Finish visible segment',d=>{const seg=Object.values(d.segments).find(x=>x.video_id===videoId&&x.identity_uuid===activeId&&x.start<=frame&&(x.end===null||x.end>=frame));if(!seg)throw new Error('No visible segment here');if(Object.values(d.observations).some(o=>o.segment_id===seg.id&&o.frame_index>frame))throw new Error('Later observations exist. Split the segment first.');seg.end=frame;});if(finished)s.toast('Segment finished at this frame. No exit was inferred.');}
  else if(action==='interpolate')s.fillInterpolation();
  else if(action==='issues')nextIssue();
 }
 useEffect(()=>{const down=(e:KeyboardEvent)=>{
  if(document.querySelector('[role=dialog], [role=menu], [role=listbox]'))return;
  if(keyName(e)==='ctrl+s'){e.preventDefault();act('save');return;}
  if(screen!=='editor'&&e.key!=='Escape')return;
  const el=e.target as HTMLElement;if(e.isComposing||el.closest('input,textarea,select,[role=combobox],[role=slider],[contenteditable="true"]'))return;
  if((e.key==='Enter'||e.code==='Space')&&el.closest('button,a[href],[role=button]'))return;
  if(e.key==='Escape'){if(uploadBusy||loading)return;canvas.current?.cancel();setModal('');setPlaying(false);return;}
  if(modal)return;
  if(e.code==='Space'){e.preventDefault();if(!e.repeat){spaceTime.current=Date.now();canvas.current?.space(true)}return;}
  const action=Object.keys(keys).find(a=>keys[a]===keyName(e));if(!action)return;if(action==='swap'&&e.key==='Tab'&&!el.closest('[data-testid=canvas]'))return;
  e.preventDefault();if(e.repeat&&!['next','previous'].includes(action))return;if(e.repeat&&Date.now()-lastStep.current<80)return;if(['next','previous'].includes(action))lastStep.current=Date.now();act(action);
 };const up=(e:KeyboardEvent)=>{if(e.code!=='Space'||screen!=='editor')return;const panned=canvas.current?.space(false);if(modal||document.querySelector('[role=dialog], [role=menu], [role=listbox]')||(e.target as HTMLElement).closest('input,textarea,select,[role=combobox],[role=slider],button,a[href],[role=button]'))return;if(!panned&&Date.now()-spaceTime.current<350)setPlaying(p=>!p)};
 window.addEventListener('keydown',down);window.addEventListener('keyup',up);return()=>{window.removeEventListener('keydown',down);window.removeEventListener('keyup',up)}},[keys,modal,frame,video,activeId,active,project,identity,geometry,screen,uploadBusy,loading]);
 async function task(fn:()=>Promise<void>){setLoading(true);setError('');try{await fn()}catch(e){setError(String(e))}finally{setLoading(false)}}
 async function showImport(){open('import');setLibrary(await api('/library'))}
 function beginGap(e:React.FormEvent){e.preventDefault();const success=s.commit('Start invisible gap',d=>{
  if(Object.values(d.intervals).some(g=>g.identity_uuid===activeId&&g.video_id===videoId&&(g.end===null||g.end>=frame)))throw new Error('An overlapping/later gap already exists');
  for(const o of Object.values(d.observations))if(o.video_id===videoId&&o.identity_uuid===activeId&&o.frame_index>=frame&&!boxKeys(o).length)delete d.observations[o.id];
  if(Object.values(d.observations).some(o=>o.video_id===videoId&&o.identity_uuid===activeId&&o.frame_index>=frame))throw new Error('This person has boxes on or after this frame. Remove or move those observations before opening a gap.');
  const seg=Object.values(d.segments).find(x=>x.video_id===videoId&&x.identity_uuid===activeId&&x.end===null);
  if(seg){if(seg.start===frame)delete d.segments[seg.id];else seg.end=frame-1;}
  const id=uuid();d.intervals[id]={id,video_id:videoId,identity_uuid:activeId,start:frame,end:null,reason:(form.reason||'occlusion') as any,evidence_note:form.note||''};
 });if(success)setModal('')}
 function resume(e:React.FormEvent){e.preventDefault();let selected=activeId;const success=s.commit('Resume visible segment · '+form.relation,d=>{
  const gap=Object.values(d.intervals).find(g=>g.video_id===videoId&&g.identity_uuid===activeId&&g.end===null);
  if(gap){if(frame<=gap.start)throw new Error('Resume on a later visible frame');gap.end=frame-1;}
  if(!gap&&Object.values(d.segments).some(g=>g.video_id===videoId&&g.identity_uuid===activeId&&g.end===null))throw new Error('Finish the existing segment first');
  if(form.relation!=='same'){
   selected=uuid();d.identities[selected]={id:selected,person_id:null,name:'Return draft '+(Object.keys(d.identities).length+1)};
   const id=uuid();d.links[id]={id,source:activeId,target:selected,relation:form.relation as any,evidence_note:form.note||''};
  }
  if(!form.note?.trim())throw new Error('Record evidence for the return decision');
  const id=uuid();d.segments[id]={id,video_id:videoId,identity_uuid:selected,start:frame,end:null,status:form.relation==='unresolved'?'unresolved':'verified'};
  if(gap)gap.evidence_note+=(gap.evidence_note?'\n':'')+'Return decision: '+form.relation+'. '+form.note;
 });if(success){useStore.setState({activeId:selected,geometry:VISIBLE_ONLY?'person_visible':'person_ext'});setModal('')}}
 function identityAction(e:React.FormEvent){e.preventDefault();const target=form.target;if(!target||target===activeId){setError('Choose another identity');return;}const success=s.commit('Identity '+form.action,d=>{
  if(!form.note?.trim())throw new Error('Identity decisions require evidence');
  if(form.action==='merge'){
   const mine=Object.values(d.observations).filter(o=>o.identity_uuid===activeId),other=Object.values(d.observations).filter(o=>o.identity_uuid===target);
   if(mine.some(a=>other.some(b=>a.video_id===b.video_id&&a.frame_index===b.frame_index)))throw new Error('Merge conflict: both identities have observations on the same frame');
   for(const o of mine){o.identity_uuid=target;o.review_state='draft'}
   for(const o of other)o.review_state='draft';
   for(const seg of Object.values(d.segments))if(seg.identity_uuid===activeId||seg.identity_uuid===target){seg.identity_uuid=target;seg.status='verified'}
   for(const g of Object.values(d.intervals))if(g.identity_uuid===activeId)g.identity_uuid=target;
   for(const l of Object.values(d.links)){if(l.source===activeId)l.source=target;if(l.target===activeId)l.target=target;if(l.source===l.target)delete d.links[l.id];}
   // Merge evidence is preserved in the observation notes and command history.
   for(const o of mine)o.evidence_note+=(o.evidence_note?'\n':'')+'Identity merge: '+form.note;
   delete d.identities[activeId];
  }else{const id=uuid();d.links[id]={id,source:activeId,target,relation:form.action as any,evidence_note:form.note};if(form.action==='different'){for(const seg of Object.values(d.segments))if(seg.identity_uuid===activeId&&seg.status==='unresolved')seg.status='verified';for(const l of Object.values(d.links))if(l.source===target&&l.target===activeId&&l.relation==='unresolved')l.relation='different';}}
 });if(success){if(form.action==='merge')useStore.setState({activeId:target});setModal('')}}
 function splitSegment(unlink=false){s.commit(unlink?'Unlink segment into new identity':'Split visible segment',d=>{
  const seg=Object.values(d.segments).find(x=>x.video_id===videoId&&x.identity_uuid===activeId&&x.start<frame&&(x.end===null||x.end>=frame));if(!seg)throw new Error('Choose a frame inside an existing segment, after its start');
  const id=uuid(),newIdentity=unlink?uuid():activeId;if(unlink)d.identities[newIdentity]={id:newIdentity,person_id:null,name:'Unlinked draft'};
  d.segments[id]={...seg,id,start:frame,identity_uuid:newIdentity,status:unlink?'unresolved':seg.status};seg.end=frame-1;
  for(const o of Object.values(d.observations))if(o.segment_id===seg.id&&o.frame_index>=frame){o.segment_id=id;o.identity_uuid=newIdentity;o.review_state='draft'};
  if(unlink){const link=uuid();d.links[link]={id:link,source:activeId,target:newIdentity,relation:'unresolved',evidence_note:'Segment unlinked for identity review'};}
 });setModal('')}
 const filteredProposals=proposals.filter(p=>(!VISIBLE_ONLY||p.geometry==='person_visible')&&p.confidence>=threshold&&(!cacheKey||p.cache_key===cacheKey)&&!project?.state.proposal_reviews?.[p.id]&&!frameObs.some(o=>Object.values(o.provenance).some(v=>v?.proposal_id===p.id)));
 function rejectProposal(p:Proposal){s.commit('Reject detector suggestion',d=>{d.proposal_reviews??={};d.proposal_reviews[p.id]={id:p.id,proposal_id:p.id,video_id:p.video_id,frame_index:p.frame_index,decision:'rejected',reason:form.reason||'Visually rejected: false positive or duplicate'}})}
 const timelineBins=useMemo(()=>buildTimelineBins(project?.state||null,videoId,video?.frame_count||0,activeId,geometry),[project?.state,videoId,activeId,video?.frame_count,geometry]);
 const completeCount=project?Object.values(project.state.reviews).filter(r=>r.video_id===videoId&&r.complete).length:0;
 async function openVideo(pid:string,vid:string){await s.saveNow();await s.load(pid);const current=useStore.getState();if(current.videoId!==vid)useStore.setState({videoId:vid,frame:0,activeId:''});setJobs([]);setLibraryProject(pid);setScreen('editor');setModal('');}
 async function startVideo(){canvas.current?.finish();await s.saveNow();open(libraryProject||screen==='editor'?'newVideo':'newProject');}
 async function home(){canvas.current?.finish();setPlaying(false);await s.saveNow();setScreen('home');setModal('');}
 function existingStyle(id:string){const p=project?.state.identities[id];return p&&form.class_name?boxStyle(p,geometryForClass(p,form.class_name)):{};}
 const personClasses=useMemo(()=>{
  const result:Record<string,{geometry:Geometry;class_name:string;color:string}[]>={};
  if(project)for(const p of Object.values(project.state.identities))result[p.id]=orderedGeometryKeys(project,p.id,videoId).map(g=>({geometry:g,...boxStyle(p,g)}));
  return result;
 },[project?.state,project?.classes,videoId]);
 function chooseClass(name:string){canvas.current?.finish();setClassVisibility(name,false);s.selectClass(name);}
 function toggleClass(name:string){canvas.current?.finish();setClassVisibility(name,!hiddenClasses[name]);}
 const videoTrackIds=useMemo(()=>new Set([...Object.values(project?.state.segments||{}),...Object.values(project?.state.observations||{}),...Object.values(project?.state.intervals||{})].filter(e=>e.video_id===videoId).map(e=>e.identity_uuid)),[project?.state,videoId]);
 const videoTracks=Object.values(project?.state.identities||{}).filter(p=>videoTrackIds.has(p.id));
 const classNames=[...new Set([...(project?.classes||[]),...Object.values(personClasses).flat().map(c=>c.class_name)])];
 const playbackControls=(<div className="transport" role="group" aria-label="Video playback controls" data-testid="timeline-transport"><Button variant="ghost" size="icon-xs" className="icon-button" aria-label="Previous frame" onClick={()=>step(-1)}><ChevronLeft size={19}/></Button><Button variant="ghost" size="icon-xs" className="icon-button" aria-label={playing?'Pause':'Play'} onClick={()=>{canvas.current?.finish();setPlaying(!playing)}}>{playing?<Pause size={17}/>:<Play size={17}/>}</Button><Button variant="ghost" size="icon-xs" className="icon-button" aria-label="Next frame" onClick={()=>step(1)}><ChevronRight size={19}/></Button><Input className="h-7 w-16 shrink-0 text-xs" aria-label="Go to frame" type="number" min={0} max={(video?.frame_count||1)-1} value={frame} onChange={e=>{canvas.current?.finish();s.navigate(Number(e.target.value))}}/><span className="frame-total">/ {Math.max(0,(video?.frame_count||1)-1)}</span><span className="transport-time">{clock(ledger[frame]?.seconds)}</span><NativeSelect className="transport-speed" size="sm" aria-label="Playback speed" value={playbackRate} onChange={e=>setPlaybackRate(Number(e.target.value))}><option value={.125}>0.125×</option><option value={.25}>0.25×</option><option value={.5}>0.5×</option><option value={1}>1×</option></NativeSelect><Button variant="outline" size="xs" disabled={video?.status!=='ready'} onClick={()=>open('annotationImport')}><Upload size={14}/>Import annotations</Button><span className="transport-filename" title={video?.name}>{video?.name}</span></div>);
 return <div className="app">
  <header className="topbar"><Button variant="ghost" size="sm" className="brand h-auto px-0 text-[18px]" onClick={()=>void task(home)}><span className="brand-mark"><ScanLine size={23}/></span>frameinsight<span className="local-badge">LOCAL · {APP_VERSION}</span></Button><div className="top-divider"/>{screen==='editor'&&project&&<><Button variant="ghost" size="sm" className="project-switch" onClick={()=>void task(home)}><FolderOpen size={16}/>{project.name}</Button><Button variant="outline" size="sm" onClick={()=>void task(startVideo)}><Plus size={16}/>New video</Button><Button variant="ghost" size="icon-sm" aria-label="Project settings" title="Project settings" onClick={()=>open('projectSettings',{projectId:project.id})}><Settings2 size={16}/></Button></>}<div className="top-spacer"/>{screen==='editor'&&project&&<><span className={'save-status '+(saveStatus==='Save failed'?'danger':'')}><span className="status-dot"/>{saveStatus}</span><Button variant="outline" size="sm" onClick={()=>act('save')} disabled={loading}><Save size={16}/>Save</Button><Button size="sm" className="primary" onClick={()=>{setFinishConfirmed(false);open('finishPrompt')}} disabled={video?.status!=='ready'}><Check size={17}/>Finish</Button></>}<Button variant="ghost" size="icon-sm" className="icon-button" aria-label="Help" onClick={()=>open('help')}><HelpCircle size={18}/></Button>{screen==='editor'&&<><Button variant="ghost" size="icon-sm" className="icon-button" aria-label="Toggle tracks panel" title="Tracks panel" aria-pressed={leftOpen} onClick={()=>setLeftOpen(!leftOpen)}><PanelLeftClose size={17}/></Button><Button variant="ghost" size="icon-sm" className="icon-button" aria-label="Toggle shortcuts" title="Shortcuts" aria-pressed={rightOpen} onClick={()=>setRightOpen(!rightOpen)}><PanelRightClose size={17}/></Button></>} <UpdateNotice beforeUpdate={async()=>{canvas.current?.finish();setPlaying(false);await useStore.getState().saveNow();}}/></header>
  {screen==='finish'&&project&&video?<ReviewFinish project={project} videoId={videoId} visualConfirmed={finishConfirmed} onBack={()=>setScreen('editor')} onEdit={(target,who)=>{setScreen('editor');s.navigate(target);if(who)s.selectPerson(who)}} onBackup={()=>open('backup')} onSettings={()=>open('projectSettings',{projectId:project.id})}/>:screen==='home'||!project?<VideoLibrary key={libraryRevision} selectedProject={libraryProject} onSelectProject={setLibraryProject} onNewProject={()=>open('newProject')} onSettings={id=>open('projectSettings',{projectId:id})} onOpen={openVideo} onNew={()=>void task(startVideo)}/>:<>
  {video?.status==='failed'&&<div className="save-error"><span>{video.error||'Preparing this video was interrupted.'}</span><Button variant="outline" size="sm" onClick={()=>void task(async()=>{await post(`/videos/${videoId}/retry-index`);s.toast('Preparing the video again…')})}>Retry loading video</Button></div>}
  {s.saveError&&<div className="save-error"><AlertTriangle size={16}/><span>{s.saveError} · Your pending edits are retained.</span><Button variant="outline" size="sm" onClick={s.retry}>Retry save</Button><Button variant="outline" size="sm" onClick={()=>{const blob=new Blob([JSON.stringify({project,pending:s.pending},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='frameinsight-recovery.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}}>Download recovery</Button></div>}
  <main className="workspace">
   <section className="editor-area">
    <div className="class-bar" aria-label="Available classes"><span>Classes</span><div className="class-buttons">{classNames.map((name,index)=><div className={'class-control '+(hiddenClasses[name]?'class-hidden':'')} key={name} role="group" aria-label={'Class '+name} data-active={boxStyle(identity,geometry).class_name===name}><Button variant="ghost" size="sm" className="class-select h-7 gap-2 rounded-none rounded-l-full border-0 px-3 text-xs" aria-label={'Select class '+name} aria-pressed={boxStyle(identity,geometry).class_name===name} title={'Draw '+name+(index<2?` (${index+1})`:'')} onClick={()=>chooseClass(name)}><i style={{background:personClasses[activeId]?.find(c=>c.class_name===name)?.color||classColor(project,name)}}/><span>{name}</span></Button><Button variant="ghost" size="icon-xs" className="class-eye size-7 rounded-none rounded-r-full border-0" aria-label={(hiddenClasses[name]?'Show class ':'Hide class ')+name} aria-pressed={!hiddenClasses[name]} title={hiddenClasses[name]?'Show this class':'Hide this class (keeps annotations)'} onClick={()=>toggleClass(name)}>{hiddenClasses[name]?<EyeOff size={14}/>:<Eye size={14}/>}</Button></div>)}</div><Button variant="ghost" size="sm" onClick={()=>open('projectSettings',{projectId:project!.id})}><Settings2 size={14}/>Edit classes</Button><Button variant="outline" size="sm" onClick={()=>open('addClass')}><Plus size={14}/>Add class</Button></div>
    <div className="canvas-toolbar" role="toolbar" aria-label="Canvas tools">
     <div className="canvas-tool-group" role="group" aria-label="Box actions">
      <CanvasToolButton label="Copy to class…" title="Copy boxes to another class" disabled={!canvasControls.ready||!identity||s.hiddenIds[activeId]} onClick={()=>act('copyClass')}><CopyToClassIcon/></CanvasToolButton>
      <CanvasToolButton label="Delete range" title="Delete boxes in a frame range (Shift+Delete)" disabled={!canvasControls.ready||!activeId} onClick={()=>act('hiddenRange')}><DeleteRangeIcon/></CanvasToolButton>
      <CanvasToolButton label="Restore range" title="Restore boxes in a deleted range" disabled={!canvasControls.ready||!activeId} onClick={()=>act('restoreRange')}><RestoreRangeIcon/></CanvasToolButton>
     </div>
     <span className="canvas-tool-divider" aria-hidden="true"/>
     <div className="canvas-tool-group" role="group" aria-label="Drawing tools">
      <CanvasToolButton label="Select and move (V)" aria-pressed={canvasControls.tool==='select'} disabled={!canvasControls.ready} onClick={()=>canvas.current?.tool('select')}><MousePointer2/></CanvasToolButton>
      <CanvasToolButton label="Draw box (B)" title="Draw or replace selected box (B)" aria-pressed={canvasControls.tool==='draw'} disabled={!canvasControls.ready} onClick={()=>canvas.current?.tool('draw')}><SquareDashed/></CanvasToolButton>
      <CanvasToolButton label="Hand tool (H)" title="Pan image (H) · Space temporarily pans" aria-pressed={canvasControls.tool==='hand'} disabled={!canvasControls.ready} onClick={()=>canvas.current?.tool('hand')}><Hand/></CanvasToolButton>
     </div>
     <span className="canvas-tool-divider" aria-hidden="true"/>
     <div className="canvas-tool-group" role="group" aria-label="Canvas zoom">
      <CanvasToolButton label="Zoom in" disabled={!canvasControls.ready||canvasControls.scale>=20} onClick={()=>canvas.current?.zoom(1.25)}><Plus/></CanvasToolButton>
      <CanvasToolButton label="Zoom out" disabled={!canvasControls.ready||canvasControls.scale<=.04} onClick={()=>canvas.current?.zoom(.8)}><Minus/></CanvasToolButton>
      <CanvasToolButton label="Fit video" title="Fit video (0)" disabled={!canvasControls.ready} onClick={()=>{canvas.current?.finish();canvas.current?.fit()}}><Maximize/></CanvasToolButton>
      <span className="canvas-tool-zoom" aria-label="Canvas zoom level">{Math.round(canvasControls.scale*100)}%</span>
     </div>
     <div className="editing-context" aria-live="polite">{identity?<><strong>Editing {identity.person_id?`Track ${identity.person_id}`:identity.name}</strong><span>· {geometryLabel(geometry,identity)}</span><CanvasToolButton label="Change ID or class" title="Change track ID, class and color (I)" onClick={()=>act('id')}><Tags/></CanvasToolButton>{hiddenClasses[boxStyle(identity,geometry).class_name]&&<CanvasToolButton label="Show class to edit" onClick={()=>chooseClass(boxStyle(identity,geometry).class_name)}><Eye/></CanvasToolButton>}</>:<span>Click New track, choose a class, then draw a box.</span>}</div>
     <div className="canvas-tool-group" role="group" aria-label="Edit history">
      <CanvasToolButton label="Undo" title="Undo (Ctrl+Z)" onClick={()=>act('undo')} disabled={!s.history.length}><Undo2/></CanvasToolButton>
      <CanvasToolButton label="Redo" title="Redo (Ctrl+Shift+Z)" onClick={()=>act('redo')} disabled={!s.redoStack.length}><Redo2/></CanvasToolButton>
     </div>
    </div>
    <EditorCanvas onControlsChange={setCanvasControls} onAction={act} dimOutside={true} hiddenClasses={hiddenClasses} ref={canvas} proposals={filteredProposals} showProposals={!VISIBLE_ONLY&&showProposals}/>
    <div className="box-status">{activeId&&!getBox(active,geometry)&&<div className="gap-banner"><AlertTriangle size={14}/><span title={activeGap?`Interpolation paused: ${geometryLabel(geometry,identity)} boxes were deleted on frames ${activeGap.start}–${activeGap.end??((video?.frame_count||1)-1)}.`:undefined}>{activeGap?<>Interpolation paused: {geometryLabel(geometry,identity)} boxes were deleted on frames {activeGap.start}–{activeGap.end??((video?.frame_count||1)-1)}.</>:<>No {geometryLabel(geometry,identity).toLowerCase()} box yet. Draw one for this track; the ID stays the same.</>}</span>{activeGap&&<Button variant="outline" size="xs" onClick={()=>act('restoreRange')}>Restore deleted range</Button>}{activeGap?.end!=null&&activeGap.end+1<(video?.frame_count||0)&&<Button variant="outline" size="xs" onClick={()=>{canvas.current?.finish();s.navigate(activeGap.end!+1)}}>Go to frame {activeGap.end+1}</Button>}</div>}</div>

   </section>
   {leftOpen&&<aside className="people-panel resizable"><div className="panel-heading"><span>Tracks</span><span className="count">{videoTracks.length}</span><Button variant="ghost" size="icon-sm" className="icon-button" aria-label="New track" title="New track (N)" onClick={()=>act('new')}><Plus size={17}/></Button></div><div className="people-search"><Search size={14}/><Input aria-label="Search tracks" placeholder="Find an ID or class…" value={filter} onChange={e=>setFilter(e.target.value)}/></div><div className="person-list">{videoTracks.sort((a,b)=>(a.person_id??Number.MAX_SAFE_INTEGER)-(b.person_id??Number.MAX_SAFE_INTEGER)||a.name.localeCompare(b.name)).filter(p=>('Track '+(p.person_id??'')+' '+p.name+' '+personClasses[p.id]?.map(c=>c.class_name).join(' ')).toLowerCase().includes(filter.toLowerCase())).map((p,i)=>{const name=p.person_id?'Track '+p.person_id:p.name;return <div key={p.id} className={'person-row '+(s.hiddenIds[p.id]?'is-hidden ':'')+(p.id===activeId?'selected':'')}><Button variant="ghost" size="sm" className="person h-auto justify-start whitespace-normal rounded-xl border-0" aria-label={'Select '+name} aria-pressed={p.id===activeId} onClick={()=>{canvas.current?.finish();s.selectPerson(p.id)}}><span className="person-avatar">{p.person_id??String(i+1).padStart(2,'0')}</span><span className="person-text"><strong>{name}</strong><span className="person-classes">{personClasses[p.id]?.map(c=><small key={c.geometry} title={c.class_name}><i style={{background:c.color}}/>{c.class_name}</small>)}</span></span></Button><div className="person-actions"><Button variant="ghost" size="icon-sm" className="icon-button" aria-label={(s.hiddenIds[p.id]?'Show ':'Hide ')+name} title={s.hiddenIds[p.id]?'Show boxes':'Hide boxes (keeps annotations)'} aria-pressed={!s.hiddenIds[p.id]} onClick={()=>{canvas.current?.finish();s.togglePersonVisibility(p.id)}}>{s.hiddenIds[p.id]?<EyeOff size={14}/>:<Eye size={14}/>}</Button><Button variant="ghost" size="icon-sm" className="icon-button" aria-label={'Focus '+name} title="Show only this track" onClick={()=>{canvas.current?.finish();s.focusPerson(p.id)}}><Focus size={14}/></Button><Button variant="ghost" size="icon-sm" className="icon-button delete-person" aria-label={'Delete '+name} title="Delete track and its annotations" onClick={()=>open('deletePerson',{target:p.id,name})}><Trash2 size={14}/></Button></div></div>})}{!videoTracks.length&&<div className="empty-people"><ScanLine size={26}/><p>Start with one object.</p><span>Press <kbd>N</kbd>, choose a class, then draw its box.</span></div>}</div><div className="people-bottom">{Object.values(s.hiddenIds).some(Boolean)&&<Button variant="outline" size="sm" onClick={s.showAllPeople}><Eye size={15}/>Show all tracks</Button>}<Button variant="outline" size="sm" onClick={()=>act('new')}><Plus size={15}/>New track <kbd>N</kbd></Button></div></aside>}
   {rightOpen&&<aside className="metadata-panel shortcut-panel"><div className="panel-heading">Shortcuts</div><p>Select a track on the right, then use these keys.</p>{[['a',classNames[0]||'First class'],['b',classNames[1]||'Second class'],['new','New track'],['id','ID, class & color'],['next','Next frame'],['previous','Previous frame'],['ahead','Forward 10 frames'],['back','Back 10 frames'],['copy','Copy previous box'],['interpolate','Fill between boxes'],['hiddenRange','Delete boxes in range'],['restoreRange','Restore deleted range'],['remove','Delete box on this frame'],['undo','Undo'],['redo','Redo'],['save','Save'],['fit','Fit video']].map(([a,label])=><Button variant="outline" size="sm" key={a} onClick={()=>act(a)} disabled={!activeId&&['id','copy','interpolate','hiddenRange','restoreRange','gap','resume','finish','remove'].includes(a)}><span>{label}</span>{keys[a]&&<kbd>{keys[a].replace('ctrl','Ctrl').replace('shift','Shift').toUpperCase()}</kbd>}</Button>)}<hr/><p><strong>Move:</strong> drag inside a box.<br/><strong>Resize:</strong> drag an edge or corner.<br/><strong>Replace:</strong> Alt + drag.<br/><strong>Zoom:</strong> scroll.<br/><strong>Pan:</strong> hold Space and drag.<br/><strong>Play/pause:</strong> tap Space.</p><p>Use the eye to hide a person, or Focus to show only them. Hidden boxes remain saved.</p><Button variant="outline" size="sm" onClick={()=>open('help')}>All shortcuts</Button></aside>}

  </main>
  <FrameTimeline controls={playbackControls} bins={timelineBins} active={!!identity} label={identity?`Track ${identity.person_id??identity.name} · ${geometryLabel(geometry,identity)}`:'Select a track to see its frames'} color={boxStyle(identity,geometry).color} frame={frame} count={video?.frame_count||0} onSeek={target=>{canvas.current?.finish();setPlaying(false);s.navigate(target)}}/>
 </>}
 {notice&&<div className="toast" role="status">{notice}</div>}
 {modal&&<Modal title={{projectSettings:'Project settings',annotationImport:'Import annotations',finishPrompt:'Review before finishing',restoreRange:'Restore deleted range',guide:'Learn Frameinsight',about:'About Frameinsight',backup:'Back up your project',addClass:'Add class',hiddenRange:'Delete boxes in range',newVideo:'New video',finishVideo:'Finish video',newProject:'Create project',projects:'Your projects',import:'Add a video',id:'Track ID, class & color',copyClass:'Copy boxes to another class',deletePerson:'Delete track',unknown:'Full extent unknown',gap:'Start an invisible interval',resume:'Resume at this visible frame',identity:'Identity & segment decisions',complete:'Whole-frame completeness check',help:'Shortcuts & commands',export:'Export your annotations',detector:'Detector proposals',issues:'Review issues',diagnostics:'Local system diagnostics',suggestions:'Inspect detector suggestions'}[modal]||modal} onClose={()=>{if(!uploadBusy&&!loading)setModal(modal==='projectSettings'?form.returnTo||'':'')}} busy={uploadBusy||loading} wide={['import','help','export','issues'].includes(modal)}>
  {error&&<div className="error" role="alert">{error}</div>}
  {modal==='hiddenRange'&&<form onSubmit={e=>{e.preventDefault();if(s.markHiddenRange(Number(form.start),Number(form.end)))setModal('')}}><p>Delete <strong>{geometryLabel(geometry,identity)}</strong> boxes for <strong>{identity?.person_id?'Track '+identity.person_id:identity?.name}</strong>. Only this class is removed. Other classes stay unchanged. The deleted range pauses interpolation until you restore it. Both frame numbers are included.</p><label>First frame to delete<Input aria-label="First frame to delete" type="number" required min="0" max={(video?.frame_count||1)-1} step="1" value={form.start??''} onChange={e=>setForm({...form,start:e.target.value})}/></label><label>Last frame to delete<Input aria-label="Last frame to delete" type="number" required min={Math.max(0,Number(form.start)||0)} max={(video?.frame_count||1)-1} step="1" value={form.end??''} onChange={e=>setForm({...form,end:e.target.value})}/></label><p><strong>{Object.values(project!.state.observations).filter(o=>o.video_id===videoId&&o.identity_uuid===activeId&&o.frame_index>=Number(form.start)&&o.frame_index<=Number(form.end)&&getBox(o,geometry)).length} boxes</strong> will be removed for this track, including any drawn or adjusted boxes in the range. Boxes outside the range and other people are kept. Deleted frames stay empty until you restore them. Use Restore deleted range to recover boxes or fill between your corrections.</p><p>Example: keep boxes at 39 and 60; delete frames 40–59. Ctrl+Z restores this entire change.</p><div className="button-row"><Button variant="outline" size="sm" type="button" onClick={()=>setModal('')}>Cancel</Button><Button variant="destructive" size="sm" type="submit">Delete boxes</Button></div></form>}
  {modal==='finishPrompt'&&<><p>Play through the video and check your boxes, class names and track IDs. If you see a mistake, fix it in the editor before continuing.</p><p className="muted">Review uses the video already on the canvas. The next page checks annotation data and JSON structure.</p><div className="flex flex-wrap justify-end gap-2"><Button variant="ghost" onClick={()=>setModal('')}>Back to editing</Button><Button variant="outline" onClick={()=>{setModal('');s.showAllPeople();setHiddenClasses({});useStore.setState({activeId:''});s.navigate(0);setPlaybackRate(.5);setPlaying(true);s.toast('Review all tracks with playback. Correct any mistakes, then click Finish.')}}><Play/>Review in editor</Button><Button disabled={loading} onClick={()=>void task(async()=>{await s.saveNow();setFinishConfirmed(true);setModal('');setScreen('finish')})}>I reviewed — continue</Button></div></> }
  {modal==='projectSettings'&&<ProjectSettings projectId={form.projectId||project!.id} onBusy={setUploadBusy} onCancel={()=>setModal(form.returnTo||'')} onSaved={(updated,renames)=>{
   const visibilityKey='frameinsight:classVisibility:'+updated.id;
   const renameVisibility=(current:Record<string,boolean>)=>Object.fromEntries(Object.entries(current).map(([name,hidden])=>[renames[name]||name,hidden]));
   if(updated.id===project?.id)setHiddenClasses(current=>{const next=renameVisibility(current);try{localStorage.setItem(visibilityKey,JSON.stringify(next))}catch{}return next;});
   else try{localStorage.setItem(visibilityKey,JSON.stringify(renameVisibility(JSON.parse(localStorage.getItem(visibilityKey)||'{}'))))}catch{}
   setLibraryRevision(n=>n+1);setModal(form.returnTo||'');s.toast('Project settings saved. Existing annotations use the updated class names.');
  }}/>}
  {modal==='restoreRange'&&<RestoreRange initialStart={Number(form.start)} initialEnd={Number(form.end)} onClose={()=>setModal('')}/>}
  {modal==='guide'&&<Onboarding onDone={()=>setModal('')}/>}
  {modal==='about'&&<><p><strong>Frameinsight {APP_VERSION}</strong> · Local video annotation</p><p>Your videos and annotations stay on this computer. Named classes, interpolation, deleted-range recovery, full-video review and structural JSON validation.</p><p>Annotation export: JSON schema 3. Share this app version when reporting an issue.</p><Button variant="outline" size="sm" onClick={()=>{void task(async()=>setDiagnostics(await api('/system/diagnostics')));setModal('diagnostics');}}>View system details</Button></>}
  {modal==='backup'&&<BackupProject projectId={project!.id} videoId={videoId} onDone={()=>setModal('')}/>}
  {modal==='newVideo'&&<NewVideo projectId={libraryProject||project!.id} onCreated={openVideo} onBusy={setUploadBusy}/>}
  {modal==='annotationImport'&&<AnnotationImport onClose={()=>setModal('')} onBusy={setUploadBusy}/>}
  {modal==='deletePerson'&&<><p>Delete {form.name} and all {Object.values(project!.state.observations).filter(o=>o.identity_uuid===form.target).length} observations across this project’s videos? This also removes their visibility segments, gaps and identity links.</p><p>You can restore this with Ctrl+Z (Undo).</p><div className="button-row"><Button variant="outline" size="sm" onClick={()=>setModal('')}>Cancel</Button><Button variant="destructive" size="sm" onClick={()=>{if(s.deletePerson(form.target))setModal('')}}>Delete track and annotations</Button></div></>}
  {modal==='newProject'&&<NewProject onBusy={setUploadBusy} onCreated={id=>{setLibraryProject(id);setLibraryRevision(n=>n+1);setScreen('home');setModal('')}}/>}
  {modal==='projects'&&<><Button size="sm" className="primary" onClick={()=>open('newProject',{name:''})}><Plus size={15}/>New project</Button><Input aria-label="Find project" placeholder="Search projects…" value={form.search||''} onChange={e=>setForm({...form,search:e.target.value})}/><div className="project-list">{projects.filter(p=>p.name.toLowerCase().includes((form.search||'').toLowerCase())).map(p=><Button variant="outline" size="sm" key={p.id} onClick={()=>void task(async()=>{await s.load(p.id);setModal('')})}><FolderOpen size={19}/><span>{p.name}</span><ArrowRight size={16}/></Button>)}</div><hr/><h3>Restore a native archive</h3><p>Restore a portable ZIP with original videos, or an archive referencing originals still present on this machine. Source hashes are checked.</p><Input aria-label="Restore native archive" type="file" accept=".zip" onChange={e=>{const f=e.target.files?.[0];if(!f)return;void task(async()=>{const body=new FormData();body.append('file',f);setRestoreJob(await api('/imports/native',{method:'POST',body}))})}}/>{restoreJob&&<p>{restoreJob.status}{restoreJob.error?' · '+restoreJob.error:''}</p>}{restoreJob?.restored_project_id&&<Button variant="outline" size="sm" onClick={()=>void task(async()=>{await s.load(restoreJob.restored_project_id);setModal('')})}>Open restored project</Button>}</>}
  {modal==='import'&&<><p>Use a local video. The original is preserved; exact frames become editable during indexing.</p><label className="upload-box"><Upload size={24}/><span>{loading?'Importing…':'Choose a video from your computer'}</span><Input aria-label="Upload video" type="file" accept="video/*" disabled={loading} onChange={e=>{const f=e.target.files?.[0];if(!f)return;void task(async()=>{const data=new FormData();data.append('file',f);const r=await api(`/projects/${project!.id}/videos`,{method:'POST',body:data});useStore.setState({videoId:r.video_id,frame:0});setModal('')})}}/></label><h3>Videos in your workspace</h3><Input aria-label="Find video" placeholder="Filter filenames…" value={form.search||''} onChange={e=>setForm({...form,search:e.target.value})}/><div className="library-list">{library.filter(v=>v.name.toLowerCase().includes((form.search||'').toLowerCase())).map(v=><Button variant="outline" size="sm" key={v.path} disabled={loading} onClick={()=>void task(async()=>{const r=await post(`/projects/${project!.id}/videos/local`,{path:v.path});useStore.setState({videoId:r.video_id,frame:0});setModal('')})}><Play size={15}/><span>{v.name}<small>{v.path.split('/').slice(0,-1).join(' / ')}</small></span><span>{(v.bytes/1e6).toFixed(0)} MB</span></Button>)}</div></>}
  {modal==='copyClass'&&project&&identity&&<CopyClass project={project} videoId={videoId} trackId={activeId} initialSource={boxStyle(identity,geometry).class_name} classes={classNames} onClose={()=>setModal('')} onCopy={(source,target)=>{if(s.copyClassTrack(geometryForClass(identity,source),target)){setClassVisibility(target,false);setModal('')}}}/>}
  {modal==='addClass'&&<form onSubmit={e=>{e.preventDefault();void task(async()=>{const name=(form.class_name||'').trim();const result=await post(`/projects/${project!.id}/classes`,{name});useStore.setState({project:{...useStore.getState().project!,classes:result.classes,class_colors:result.class_colors}});chooseClass(name);setModal('')})}}><label>New class name<Input autoFocus aria-label="New class name" required maxLength={80} value={form.class_name||''} onChange={e=>setForm({...form,class_name:e.target.value})}/></label><p>A distinct color is chosen automatically. Each class has its own boxes and interpolation, under the same track ID.</p><Button size="sm" className="primary" disabled={loading}>Create class</Button></form>}
  {modal==='id'&&<form onSubmit={e=>{e.preventDefault();const n=form.id?Number(form.id):null;const target=form.target||Object.values(project!.state.identities).find(p=>n!==null&&p.person_id===n)?.id||activeId;void task(async()=>{const name=(form.class_name||'').trim();if(!name)throw new Error('Enter a class name');const result=await post(`/projects/${project!.id}/classes`,{name});useStore.setState({project:{...useStore.getState().project!,classes:result.classes,class_colors:result.class_colors}});if(s.assignPerson(target,n,name,form.color||result.class_colors[name],form.geometry as Geometry))setModal('')})}}>
   <p>Keep the same ID for the same object. Saving a different class here reassigns the selected class’s boxes across this track. To draw an additional class, close this dialog and choose it in the class bar.</p>
   {identity&&legacyExtended(identity)&&<p>This older track will keep its saved rectangles while joining the chosen ID. Other classes are kept. Undo restores the separate tracks.</p>}
   <label>Existing track ID<NativeSelect aria-label="Existing track ID" value={form.target||''} onChange={e=>{const person=project!.state.identities[e.target.value];setForm({...form,target:e.target.value,id:String(person?.person_id??identity?.person_id??''),...existingStyle(e.target.value)})}}><option value="">New number / current person</option>{Object.values(project!.state.identities).filter(p=>p.person_id!==null).sort((a,b)=>a.person_id!-b.person_id!).map(p=><option key={p.id} value={p.id}>Track {p.person_id}{p.id===activeId?' (current)':''}</option>)}</NativeSelect></label>
   <label>Positive numeric track ID<Input autoFocus aria-label="Track ID" type="number" min="1" step="1" value={form.id||''} onChange={e=>{const existing=Object.values(project!.state.identities).find(p=>p.person_id===Number(e.target.value));setForm({...form,id:e.target.value,target:existing?.id||'',...existingStyle(existing?.id||'')})}}/></label>
   <div className="class-buttons" aria-label="Choose class">{classNames.map(name=><Button variant="outline" size="sm" type="button" key={name} aria-pressed={form.class_name===name} onClick={()=>setForm({...form,class_name:name,color:classColor(project,name)})}><i style={{background:classColor(project,name)}}/>{name}</Button>)}<Button variant="outline" size="sm" type="button" onClick={()=>{setForm({...form,class_name:'',color:''});document.getElementById('identity-class-name')?.focus()}}><Plus size={14}/>Add class</Button></div>
   <label>Class name<Input id="identity-class-name" aria-label="Class name" list="class-names" required maxLength={80} value={form.class_name||''} onChange={e=>setForm({...form,class_name:e.target.value,color:project?.class_colors?.[e.target.value]||''})}/></label><datalist id="class-names">{classNames.map(name=><option key={name} value={name}/>)}</datalist><p>One ID can hold any number of named classes. Existing boxes are never overwritten when joining tracks.</p>
   <fieldset className="box-color-picker"><legend>Box color</legend><div role="group" aria-label="Box color">{NEW_BOX_COLORS.map(color=><Button variant="outline" size="icon-sm" key={color} type="button" aria-label={'Box color '+color} aria-pressed={form.color?.toLowerCase()===color} style={{background:color}} onClick={()=>setForm({...form,color})}>{form.color?.toLowerCase()===color&&<Check size={17}/>}</Button>)}</div>{form.color&&!isAllowedNewBoxColor(form.color)&&<small>Keeping the saved color. Choose a swatch to change it.</small>}<small>Red marks Hidden frames. White marks the current frame.</small></fieldset><Button size="sm" className="primary" disabled={loading}>Save ID</Button></form>}
  {modal==='unknown'&&<form onSubmit={e=>{e.preventDefault();editObservation('Full extent unknown',o=>{o.person_ext=null;o.full_quality='unknown';o.geometry_link='independent';o.evidence_note=form.note});useStore.setState({geometry:'person_visible'});setModal('')}}><p>Keep B as the visible evidence. A will be removed in one undoable action. This does not mark the person invisible.</p><label>Why is the full extent unsupported?<Textarea autoFocus required value={form.note||''} onChange={e=>setForm({...form,note:e.target.value})}/></label><Button size="sm" className="primary">Keep B, mark A unknown</Button></form>}
  {modal==='gap'&&<form onSubmit={beginGap}><p>Frame <strong>{frame}</strong> is the first completely invisible frame. There will be no positive boxes until you explicitly resume.</p><label>Cause<NativeSelect value={form.reason} onChange={e=>setForm({...form,reason:e.target.value})}><option value="occlusion">Fully occluded</option><option value="outside">Outside image</option><option value="unavailable">Unavailable footage</option><option value="unknown">Unknown cause</option></NativeSelect></label><label>Evidence note<Textarea value={form.note||''} onChange={e=>setForm({...form,note:e.target.value})}/></label><Button size="sm" className="primary">Start gap at frame {frame}</Button></form>}
  {modal==='resume'&&<form onSubmit={resume}><p>The gap closes at frame <strong>{frame-1}</strong>. Decide who is visible at frame <strong>{frame}</strong>.</p><label>Return identity<NativeSelect value={form.relation} onChange={e=>setForm({...form,relation:e.target.value})}><option value="same">Same verified person</option><option value="different">Different person · new identity</option><option value="unresolved">Uncertain · provisional identity</option></NativeSelect></label><label>Evidence for this decision<Textarea autoFocus required value={form.note||''} onChange={e=>setForm({...form,note:e.target.value})}/></label><Button size="sm" className="primary">Start visible segment</Button></form>}
  {modal==='identity'&&<><form onSubmit={identityAction}><label>Decision<NativeSelect value={form.action} onChange={e=>setForm({...form,action:e.target.value})}><option value="unresolved">Record unresolved relation</option><option value="different">Confirm different people</option><option value="merge">Merge as the same physical person</option></NativeSelect></label><label>Other identity<NativeSelect required value={form.target} onChange={e=>setForm({...form,target:e.target.value})}><option value="">Choose identity</option>{Object.values(project!.state.identities).filter(p=>p.id!==activeId).map(p=><option value={p.id} key={p.id}>{p.person_id?'Track '+p.person_id:p.name}</option>)}</NativeSelect></label><label>Evidence<Textarea required value={form.note||''} onChange={e=>setForm({...form,note:e.target.value})}/></label><Button size="sm" className="primary">Save identity decision</Button></form><hr/><h3>Segment boundary at frame {frame}</h3><div className="button-row"><Button variant="outline" size="sm" onClick={()=>splitSegment()}>Split segment, keep identity</Button><Button variant="outline" size="sm" onClick={()=>splitSegment(true)}>Unlink into provisional identity</Button><Button variant="outline" size="sm" onClick={()=>act('finish')}>Finish segment here</Button></div></>}
  {modal==='complete'&&<><p>Inspect the <strong>entire image</strong>, including people you have not worked on yet. This final check covers everyone together; there is no per-person approval step.</p><div className="review-summary"><span>{frameObs.length} people annotated</span><span>{filteredProposals.filter(p=>!frameObs.some(o=>Object.values(o.provenance).some(v=>v?.proposal_id===p.id))).length} unaccepted suggestions to consider</span></div>{frameObs.some(o=>observationIssues(o).length>0||project!.state.segments[o.segment_id]?.status!=='verified')&&<p className="error">Fix missing boxes or unresolved identities before marking this frame complete.</p>}<label className="checkbox"><Checkbox checked={checkAll} onCheckedChange={checked=>setCheckAll((checked===true))}/>I checked the whole frame for every visible person, including detector misses. If this is empty, I verified it is genuinely empty.</label><Button size="sm" className="primary" disabled={!checkAll||frameObs.some(o=>observationIssues(o).length>0||project!.state.segments[o.segment_id]?.status!=='verified')} onClick={()=>{s.commit('Frame reviewed-complete',d=>{const id=videoId+':'+frame;d.reviews[id]={id,video_id:videoId,frame_index:frame,complete:true,checked_all_people:true,note:''}});setModal('')}}>Mark frame {frame} complete</Button></>}
  {modal==='help'&&<><div className="button-row"><Button variant="outline" size="sm" onClick={()=>open('guide')}>Start guide</Button><Button variant="outline" size="sm" onClick={()=>open('about')}>About · {APP_VERSION}</Button>{project&&<Button variant="outline" size="sm" onClick={()=>open('backup')}>Back up project</Button>}</div><Input autoFocus placeholder="Search actions or shortcuts…" value={form.search||''} onChange={e=>setForm({...form,search:e.target.value})}/><p className="muted">Click a shortcut field to remap it. Space: tap to play/pause, hold and drag to pan. Drag a box to move it; drag a corner to resize it.</p><div className="shortcut-list">{Object.entries(keyDescriptions).filter(([a])=>a in defaultKeys).filter(([a,d])=>(d+' '+keys[a]).toLowerCase().includes((form.search||'').toLowerCase())).map(([a,d])=><div key={a}><Button variant="outline" size="sm" onClick={()=>{setModal('');setTimeout(()=>act(a),0)}}>{d}</Button><Input aria-label={'Shortcut '+d} value={keys[a]} onChange={e=>{const k={...keys,[a]:e.target.value.toLowerCase()};setKeys(k);localStorage.setItem('frameinsight:keys',JSON.stringify(k))}}/></div>)}</div><Button variant="outline" size="sm" onClick={()=>{setKeys(defaultKeys);localStorage.removeItem('frameinsight:keys')}}>Reset defaults</Button></>}
  {modal==='issues'&&<div className="issue-list">{!VISIBLE_ONLY&&unknownFullCount>0&&<p>{unknownFullCount} observations have unknown full extent. These are valid visible annotations; full/dual YOLO export excludes their frames.</p>}{unresolvedLinkCount>0&&<p>{unresolvedLinkCount} unresolved identity links block MOT export. Native and visible-only exports retain this uncertainty.</p>}{issues.length?issues.map(({o,messages})=><Button variant="outline" size="sm" key={o.id} onClick={()=>{s.navigate(o.frame_index);useStore.setState({activeId:o.identity_uuid});setModal('')}}><span className="issue-frame">{o.frame_index}</span><span><strong>{project!.state.identities[o.identity_uuid].person_id?'Track '+project!.state.identities[o.identity_uuid].person_id:project!.state.identities[o.identity_uuid].name}</strong><small>{messages.join(' · ')}</small></span><ArrowRight size={15}/></Button>):<p>No observation errors. Frame completeness is checked separately.</p>}</div>}
  {modal==='detector'&&<><p>Only suggestions explicitly mapped to person_visible appear in this workflow. The supplied full-extent model remains hidden; use it for visible boxes only if that matches its training labels. Suggestions never establish identity or approval.</p><form onSubmit={e=>{e.preventDefault();void task(async()=>{await post(`/videos/${videoId}/proposal-jobs`,{model:form.model,device:form.device,confidence:Number(form.confidence),imgsz:Number(form.imgsz),batch_size:Number(form.batch_size),class_mapping:JSON.parse(form.mapping)});s.toast('Detector pass queued. Editing remains available.');setModal('')})}}><label>Trusted model<NativeSelect value={form.model} onChange={e=>setForm({...form,model:e.target.value})}>{models.map(m=><option key={m.name}>{m.name}</option>)}</NativeSelect></label><div className="form-grid"><label>Device<NativeSelect value={form.device} onChange={e=>setForm({...form,device:e.target.value})}><option value="0">CUDA GPU 0</option><option value="cpu">CPU (explicit)</option></NativeSelect></label><label>Image size<Input type="number" min="128" max="2048" step="32" value={form.imgsz} onChange={e=>setForm({...form,imgsz:e.target.value})}/></label><label>Saved candidate threshold<Input type="number" min=".001" max="1" step=".01" value={form.confidence} onChange={e=>setForm({...form,confidence:e.target.value})}/></label><label>Batch size<Input type="number" min="1" max="16" value={form.batch_size} onChange={e=>setForm({...form,batch_size:e.target.value})}/></label></div><label>Confirmed model class → geometry mapping<Input required value={form.mapping} onChange={e=>setForm({...form,mapping:e.target.value})}/></label><p className="muted">Changing display confidence only filters saved candidates. Run a new pass to lower the inference threshold.</p><Button size="sm" className="primary" disabled={loading||!models.length||video?.status!=='ready'}>Run every source frame</Button></form><div className="job-list">{jobs.filter(j=>j.kind==='proposals').slice(0,6).map(j=><div key={j.id}><strong>{j.status} · {j.progress} / {j.total||'?'}</strong><small>{j.error||j.phase}</small>{['queued','running'].includes(j.status)&&<Button variant="outline" size="sm" onClick={()=>void post('/jobs/'+j.id+'/cancel')}>Cancel pass</Button>}</div>)}</div><Button variant="outline" size="sm" onClick={()=>void post('/worker/stop').then(()=>s.toast('GPU worker stopped. Manual editing stays available.'))}>Stop GPU worker</Button></>}

  {modal==='suggestions'&&<><p>Inspect each crop. Accept only the selected geometry, or reject false positives and duplicates. Rejection is saved separately and can be undone.</p><label>Rejection reason<Input value={form.reason||''} onChange={e=>setForm({...form,reason:e.target.value})}/></label><div className="proposal-review-list">{proposals.filter(p=>(!VISIBLE_ONLY||p.geometry==='person_visible')&&p.confidence>=threshold).map(p=>{const rejected=project!.state.proposal_reviews?.[p.id],scale=Math.min(210/(p.box[2]-p.box[0]),150/(p.box[3]-p.box[1]));return <div key={p.id}><div className="proposal-crop" style={{width:Math.max(20,(p.box[2]-p.box[0])*scale),height:Math.max(20,(p.box[3]-p.box[1])*scale)}}><img src={`/api/videos/${videoId}/frames/${frame}`} style={{width:video!.width*scale,height:video!.height*scale,left:-p.box[0]*scale,top:-p.box[1]*scale}}/></div><span>{VISIBLE_ONLY?'Visible person':p.geometry==='person_ext'?'A':'B'} · {Math.round(p.confidence*100)}%</span>{rejected?<><small>Rejected: {rejected.reason}</small><Button variant="outline" size="sm" onClick={()=>s.commit('Restore suggestion',d=>{delete d.proposal_reviews[p.id]})}>Restore suggestion</Button></>:<div className="button-row"><Button variant="outline" size="sm" disabled={!activeId} onClick={()=>{s.setBox(p.geometry,p.box,p);setModal('')}}>Attach to active person</Button><Button variant="outline" size="sm" onClick={()=>rejectProposal(p)}>Reject suggestion</Button></div>}</div>})}</div></>}
  {modal==='diagnostics'&&<><pre className="diagnostics">{diagnostics?JSON.stringify(diagnostics,null,2):'Checking system…'}</pre>{video?.status==='failed'&&<Button variant="outline" size="sm" onClick={()=>void post(`/videos/${videoId}/retry-index`).then(()=>setModal(''))}>Retry interrupted indexing</Button>}<p className="muted">Bound to localhost. Footage, models, annotations and exports stay on this machine.</p></>}
 </Modal>}
 </div>;
}
