import {useEffect,useRef,useState,useMemo} from 'react';
import {Activity,ArrowLeft,ArrowRight,Check,CheckCheck,ChevronDown,ChevronLeft,ChevronRight,Download,FolderOpen,HelpCircle,Layers,Maximize,MoreHorizontal,Pause,Play,Plus,Redo2,Search,Settings2,ShieldCheck,Undo2,Upload,X,AlertTriangle,Eye,EyeOff,ScanLine,Link2,PanelLeftClose,PanelRightClose,Trash2,Focus,Save} from 'lucide-react';
import {VideoLibrary,NewVideo} from './VideoLibrary';
import {EditorCanvas,type CanvasHandle} from './Canvas';
import {api,post} from './api';
import {useStore} from './store';
import {isInterpolated} from './interpolation';
import {VISIBLE_ONLY} from './types';
import {timelineBins as buildTimelineBins} from './timeline';
import {currentObservation,frameObservations,observationIssues,type Project,type Job,type Proposal,type FrameInfo,type Geometry,type Domain,uuid} from './types';
const defaultKeys:Record<string,string>={hiddenRange:'shift+delete',save:'ctrl+s',next:'f',previous:'d',ahead:'shift+f',back:'shift+d',a:'1',b:'2',swap:'tab',new:'n',id:'i',equal:'e',occluded:'o',estimated:'r',unknown:'u',copy:'c',approve:'enter',approveStay:'shift+enter',complete:'ctrl+enter',gap:'g',resume:'h',finish:'t',remove:'delete',undo:'ctrl+z',redo:'ctrl+shift+z',fit:'0',help:'?',issues:']',interpolate:'k'};
if(VISIBLE_ONLY)for(const key of ['a','b','swap','equal','estimated','unknown','approve','approveStay'])delete defaultKeys[key];
if(VISIBLE_ONLY){defaultKeys.advance='enter';for(const key of ['complete','occluded','issues'])delete defaultKeys[key];}
const keyDescriptions:Record<string,string>={hiddenRange:'Delete boxes in a frame range',save:'Save your work',advance:'Next frame (automatically saved)',next:'Next exact frame',previous:'Previous exact frame',ahead:'Forward 10 frames',back:'Back 10 frames',a:'Select A · full extent',b:'Select B · visible extent',swap:'Switch A / B',new:'New person',id:'Choose person ID, class and color',equal:'Clear person · A = B',occluded:'Toggle external occlusion',estimated:'Full extent estimated',unknown:'Full extent unknown',copy:'Copy previous box',approve:'Approve person and advance',approveStay:'Approve person, stay',complete:'Whole-frame completeness check',gap:'Start invisible gap',resume:'Resume / decide returning identity',finish:'End this person’s track here',remove:'Delete box on this frame',undo:'Undo',redo:'Redo',fit:'Fit image',help:'Search shortcuts',issues:'Next review issue',interpolate:'Fill between keyframes'};
function keyName(e:KeyboardEvent){return ((e.ctrlKey||e.metaKey)?'ctrl+':'')+(e.shiftKey&&e.key!=='?'?'shift+':'')+e.key.toLowerCase();}
function clock(seconds:number|null|undefined){if(seconds==null)return 'PTS unavailable';return `${Math.floor(seconds/60).toString().padStart(2,'0')}:${(seconds%60).toFixed(3).padStart(6,'0')}`;}
function Button({children,...props}:React.ButtonHTMLAttributes<HTMLButtonElement>){return <button {...props}>{children}</button>}
function Modal({title,children,onClose,wide=false}:{title:string;children:React.ReactNode;onClose:()=>void;wide?:boolean}){return <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><section role="dialog" aria-modal="true" aria-label={title} className={'modal '+(wide?'wide':'')}><header><h2>{title}</h2><button aria-label="Close dialog" onClick={onClose}><X size={19}/></button></header>{children}</section></div>}
export default function App(){
 const s=useStore(),{project,videoId,frame,activeId,geometry,saveStatus,notice}=s;
 const [projects,setProjects]=useState<{id:string;name:string}[]>([]),[modal,setModal]=useState(''),[loading,setLoading]=useState(false),[error,setError]=useState(''),[library,setLibrary]=useState<any[]>([]),[jobs,setJobs]=useState<Job[]>([]),[proposals,setProposals]=useState<Proposal[]>([]),[ledger,setLedger]=useState<FrameInfo[]>([]),[models,setModels]=useState<any[]>([]),[playing,setPlaying]=useState(false),[ghosts,setGhosts]=useState(false),[showProposals,setShowProposals]=useState(true),[threshold,setThreshold]=useState(.25),[cacheKey,setCacheKey]=useState(''),[leftOpen,setLeftOpen]=useState(true),[rightOpen,setRightOpen]=useState(true),[filter,setFilter]=useState(''),[keys,setKeys]=useState<Record<string,string>>(()=>{try{return Object.fromEntries(Object.entries({...defaultKeys,...JSON.parse(localStorage.getItem('frameinsight:keys')||'{}')}).filter(([key,value])=>key in defaultKeys&&typeof value==='string')) as Record<string,string>}catch{return defaultKeys}}),[workerStatus,setWorkerStatus]=useState(false);
 const [screen,setScreen]=useState<'home'|'editor'>('home'),[uploadBusy,setUploadBusy]=useState(false);
 const [restoreJob,setRestoreJob]=useState<any>(null);
 const [form,setForm]=useState<Record<string,string>>({}),[checkAll,setCheckAll]=useState(false),[diagnostics,setDiagnostics]=useState<any>(null);
 const canvas=useRef<CanvasHandle>(null),note=useRef<HTMLTextAreaElement>(null),playTimer=useRef<number>(0),spaceTime=useRef(0),lastStep=useRef(0);
 const activeGpuJob=jobs.find(j=>j.kind==='proposals'&&j.video_id===videoId&&['running','queued'].includes(j.status));
 const video=project?.videos[videoId],active=currentObservation(project,videoId,frame,activeId),identity=project?.state.identities[activeId];
 const frameObs=frameObservations(project,videoId,frame);
 const activeGap=project&&Object.values(project.state.intervals).find(g=>g.video_id===videoId&&g.identity_uuid===activeId&&g.start<=frame&&(g.end===null||frame<=g.end));
 const review=project?.state.reviews[videoId+':'+frame];
 const issues=useMemo(()=>project?Object.values(project.state.observations).filter(o=>o.video_id===videoId).flatMap(o=>{const messages=observationIssues(o);if(!VISIBLE_ONLY&&o.review_state!=='approved')messages.push('Observation not approved');if(project.state.segments[o.segment_id]?.status==='unresolved')messages.push('Unresolved return identity');return messages.length?[{o,messages}]:[]}):[],[project?.state.observations,project?.state.segments,videoId]);
 const unknownFullCount=useMemo(()=>project?Object.values(project.state.observations).filter(o=>o.video_id===videoId&&o.full_quality==='unknown').length:0,[project?.state.observations,videoId]);
 const unresolvedLinkCount=useMemo(()=>project?Object.values(project.state.links).filter(l=>l.relation==='unresolved').length:0,[project?.state.links]);
 useEffect(()=>{if(!restoreJob?.id||['completed','failed'].includes(restoreJob.status))return;const timer=setInterval(()=>void api('/jobs/'+restoreJob.id).then(j=>{setRestoreJob(j);if(j.status==='completed')void refreshProjects()}),1500);return()=>clearInterval(timer)},[restoreJob?.id,restoreJob?.status]);
 async function refreshProjects(){setProjects(await api('/projects'))}

 useEffect(()=>{if(!project)return;let gone=false;let socket:WebSocket|null=null;let retry=0;
 const connect=()=>{socket=new WebSocket(`${location.protocol==='https:'?'wss':'ws'}://${location.host}/api/projects/${project.id}/events`);socket.onmessage=e=>{if(gone)return;const data=JSON.parse(e.data);if(data.heartbeat)return;setJobs(data.jobs);setWorkerStatus(data.worker.running);const current=useStore.getState();if(current.project?.id===project.id){useStore.setState({project:{...current.project,videos:data.videos}});if(!current.pending.length&&data.revision>current.project.revision)void api<Project>('/projects/'+project.id).then(remote=>{const live=useStore.getState();if(live.project?.id===remote.id&&!live.pending.length&&remote.revision>live.project.revision){useStore.setState({project:remote,history:[],redoStack:[]});live.toast('Project refreshed from server; operation history remains saved.')}}).catch(()=>{});}};socket.onclose=()=>{if(!gone)retry=window.setTimeout(connect,2500)};};connect();return()=>{gone=true;clearTimeout(retry);socket?.close()};},[project?.id]);
 useEffect(()=>{if(!videoId)return;let gone=false;void api<FrameInfo[]>('/videos/'+videoId+'/ledger').then(x=>{if(!gone){setLedger(x);useStore.setState({frameTimes:{...useStore.getState().frameTimes,[videoId]:x.map(f=>f.seconds)}})}});return()=>{gone=true}},[videoId,video?.frame_count]);
 useEffect(()=>{if(VISIBLE_ONLY||!videoId)return;let gone=false;setProposals([]);const fetch=()=>void api<Proposal[]>(`/videos/${videoId}/proposals?start=${frame}&end=${frame}`).then(x=>{if(!gone)setProposals(x)});fetch();const timer=setInterval(fetch,2000);return()=>{gone=true;clearInterval(timer)}},[videoId,frame]);
 useEffect(()=>{if(VISIBLE_ONLY)return;const j=jobs.find(j=>j.kind==='proposals'&&j.video_id===videoId&&j.status==='running');if(j)void post(`/jobs/${j.id}/priority/${frame}`)},[videoId,frame]);
 useEffect(()=>{if(!playing)return;const tick=()=>{const st=useStore.getState(),v=st.project?.videos[st.videoId];if(!v||st.frame>=v.frame_count-1){setPlaying(false);return;}if(canvas.current?.isReady())st.navigate(st.frame+1);playTimer.current=window.setTimeout(tick,Math.max(40,((ledger[st.frame+1]?.seconds??0)-(ledger[st.frame]?.seconds??0))*1000||100));};playTimer.current=window.setTimeout(tick,100);return()=>clearTimeout(playTimer.current)},[playing,ledger]);
 useEffect(()=>{if(note.current)note.current.value=active?.evidence_note||''},[active?.id,active?.evidence_note]);
 function editObservation(label:string,fn:Parameters<typeof s.editObservation>[1]){if(!canvas.current?.isReady()){s.toast('Wait for the exact frame to load');return;}s.editObservation(label,fn)}
 function open(name:string,initial:Record<string,string>={}){if(['complete','unknown','suggestions','identity'].includes(name)&&!canvas.current?.isReady()){s.toast('Wait for the exact frame to load');return;}canvas.current?.finish();setPlaying(false);setForm(initial);setError('');setCheckAll(false);setFilter('');setModal(name)}
 function step(delta:number){canvas.current?.finish();setPlaying(false);s.navigate(useStore.getState().frame+delta)}
 function nextIssue(){const next=issues.find(i=>i.o.frame_index>frame)||issues[0];if(next){canvas.current?.finish();s.navigate(next.o.frame_index);s.selectPerson(next.o.identity_uuid);}else s.toast('No observation issues in this video. Whole-frame completeness still needs checking.');}
 function act(action:string){
  if(VISIBLE_ONLY&&['a','b','swap','equal','estimated','unknown','approve','approveStay'].includes(action))return;
  if(action==='save'){void task(async()=>{canvas.current?.finish();await s.saveNow();s.toast('All changes saved.');});return;}
  if(action==='help'){open('help');return;}if(!video)return;
  if(['advance','next','previous','ahead','back'].includes(action)){step({advance:1,next:1,previous:-1,ahead:10,back:-10}[action]!);return;}
  if(action==='undo'||action==='redo'){canvas.current?.finish();s[action]();return;}
  if(action==='fit'){canvas.current?.fit();return;}
  if(!canvas.current?.isReady()){s.toast('Wait for the exact frame to load');return;}
  canvas.current?.finish();
  if(action==='a'||action==='b'||action==='swap')useStore.setState({geometry:action==='a'?'person_ext':action==='b'?'person_visible':s.geometry==='person_ext'?'person_visible':'person_ext'});
  else if(action==='new')s.newPerson();else if(action==='id'&&identity)open('id',{id:String(identity.person_id??''),target:'',class_name:identity.class_name||project?.classes?.[0]||'Person',color:identity.color||'#baa7ff'});else if(action==='equal')s.equal();
  else if(action==='occluded')editObservation('Toggle occlusion',o=>{o.occluded=!o.occluded;if(o.occluded)o.geometry_link='independent'});
  else if(action==='estimated')editObservation('Full extent estimated',o=>{o.full_quality='estimated'});
  else if(action==='unknown')open('unknown',{note:active?.evidence_note||''});
  else if(action==='hiddenRange'&&activeId)open('hiddenRange',{start:String(frame),end:String(frame)});
  else if(action==='copy')s.copyPrevious();else if(action==='remove')s.setBox(s.geometry,null);
  else if(action==='approve'||action==='approveStay'){if(s.approve()&&action==='approve')s.navigate(frame+1)}
  else if(action==='complete')open('complete');else if(action==='gap'&&activeId)open('gap',{reason:'occlusion',note:''});
  else if(action==='resume'&&activeId)open('resume',{relation:'same',note:''});
  else if(action==='finish'&&activeId){const finished=s.commit('Finish visible segment',d=>{const seg=Object.values(d.segments).find(x=>x.video_id===videoId&&x.identity_uuid===activeId&&x.start<=frame&&(x.end===null||x.end>=frame));if(!seg)throw new Error('No visible segment here');if(Object.values(d.observations).some(o=>o.segment_id===seg.id&&o.frame_index>frame))throw new Error('Later observations exist. Split the segment first.');seg.end=frame;});if(finished)s.toast('Segment finished at this frame. No exit was inferred.');}
  else if(action==='interpolate')s.fillInterpolation();
  else if(action==='issues')nextIssue();
 }
 useEffect(()=>{const down=(e:KeyboardEvent)=>{
  if(keyName(e)==='ctrl+s'){e.preventDefault();act('save');return;}
  if(screen!=='editor'&&e.key!=='Escape')return;
  const el=e.target as HTMLElement;if(e.isComposing||el.closest('input,textarea,select,[contenteditable="true"]'))return;
  if(e.key==='Escape'){if(uploadBusy||loading)return;canvas.current?.cancel();setModal('');setPlaying(false);return;}
  if(modal)return;
  if(e.code==='Space'){e.preventDefault();if(!e.repeat){spaceTime.current=Date.now();canvas.current?.space(true)}return;}
  const action=Object.keys(keys).find(a=>keys[a]===keyName(e));if(!action)return;if(action==='swap'&&e.key==='Tab'&&!el.closest('[data-testid=canvas]'))return;
  e.preventDefault();if(e.repeat&&!['next','previous'].includes(action))return;if(e.repeat&&Date.now()-lastStep.current<80)return;if(['next','previous'].includes(action))lastStep.current=Date.now();act(action);
 };const up=(e:KeyboardEvent)=>{if(e.code!=='Space')return;const panned=canvas.current?.space(false);if(modal||(e.target as HTMLElement).closest('input,textarea,select'))return;if(!panned&&Date.now()-spaceTime.current<350)setPlaying(p=>!p)};
 window.addEventListener('keydown',down);window.addEventListener('keyup',up);return()=>{window.removeEventListener('keydown',down);window.removeEventListener('keyup',up)}},[keys,modal,frame,video,activeId,active,project,identity,geometry,screen,uploadBusy,loading]);
 async function task(fn:()=>Promise<void>){setLoading(true);setError('');try{await fn()}catch(e){setError(String(e))}finally{setLoading(false)}}
 async function createProject(e:React.FormEvent){e.preventDefault();await task(async()=>{const p=await post<Project>('/projects',{name:form.name||'Untitled session'});await s.load(p.id);await refreshProjects();setModal('');});}
 async function showImport(){open('import');setLibrary(await api('/library'))}
 function beginGap(e:React.FormEvent){e.preventDefault();const success=s.commit('Start invisible gap',d=>{
  if(Object.values(d.intervals).some(g=>g.identity_uuid===activeId&&g.video_id===videoId&&(g.end===null||g.end>=frame)))throw new Error('An overlapping/later gap already exists');
  for(const o of Object.values(d.observations))if(o.video_id===videoId&&o.identity_uuid===activeId&&o.frame_index>=frame&&!o.person_ext&&!o.person_visible)delete d.observations[o.id];
  if(Object.values(d.observations).some(o=>o.video_id===videoId&&o.identity_uuid===activeId&&o.frame_index>=frame))throw new Error('This person has boxes on or after this frame. Remove or move those observations before opening a gap.');
  const seg=Object.values(d.segments).find(x=>x.video_id===videoId&&x.identity_uuid===activeId&&x.end===null);
  if(seg){if(seg.start===frame)delete d.segments[seg.id];else seg.end=frame-1;}
  const id=uuid();d.intervals[id]={id,video_id:videoId,identity_uuid:activeId,start:frame,end:null,reason:(form.reason||'occlusion') as any,evidence_note:form.note||''};
 });if(success)setModal('')}
 function resume(e:React.FormEvent){e.preventDefault();let selected=activeId;const success=s.commit('Resume visible segment · '+form.relation,d=>{
  const gap=Object.values(d.intervals).find(g=>g.video_id===videoId&&g.identity_uuid===activeId&&g.end===null);
  if(gap){if(frame<=gap.start)throw new Error('Resume on a later visible frame');gap.end=frame-1;}
  if(!gap&&Object.values(d.segments).some(g=>g.video_id===videoId&&g.identity_uuid===activeId&&g.end===null))throw new Error('Finish the existing segment first');
  if(form.relation!=='same'){
   selected=uuid();d.identities[selected]={id:selected,person_id:null,name:'Return draft '+(Object.keys(d.identities).length+1)};
   const id=uuid();d.links[id]={id,source:activeId,target:selected,relation:form.relation as any,evidence_note:form.note||''};
  }
  if(!form.note?.trim())throw new Error('Record evidence for the return decision');
  const id=uuid();d.segments[id]={id,video_id:videoId,identity_uuid:selected,start:frame,end:null,status:form.relation==='unresolved'?'unresolved':'verified'};
  if(gap)gap.evidence_note+=(gap.evidence_note?'\n':'')+'Return decision: '+form.relation+'. '+form.note;
 });if(success){useStore.setState({activeId:selected,geometry:VISIBLE_ONLY?'person_visible':'person_ext'});setModal('')}}
 function identityAction(e:React.FormEvent){e.preventDefault();const target=form.target;if(!target||target===activeId){setError('Choose another identity');return;}const success=s.commit('Identity '+form.action,d=>{
  if(!form.note?.trim())throw new Error('Identity decisions require evidence');
  if(form.action==='merge'){
   const mine=Object.values(d.observations).filter(o=>o.identity_uuid===activeId),other=Object.values(d.observations).filter(o=>o.identity_uuid===target);
   if(mine.some(a=>other.some(b=>a.video_id===b.video_id&&a.frame_index===b.frame_index)))throw new Error('Merge conflict: both identities have observations on the same frame');
   for(const o of mine){o.identity_uuid=target;o.review_state='draft'}
   for(const o of other)o.review_state='draft';
   for(const seg of Object.values(d.segments))if(seg.identity_uuid===activeId||seg.identity_uuid===target){seg.identity_uuid=target;seg.status='verified'}
   for(const g of Object.values(d.intervals))if(g.identity_uuid===activeId)g.identity_uuid=target;
   for(const l of Object.values(d.links)){if(l.source===activeId)l.source=target;if(l.target===activeId)l.target=target;if(l.source===l.target)delete d.links[l.id];}
   // Merge evidence is preserved in the observation notes and command history.
   for(const o of mine)o.evidence_note+=(o.evidence_note?'\n':'')+'Identity merge: '+form.note;
   delete d.identities[activeId];
  }else{const id=uuid();d.links[id]={id,source:activeId,target,relation:form.action as any,evidence_note:form.note};if(form.action==='different'){for(const seg of Object.values(d.segments))if(seg.identity_uuid===activeId&&seg.status==='unresolved')seg.status='verified';for(const l of Object.values(d.links))if(l.source===target&&l.target===activeId&&l.relation==='unresolved')l.relation='different';}}
 });if(success){if(form.action==='merge')useStore.setState({activeId:target});setModal('')}}
 function splitSegment(unlink=false){s.commit(unlink?'Unlink segment into new identity':'Split visible segment',d=>{
  const seg=Object.values(d.segments).find(x=>x.video_id===videoId&&x.identity_uuid===activeId&&x.start<frame&&(x.end===null||x.end>=frame));if(!seg)throw new Error('Choose a frame inside an existing segment, after its start');
  const id=uuid(),newIdentity=unlink?uuid():activeId;if(unlink)d.identities[newIdentity]={id:newIdentity,person_id:null,name:'Unlinked draft'};
  d.segments[id]={...seg,id,start:frame,identity_uuid:newIdentity,status:unlink?'unresolved':seg.status};seg.end=frame-1;
  for(const o of Object.values(d.observations))if(o.segment_id===seg.id&&o.frame_index>=frame){o.segment_id=id;o.identity_uuid=newIdentity;o.review_state='draft'};
  if(unlink){const link=uuid();d.links[link]={id:link,source:activeId,target:newIdentity,relation:'unresolved',evidence_note:'Segment unlinked for identity review'};}
 });setModal('')}
 const filteredProposals=proposals.filter(p=>(!VISIBLE_ONLY||p.geometry==='person_visible')&&p.confidence>=threshold&&(!cacheKey||p.cache_key===cacheKey)&&!project?.state.proposal_reviews?.[p.id]&&!frameObs.some(o=>Object.values(o.provenance).some(v=>v?.proposal_id===p.id)));
 function rejectProposal(p:Proposal){s.commit('Reject detector suggestion',d=>{d.proposal_reviews??={};d.proposal_reviews[p.id]={id:p.id,proposal_id:p.id,video_id:p.video_id,frame_index:p.frame_index,decision:'rejected',reason:form.reason||'Visually rejected: false positive or duplicate'}})}
 const timelineBins=useMemo(()=>buildTimelineBins(project?.state||null,videoId,video?.frame_count||0,activeId),[project?.state,videoId,activeId,video?.frame_count]);
 const completeCount=project?Object.values(project.state.reviews).filter(r=>r.video_id===videoId&&r.complete).length:0;
 async function openVideo(pid:string,vid:string){await s.saveNow();await s.load(pid);const current=useStore.getState();if(current.videoId!==vid)useStore.setState({videoId:vid,frame:0,activeId:''});setJobs([]);setScreen('editor');setModal('');}
 async function startVideo(){canvas.current?.finish();await s.saveNow();open('newVideo');}
 async function home(){canvas.current?.finish();setPlaying(false);await s.saveNow();setScreen('home');setModal('');}
 const classNames=[...new Set([...(project?.classes||[]),...Object.values(project?.state.identities||{}).map(p=>p.class_name).filter((c):c is string=>!!c)])];
 return <div className="app">
  <header className="topbar"><button className="brand" onClick={()=>void task(home)}><span className="brand-mark"><ScanLine size={23}/></span>frameinsight<span className="local-badge">LOCAL</span></button><div className="top-divider"/>{screen==='editor'&&project&&<><button className="project-switch" onClick={()=>void task(home)}><FolderOpen size={16}/>All videos</button><button onClick={()=>void task(startVideo)}><Plus size={16}/>New video</button></>}<div className="top-spacer"/>{screen==='editor'&&project&&<><span className={'save-status '+(saveStatus==='Save failed'?'danger':'')}><span className="status-dot"/>{saveStatus}</span><button onClick={()=>act('save')} disabled={loading}><Save size={16}/>Save</button><button className="primary" onClick={()=>open('finishVideo')} disabled={video?.status!=='ready'}><Check size={17}/>Finish</button></>}<button className="icon-button" aria-label="Help" onClick={()=>open('help')}><HelpCircle size={18}/></button></header>
  {screen==='home'||!project?<VideoLibrary onOpen={openVideo} onNew={()=>void task(startVideo)}/>:<>
  <div className="video-bar"><button className="icon-button" aria-label="Toggle people panel" onClick={()=>setLeftOpen(!leftOpen)}><PanelLeftClose size={17}/></button><select aria-label="Active video" value={videoId} onChange={e=>{canvas.current?.finish();setPlaying(false);useStore.setState({videoId:e.target.value,frame:0,activeId:''})}}><option value="" disabled>Select a video</option>{Object.values(project.videos).map(v=><option value={v.id} key={v.id}>{v.name}</option>)}</select><span className="video-state">{video?.status==='indexing'?`Indexing · ${video.frame_count} frames ready`:video?.status==='ready'?(video.finished_revision===project.revision?'Finished':'Ready'):video?.status}</span><span className="frame-counter">Frame <strong>{frame}</strong><span> / {Math.max(0,(video?.frame_count||1)-1)}</span></span><span className="timecode">{clock(ledger[frame]?.seconds)}</span><button className="icon-button" aria-label="Toggle shortcuts" onClick={()=>setRightOpen(!rightOpen)}><PanelRightClose size={17}/></button></div>
  {video?.status==='failed'&&<div className="save-error"><span>{video.error||'Preparing this video was interrupted.'}</span><button onClick={()=>void task(async()=>{await post(`/videos/${videoId}/retry-index`);s.toast('Preparing the video again…')})}>Retry loading video</button></div>}
  {s.saveError&&<div className="save-error"><AlertTriangle size={16}/><span>{s.saveError} · Your pending edits are retained.</span><button onClick={s.retry}>Retry save</button><button onClick={()=>{const blob=new Blob([JSON.stringify({project,pending:s.pending},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='frameinsight-recovery.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}}>Download recovery</button></div>}
  <main className="workspace">
   {leftOpen&&<aside className="people-panel resizable"><div className="panel-heading"><span>PEOPLE</span><span className="count">{Object.keys(project.state.identities).length}</span><button className="icon-button" aria-label="New person" title="New person (N)" onClick={()=>act('new')}><Plus size={17}/></button></div><div className="people-search"><Search size={14}/><input aria-label="Search people" placeholder="Find a person…" value={filter} onChange={e=>setFilter(e.target.value)}/></div><div className="person-list">{Object.values(project.state.identities).sort((a,b)=>(a.person_id??Number.MAX_SAFE_INTEGER)-(b.person_id??Number.MAX_SAFE_INTEGER)||a.name.localeCompare(b.name)).filter(p=>('Person '+(p.person_id??'')+' '+p.name).toLowerCase().includes(filter.toLowerCase())).map((p,i)=>{const o=frameObs.find(o=>o.identity_uuid===p.id),gap=Object.values(project.state.intervals).find(g=>g.video_id===videoId&&g.identity_uuid===p.id&&g.start<=frame&&(g.end===null||frame<=g.end));const name=p.person_id?'Person '+p.person_id:p.name;return <div key={p.id} className={'person-row '+(s.hiddenIds[p.id]?'is-hidden ':'')+(p.id===activeId?'selected':'')}><button className="person" onClick={()=>{canvas.current?.finish();s.selectPerson(p.id)}}><span className="person-avatar" style={{borderBottom:'3px solid '+(p.color||'#baa7ff')}}>{p.person_id??String(i+1).padStart(2,'0')}</span><span className="person-text"><strong>{name}</strong><small>{s.hiddenIds[p.id]?'Boxes hidden':o?.person_visible?(isInterpolated(o)?'Interpolated box':'Keyframe'):'Not visible'}</small></span></button><div className="person-actions"><button className="icon-button" aria-label={(s.hiddenIds[p.id]?'Show ':'Hide ')+name} title={s.hiddenIds[p.id]?'Show boxes':'Hide boxes (keeps annotations)'} aria-pressed={!s.hiddenIds[p.id]} onClick={()=>{canvas.current?.finish();s.togglePersonVisibility(p.id)}}>{s.hiddenIds[p.id]?<EyeOff size={14}/>:<Eye size={14}/>}</button><button className="icon-button" aria-label={'Focus '+name} title="Show only this person" onClick={()=>{canvas.current?.finish();s.focusPerson(p.id)}}><Focus size={14}/></button><button className="icon-button delete-person" aria-label={'Delete '+name} title="Delete person and their annotations" onClick={()=>open('deletePerson',{target:p.id,name})}><Trash2 size={14}/></button></div></div>})}{!Object.keys(project.state.identities).length&&<div className="empty-people"><Layers size={26}/><p>Start with one person.</p><span>Press <kbd>N</kbd>, then draw a box around them.</span></div>}</div><div className="people-bottom">{Object.values(s.hiddenIds).some(Boolean)&&<button onClick={s.showAllPeople}><Eye size={15}/>Show all people</button>}<button onClick={()=>act('new')}><Plus size={15}/>New person <kbd>N</kbd></button><p>Eye: hide boxes. Focus: show only one. Hidden boxes are still saved and exported.</p></div></aside>}
   <section className="editor-area"><div className="canvas-toolbar"><label className="interpolation-toggle" title="Fill frames between keyframes as editable drafts"><input type="checkbox" aria-label="Auto-interpolate" checked={s.autoInterpolate} onChange={s.toggleInterpolation}/>Auto-interpolate</label><button disabled={!activeId} onClick={()=>act('hiddenRange')} title="Delete boxes in a frame range (Shift+Delete); visibility updates automatically"><EyeOff size={15}/>Delete boxes in range</button><div className="toolbar-spacer"/><button className={'icon-button '+(ghosts?'toggled':'')} aria-label="Toggle previous-frame ghosts" title="Previous-frame ghosts" onClick={()=>setGhosts(!ghosts)}><Layers size={16}/></button><button className="icon-button" aria-label="Undo" title="Undo" onClick={()=>act('undo')} disabled={!s.history.length}><Undo2 size={16}/></button><button className="icon-button" aria-label="Redo" title="Redo" onClick={()=>act('redo')} disabled={!s.redoStack.length}><Redo2 size={16}/></button><button className="icon-button" aria-label="Fit image" title="Fit (0)" onClick={()=>canvas.current?.fit()}><Maximize size={16}/></button></div>
    <EditorCanvas ref={canvas} proposals={filteredProposals} showGhosts={ghosts} showProposals={!VISIBLE_ONLY&&showProposals}/>
    {activeId&&!active?.person_visible&&<div className="gap-banner"><EyeOff size={15}/>Not visible — no box on this frame. Draw a box here to make this person visible.{activeGap?.end!=null&&activeGap.end+1<(video?.frame_count||0)&&<button onClick={()=>{canvas.current?.finish();s.navigate(activeGap.end!+1)}}>Go to frame {activeGap.end+1}</button>}</div>}
    <div className="transport"><button className="icon-button" aria-label="Previous frame" onClick={()=>step(-1)}><ChevronLeft size={19}/></button><button className="icon-button" aria-label={playing?'Pause':'Play'} onClick={()=>{canvas.current?.finish();setPlaying(!playing)}}>{playing?<Pause size={17}/>:<Play size={17}/>}</button><button className="icon-button" aria-label="Next frame" onClick={()=>step(1)}><ChevronRight size={19}/></button><input aria-label="Go to frame" type="number" min={0} max={(video?.frame_count||1)-1} value={frame} onChange={e=>{canvas.current?.finish();s.navigate(Number(e.target.value))}}/><span className="muted">source frame</span><div className="toolbar-spacer"/><span className="muted">Boxes save automatically</span></div>
   </section>
   {rightOpen&&<aside className="metadata-panel shortcut-panel"><div className="panel-heading">USEFUL SHORTCUTS</div><p>Select a person on the left, then use these keys.</p>{[['new','New person'],['id','ID, class & color'],['next','Next frame'],['previous','Previous frame'],['ahead','Forward 10 frames'],['back','Back 10 frames'],['copy','Copy previous box'],['interpolate','Fill between boxes'],['hiddenRange','Delete boxes in range'],['remove','Delete box on this frame'],['undo','Undo'],['redo','Redo'],['save','Save'],['fit','Fit video']].map(([a,label])=><button key={a} onClick={()=>act(a)} disabled={!activeId&&['id','copy','interpolate','hiddenRange','gap','resume','finish','remove'].includes(a)}><span>{label}</span><kbd>{keys[a]?.replace('ctrl','Ctrl').replace('shift','Shift').toUpperCase()}</kbd></button>)}<hr/><p><strong>Move:</strong> drag inside a box.<br/><strong>Resize:</strong> drag an edge or corner.<br/><strong>Replace:</strong> Alt + drag.<br/><strong>Zoom:</strong> scroll.<br/><strong>Pan:</strong> hold Space and drag.<br/><strong>Play/pause:</strong> tap Space.</p><p>Use the eye to hide a person, or Focus to show only them. Hidden boxes remain saved.</p><button onClick={()=>open('help')}>All shortcuts</button></aside>}

  </main>
  <section className="timeline"><div className="timeline-title"><span>FRAMES</span><div className="legend"><i className="draft"/>Annotated<i className="gap"/>Gap</div><span className="review-progress">{video?.frame_count||0} frames</span><button className="subtle" onClick={()=>open('issues')}>{issues.length? <AlertTriangle size={13}/>:<Check size={13}/>} {issues.length} observation issues</button></div><div className="timeline-track">{timelineBins.map((b,i)=><button key={i} title={`Frame ${b.start}`} className={(b.complete?'complete':b.gap?'gap':b.draft?'draft':'')+(frame>=b.start&&frame<b.end?' current':'')} onClick={()=>{canvas.current?.finish();s.navigate(b.start)}}/>)}</div><div className="nearby">{video&&[-3,-2,-1,0,1,2,3].map(delta=>{const f=frame+delta;if(f<0||f>=video.frame_count)return null;const o=currentObservation(project,videoId,f,activeId);return <button className={delta===0?'current':''} key={f} onClick={()=>{canvas.current?.finish();s.navigate(f)}}><img src={`/api/videos/${videoId}/frames/${f}`} loading="lazy"/><span>{String(f).padStart(5,'0')}</span><div className="pair-strips">{!VISIBLE_ONLY&&<i className={o?.person_ext?'has-a':''}>A</i>}<i className={o?.person_visible?'has-b':''}>{o?.person_visible?'Box':'—'}</i></div></button>})}<div className="nearby-label"><span>NEARBY FRAMES</span><p>Check the boxes between<br/>your drawn frames.</p><button className="subtle" onClick={()=>act('copy')}>Copy previous box <kbd>C</kbd></button></div></div></section>
  <footer><span><kbd>F</kbd>next</span><span><kbd>D</kbd>back</span><span><kbd>N</kbd>new person</span><span><kbd>K</kbd>interpolate</span><span><kbd>↵</kbd>next</span><span><kbd>Alt + drag</kbd>replace</span><div className="toolbar-spacer"/><span>Draw. Adjust. Automatically saved.</span><button onClick={()=>open('help')}><kbd>?</kbd>help</button></footer>
 </>}
 {notice&&<div className="toast" role="status">{notice}</div>}
 {modal&&<Modal title={{hiddenRange:'Delete boxes in range',newVideo:'New video',finishVideo:'Finish video',newProject:'Create project',projects:'Your projects',import:'Add a video',id:'Person ID, class & color',deletePerson:'Delete person',unknown:'Full extent unknown',gap:'Start an invisible interval',resume:'Resume at this visible frame',identity:'Identity & segment decisions',complete:'Whole-frame completeness check',help:'Shortcuts & commands',export:'Export your annotations',detector:'Detector proposals',issues:'Review issues',diagnostics:'Local system diagnostics',suggestions:'Inspect detector suggestions'}[modal]||modal} onClose={()=>{if(!uploadBusy&&!loading)setModal('')}} wide={['import','help','export','issues'].includes(modal)}>
  {error&&<div className="error" role="alert">{error}</div>}
  {modal==='hiddenRange'&&<form onSubmit={e=>{e.preventDefault();if(s.markHiddenRange(Number(form.start),Number(form.end)))setModal('')}}><p>Delete boxes for <strong>{identity?.person_id?'Person '+identity.person_id:identity?.name}</strong>. Missing boxes are automatically marked Not visible. Both frame numbers are included.</p><label>First frame to delete<input aria-label="First frame to delete" type="number" required min="0" max={(video?.frame_count||1)-1} step="1" value={form.start??''} onChange={e=>setForm({...form,start:e.target.value})}/></label><label>Last frame to delete<input aria-label="Last frame to delete" type="number" required min={Math.max(0,Number(form.start)||0)} max={(video?.frame_count||1)-1} step="1" value={form.end??''} onChange={e=>setForm({...form,end:e.target.value})}/></label><p><strong>{Object.values(project!.state.observations).filter(o=>o.video_id===videoId&&o.identity_uuid===activeId&&o.frame_index>=Number(form.start)&&o.frame_index<=Number(form.end)&&(o.person_visible||o.person_ext)).length} boxes</strong> will be removed for this person, including any drawn or adjusted boxes in the range. Boxes outside the range and other people are kept. Interpolation will not refill deleted frames. Draw a box again to correct a deleted frame.</p><p>Example: keep boxes at 39 and 60; delete frames 40–59. Ctrl+Z restores this entire change.</p><div className="button-row"><button type="button" onClick={()=>setModal('')}>Cancel</button><button className="primary" type="submit">Delete boxes</button></div></form>}
  {modal==='newVideo'&&<NewVideo onCreated={openVideo} onBusy={setUploadBusy}/>}
  {modal==='finishVideo'&&<><p>Did you annotate and track every person in the video?</p><p>Check the frames between your drawn boxes too. You can reopen this video and make corrections later.</p><label className="checkbox"><input aria-label="Every person annotated and tracked" type="checkbox" checked={checkAll} onChange={e=>setCheckAll(e.target.checked)}/>Yes, I annotated and tracked every person in this video.</label><div className="button-row"><button onClick={()=>setModal('')}>Keep annotating</button><button className="primary" disabled={!checkAll||loading} onClick={()=>void task(async()=>{await s.saveNow();const current=useStore.getState();const finished=await post(`/videos/${videoId}/finish`,{confirmed:true,revision:current.project!.revision});useStore.setState({project:{...current.project!,videos:{...current.project!.videos,[videoId]:finished}}});setForm({format:'annotations_json'});setModal('export');})}>Finish & choose export</button></div></>}
  {modal==='deletePerson'&&<><p>Delete {form.name} and all {Object.values(project!.state.observations).filter(o=>o.identity_uuid===form.target).length} observations across this project’s videos? This also removes their visibility segments, gaps and identity links.</p><p>You can restore this with Ctrl+Z (Undo).</p><div className="button-row"><button onClick={()=>setModal('')}>Cancel</button><button className="danger" onClick={()=>{if(s.deletePerson(form.target))setModal('')}}>Delete person and annotations</button></div></>}
  {modal==='newProject'&&<form onSubmit={createProject}><label>Project name<input autoFocus required value={form.name||''} onChange={e=>setForm({...form,name:e.target.value})}/></label><p className="muted">Group related recordings in one project. Numeric person IDs are scoped to this project.</p><button className="primary" disabled={loading}>Create project</button></form>}
  {modal==='projects'&&<><button className="primary" onClick={()=>open('newProject',{name:''})}><Plus size={15}/>New project</button><input aria-label="Find project" placeholder="Search projects…" value={form.search||''} onChange={e=>setForm({...form,search:e.target.value})}/><div className="project-list">{projects.filter(p=>p.name.toLowerCase().includes((form.search||'').toLowerCase())).map(p=><button key={p.id} onClick={()=>void task(async()=>{await s.load(p.id);setModal('')})}><FolderOpen size={19}/><span>{p.name}</span><ArrowRight size={16}/></button>)}</div><hr/><h3>Restore a native archive</h3><p>Restore a portable ZIP with original videos, or an archive referencing originals still present on this machine. Source hashes are checked.</p><input aria-label="Restore native archive" type="file" accept=".zip" onChange={e=>{const f=e.target.files?.[0];if(!f)return;void task(async()=>{const body=new FormData();body.append('file',f);setRestoreJob(await api('/imports/native',{method:'POST',body}))})}}/>{restoreJob&&<p>{restoreJob.status}{restoreJob.error?' · '+restoreJob.error:''}</p>}{restoreJob?.restored_project_id&&<button onClick={()=>void task(async()=>{await s.load(restoreJob.restored_project_id);setModal('')})}>Open restored project</button>}</>}
  {modal==='import'&&<><p>Use a local video. The original is preserved; exact frames become editable during indexing.</p><label className="upload-box"><Upload size={24}/><span>{loading?'Importing…':'Choose a video from your computer'}</span><input aria-label="Upload video" type="file" accept="video/*" disabled={loading} onChange={e=>{const f=e.target.files?.[0];if(!f)return;void task(async()=>{const data=new FormData();data.append('file',f);const r=await api(`/projects/${project!.id}/videos`,{method:'POST',body:data});useStore.setState({videoId:r.video_id,frame:0});setModal('')})}}/></label><h3>Videos in your workspace</h3><input aria-label="Find video" placeholder="Filter filenames…" value={form.search||''} onChange={e=>setForm({...form,search:e.target.value})}/><div className="library-list">{library.filter(v=>v.name.toLowerCase().includes((form.search||'').toLowerCase())).map(v=><button key={v.path} disabled={loading} onClick={()=>void task(async()=>{const r=await post(`/projects/${project!.id}/videos/local`,{path:v.path});useStore.setState({videoId:r.video_id,frame:0});setModal('')})}><Play size={15}/><span>{v.name}<small>{v.path.split('/').slice(0,-1).join(' / ')}</small></span><span>{(v.bytes/1e6).toFixed(0)} MB</span></button>)}</div></>}
  {modal==='id'&&<form onSubmit={e=>{e.preventDefault();const n=form.id?Number(form.id):null;const target=form.target||Object.values(project!.state.identities).find(p=>n!==null&&p.person_id===n)?.id||activeId;void task(async()=>{const name=(form.class_name||'').trim();if(!name)throw new Error('Enter a class name');const result=await post(`/projects/${project!.id}/classes`,{name});useStore.setState({project:{...useStore.getState().project!,classes:result.classes}});if(s.assignPerson(target,n,name,form.color||'#baa7ff'))setModal('')})}}><p>Choose an existing person to continue their track, including on earlier frames. Or enter a new number. Class and color apply to this person across all frames.</p><label>Existing person ID<select aria-label="Existing person ID" value={form.target||''} onChange={e=>{const person=project!.state.identities[e.target.value];setForm({...form,target:e.target.value,id:String(person?.person_id??identity?.person_id??''),class_name:person?.class_name||project?.classes?.[0]||'Person',color:person?.color||'#baa7ff'})}}><option value="">New number / current person</option>{Object.values(project!.state.identities).filter(p=>p.person_id!==null).sort((a,b)=>a.person_id!-b.person_id!).map(p=><option key={p.id} value={p.id}>Person {p.person_id} · {p.class_name||'Person'}{p.id===activeId?' (current)':''}</option>)}</select></label><label>Positive numeric person ID<input autoFocus aria-label="Person ID" type="number" min="1" step="1" value={form.id||''} onChange={e=>{const existing=Object.values(project!.state.identities).find(p=>p.person_id===Number(e.target.value));setForm({...form,id:e.target.value,target:existing?.id||'',...(existing?{class_name:existing.class_name||project?.classes?.[0]||'Person',color:existing.color||'#baa7ff'}:{})})}}/></label><label>Class name<input aria-label="Class name" list="class-names" required maxLength={80} value={form.class_name||''} onChange={e=>setForm({...form,class_name:e.target.value})}/></label><datalist id="class-names">{classNames.map(name=><option key={name} value={name}/>)}</datalist><p>Choose a class from the list, or type a new class name.</p><label>Box color<input aria-label="Box color" type="color" value={form.color||'#baa7ff'} onInput={e=>setForm({...form,color:e.currentTarget.value})} onChange={e=>setForm({...form,color:e.target.value})}/></label><button className="primary" disabled={loading}>Save ID</button></form>}
  {modal==='unknown'&&<form onSubmit={e=>{e.preventDefault();editObservation('Full extent unknown',o=>{o.person_ext=null;o.full_quality='unknown';o.geometry_link='independent';o.evidence_note=form.note});useStore.setState({geometry:'person_visible'});setModal('')}}><p>Keep B as the visible evidence. A will be removed in one undoable action. This does not mark the person invisible.</p><label>Why is the full extent unsupported?<textarea autoFocus required value={form.note||''} onChange={e=>setForm({...form,note:e.target.value})}/></label><button className="primary">Keep B, mark A unknown</button></form>}
  {modal==='gap'&&<form onSubmit={beginGap}><p>Frame <strong>{frame}</strong> is the first completely invisible frame. There will be no positive boxes until you explicitly resume.</p><label>Cause<select value={form.reason} onChange={e=>setForm({...form,reason:e.target.value})}><option value="occlusion">Fully occluded</option><option value="outside">Outside image</option><option value="unavailable">Unavailable footage</option><option value="unknown">Unknown cause</option></select></label><label>Evidence note<textarea value={form.note||''} onChange={e=>setForm({...form,note:e.target.value})}/></label><button className="primary">Start gap at frame {frame}</button></form>}
  {modal==='resume'&&<form onSubmit={resume}><p>The gap closes at frame <strong>{frame-1}</strong>. Decide who is visible at frame <strong>{frame}</strong>.</p><label>Return identity<select value={form.relation} onChange={e=>setForm({...form,relation:e.target.value})}><option value="same">Same verified person</option><option value="different">Different person · new identity</option><option value="unresolved">Uncertain · provisional identity</option></select></label><label>Evidence for this decision<textarea autoFocus required value={form.note||''} onChange={e=>setForm({...form,note:e.target.value})}/></label><button className="primary">Start visible segment</button></form>}
  {modal==='identity'&&<><form onSubmit={identityAction}><label>Decision<select value={form.action} onChange={e=>setForm({...form,action:e.target.value})}><option value="unresolved">Record unresolved relation</option><option value="different">Confirm different people</option><option value="merge">Merge as the same physical person</option></select></label><label>Other identity<select required value={form.target} onChange={e=>setForm({...form,target:e.target.value})}><option value="">Choose identity</option>{Object.values(project!.state.identities).filter(p=>p.id!==activeId).map(p=><option value={p.id} key={p.id}>{p.person_id?'Person '+p.person_id:p.name}</option>)}</select></label><label>Evidence<textarea required value={form.note||''} onChange={e=>setForm({...form,note:e.target.value})}/></label><button className="primary">Save identity decision</button></form><hr/><h3>Segment boundary at frame {frame}</h3><div className="button-row"><button onClick={()=>splitSegment()}>Split segment, keep identity</button><button onClick={()=>splitSegment(true)}>Unlink into provisional identity</button><button onClick={()=>act('finish')}>Finish segment here</button></div></>}
  {modal==='complete'&&<><p>Inspect the <strong>entire image</strong>, including people you have not worked on yet. This final check covers everyone together; there is no per-person approval step.</p><div className="review-summary"><span>{frameObs.length} people annotated</span><span>{filteredProposals.filter(p=>!frameObs.some(o=>Object.values(o.provenance).some(v=>v?.proposal_id===p.id))).length} unaccepted suggestions to consider</span></div>{frameObs.some(o=>observationIssues(o).length>0||project!.state.segments[o.segment_id]?.status!=='verified')&&<p className="error">Fix missing boxes or unresolved identities before marking this frame complete.</p>}<label className="checkbox"><input type="checkbox" checked={checkAll} onChange={e=>setCheckAll(e.target.checked)}/>I checked the whole frame for every visible person, including detector misses. If this is empty, I verified it is genuinely empty.</label><button className="primary" disabled={!checkAll||frameObs.some(o=>observationIssues(o).length>0||project!.state.segments[o.segment_id]?.status!=='verified')} onClick={()=>{s.commit('Frame reviewed-complete',d=>{const id=videoId+':'+frame;d.reviews[id]={id,video_id:videoId,frame_index:frame,complete:true,checked_all_people:true,note:''}});setModal('')}}>Mark frame {frame} complete</button></>}
  {modal==='help'&&<><input autoFocus placeholder="Search actions or shortcuts…" value={form.search||''} onChange={e=>setForm({...form,search:e.target.value})}/><p className="muted">Click a shortcut field to remap it. Space: tap to play/pause, hold and drag to pan. Drag a box to move it; drag a corner to resize it.</p><div className="shortcut-list">{Object.entries(keyDescriptions).filter(([a])=>a in defaultKeys).filter(([a,d])=>(d+' '+keys[a]).toLowerCase().includes((form.search||'').toLowerCase())).map(([a,d])=><div key={a}><button onClick={()=>{setModal('');setTimeout(()=>act(a),0)}}>{d}</button><input aria-label={'Shortcut '+d} value={keys[a]} onChange={e=>{const k={...keys,[a]:e.target.value.toLowerCase()};setKeys(k);localStorage.setItem('frameinsight:keys',JSON.stringify(k))}}/></div>)}</div><button onClick={()=>{setKeys(defaultKeys);localStorage.removeItem('frameinsight:keys')}}>Reset defaults</button></>}
  {modal==='issues'&&<div className="issue-list">{!VISIBLE_ONLY&&unknownFullCount>0&&<p>{unknownFullCount} observations have unknown full extent. These are valid visible annotations; full/dual YOLO export excludes their frames.</p>}{unresolvedLinkCount>0&&<p>{unresolvedLinkCount} unresolved identity links block MOT export. Native and visible-only exports retain this uncertainty.</p>}{issues.length?issues.map(({o,messages})=><button key={o.id} onClick={()=>{s.navigate(o.frame_index);useStore.setState({activeId:o.identity_uuid});setModal('')}}><span className="issue-frame">{o.frame_index}</span><span><strong>{project!.state.identities[o.identity_uuid].person_id?'Person '+project!.state.identities[o.identity_uuid].person_id:project!.state.identities[o.identity_uuid].name}</strong><small>{messages.join(' · ')}</small></span><ArrowRight size={15}/></button>):<p>No observation errors. Frame completeness is checked separately.</p>}</div>}
  {modal==='detector'&&<><p>Only suggestions explicitly mapped to person_visible appear in this workflow. The supplied full-extent model remains hidden; use it for visible boxes only if that matches its training labels. Suggestions never establish identity or approval.</p><form onSubmit={e=>{e.preventDefault();void task(async()=>{await post(`/videos/${videoId}/proposal-jobs`,{model:form.model,device:form.device,confidence:Number(form.confidence),imgsz:Number(form.imgsz),batch_size:Number(form.batch_size),class_mapping:JSON.parse(form.mapping)});s.toast('Detector pass queued. Editing remains available.');setModal('')})}}><label>Trusted model<select value={form.model} onChange={e=>setForm({...form,model:e.target.value})}>{models.map(m=><option key={m.name}>{m.name}</option>)}</select></label><div className="form-grid"><label>Device<select value={form.device} onChange={e=>setForm({...form,device:e.target.value})}><option value="0">CUDA GPU 0</option><option value="cpu">CPU (explicit)</option></select></label><label>Image size<input type="number" min="128" max="2048" step="32" value={form.imgsz} onChange={e=>setForm({...form,imgsz:e.target.value})}/></label><label>Saved candidate threshold<input type="number" min=".001" max="1" step=".01" value={form.confidence} onChange={e=>setForm({...form,confidence:e.target.value})}/></label><label>Batch size<input type="number" min="1" max="16" value={form.batch_size} onChange={e=>setForm({...form,batch_size:e.target.value})}/></label></div><label>Confirmed model class → geometry mapping<input required value={form.mapping} onChange={e=>setForm({...form,mapping:e.target.value})}/></label><p className="muted">Changing display confidence only filters saved candidates. Run a new pass to lower the inference threshold.</p><button className="primary" disabled={loading||!models.length||video?.status!=='ready'}>Run every source frame</button></form><div className="job-list">{jobs.filter(j=>j.kind==='proposals').slice(0,6).map(j=><div key={j.id}><strong>{j.status} · {j.progress} / {j.total||'?'}</strong><small>{j.error||j.phase}</small>{['queued','running'].includes(j.status)&&<button onClick={()=>void post('/jobs/'+j.id+'/cancel')}>Cancel pass</button>}</div>)}</div><button onClick={()=>void post('/worker/stop').then(()=>s.toast('GPU worker stopped. Manual editing stays available.'))}>Stop GPU worker</button></>}
  {modal==='export'&&<><p>Your work is saved. Choose how to download your annotations.</p><form onSubmit={e=>{e.preventDefault();void task(async()=>{await s.saveNow();await post(`/projects/${project!.id}/exports`,{format:form.format,video_id:videoId,include_videos:false});s.toast('Preparing your download…');})}}><label>Export format<select aria-label="Export format" value={form.format} onChange={e=>setForm({...form,format:e.target.value})}><option value="annotations_json">Annotations JSON (recommended)</option><option value="native">Project backup ZIP</option></select></label><p>{form.format==='annotations_json'?'Includes boxes, IDs, classes, colors, frame numbers and edit history for this video. No videos or images.':'A backup of the project’s annotation data. Keep your source videos separately for restoring it.'}</p><button className="primary" disabled={loading}>Prepare download</button></form><div className="job-list">{jobs.filter(j=>j.kind==='export'&&j.settings?.video_id===videoId).slice(0,8).map(j=><div key={j.id}><strong>{j.status==='completed'?'Ready to download':j.status==='failed'?'Could not prepare download':'Preparing…'}</strong>{j.error&&<small className="error">{j.error}</small>}{j.export_id&&<a className="download-link" href={'/api/exports/'+j.export_id} download><Download size={14}/>{j.settings?.format==='annotations_json'?'Download annotations (.json)':'Download backup (.zip)'}</a>}</div>)}</div><button onClick={()=>void task(home)}>Back to videos</button></>}

  {modal==='suggestions'&&<><p>Inspect each crop. Accept only the selected geometry, or reject false positives and duplicates. Rejection is saved separately and can be undone.</p><label>Rejection reason<input value={form.reason||''} onChange={e=>setForm({...form,reason:e.target.value})}/></label><div className="proposal-review-list">{proposals.filter(p=>(!VISIBLE_ONLY||p.geometry==='person_visible')&&p.confidence>=threshold).map(p=>{const rejected=project!.state.proposal_reviews?.[p.id],scale=Math.min(210/(p.box[2]-p.box[0]),150/(p.box[3]-p.box[1]));return <div key={p.id}><div className="proposal-crop" style={{width:Math.max(20,(p.box[2]-p.box[0])*scale),height:Math.max(20,(p.box[3]-p.box[1])*scale)}}><img src={`/api/videos/${videoId}/frames/${frame}`} style={{width:video!.width*scale,height:video!.height*scale,left:-p.box[0]*scale,top:-p.box[1]*scale}}/></div><span>{VISIBLE_ONLY?'Visible person':p.geometry==='person_ext'?'A':'B'} · {Math.round(p.confidence*100)}%</span>{rejected?<><small>Rejected: {rejected.reason}</small><button onClick={()=>s.commit('Restore suggestion',d=>{delete d.proposal_reviews[p.id]})}>Restore suggestion</button></>:<div className="button-row"><button disabled={!activeId} onClick={()=>{s.setBox(p.geometry,p.box,p);setModal('')}}>Attach to active person</button><button onClick={()=>rejectProposal(p)}>Reject suggestion</button></div>}</div>})}</div></>}
  {modal==='diagnostics'&&<><pre className="diagnostics">{diagnostics?JSON.stringify(diagnostics,null,2):'Checking system…'}</pre>{video?.status==='failed'&&<button onClick={()=>void post(`/videos/${videoId}/retry-index`).then(()=>setModal(''))}>Retry interrupted indexing</button>}<p className="muted">Bound to localhost. Footage, models, annotations and exports stay on this machine.</p></>}
 </Modal>}
 </div>;
}
