import {useEffect,useMemo,useState} from 'react';
import {ScanLine,Upload,Eye,ChevronRight} from 'lucide-react';
import {api,post} from './api';
import {useStore} from './store';
import {listTrackIssues} from './assistance';
import {boxStyle,currentObservation,type Job,type Proposal} from './types';

type Runtime={available:boolean;gpu:string|null;error?:string;default_model:string;models:{name:string;label?:string;installed?:boolean}[];trackers:string[]};
type Track={id:string;start:number;end:number;count:number;issues:{frame_index:number;reason:string}[]};
type Tracks={cache_key:string|null;tracks:Track[];complete:boolean;status:string;processed_frames:number;total_frames:number};
type Detail={cache_key:string;track_id:string;proposals:Proposal[];complete:boolean;issues:{frame_index:number;reason:string}[]};
const trackLabel=(id:string)=>id.split(':').at(-1);
type Props={jobs:Job[];proposals:Proposal[];threshold:number;setThreshold:(v:number)=>void;show:boolean;setShow:(v:boolean)=>void;cacheKey:string;setCacheKey:(v:string)=>void;selected:Proposal|null;onSelect:(p:Proposal|null)=>void;onImport:()=>void;beforeAction:()=>void};
export function AssistancePanel({jobs,proposals,threshold,setThreshold,show,setShow,cacheKey,setCacheKey,selected,onSelect,onImport,beforeAction}:Props){
 const s=useStore(),{project,videoId,frame,activeId}=s,video=project?.videos[videoId];
 const [runtime,setRuntime]=useState<Runtime|null>(null),[model,setModel]=useState(''),[tracker,setTracker]=useState('botsort'),[device,setDevice]=useState('auto'),[resolution,setResolution]=useState(960),[error,setError]=useState(''),[busy,setBusy]=useState(false),[tracks,setTracks]=useState<Tracks|null>(null),[detail,setDetail]=useState<Detail|null>(null),[chosenTrack,setChosenTrack]=useState(''),[newClass,setNewClass]=useState('person_visible'),[localJob,setLocalJob]=useState<Job|null>(null);
 const job=jobs.find(j=>j.video_id===videoId&&j.settings?.mode==='tracking')||localJob;
 const running=job&&['queued','running'].includes(job.status);
 useEffect(()=>{let gone=false;void api<Runtime>('/assist/status').then(x=>{if(!gone){setRuntime(x);setModel(x.default_model);}}).catch(e=>{if(!gone)setError(String(e))});return()=>{gone=true}},[]);
 useEffect(()=>{setTracks(null);setDetail(null);setChosenTrack('');setLocalJob(null);setCacheKey('');onSelect(null);setError('');setNewClass(project?.classes?.find(c=>!['person_ext','person_extended','person_exteded'].includes(c.toLowerCase()))||'person_visible');},[videoId]);
 useEffect(()=>{if(job?.cache_key&&job.cache_key!==cacheKey){setCacheKey(job.cache_key);setChosenTrack('');setDetail(null);onSelect(null);}},[job?.id,job?.cache_key]);
 useEffect(()=>{if(!videoId)return;let gone=false;const refresh=()=>void api<Tracks>(`/videos/${videoId}/tracks${cacheKey?'?cache_key='+encodeURIComponent(cacheKey):''}`).then(x=>{if(gone)return;setTracks(x);if(!cacheKey&&x.cache_key)setCacheKey(x.cache_key)}).catch(e=>{if(!gone)setError(String(e))});refresh();const timer=window.setInterval(refresh,running?3000:15000);return()=>{gone=true;clearInterval(timer)}},[videoId,cacheKey,running,job?.status]);
 useEffect(()=>{if(selected?.video_id===videoId&&selected.cache_key===cacheKey)setChosenTrack(selected.track_id||'');},[selected?.id,cacheKey,videoId]);
 useEffect(()=>{setDetail(null);if(!chosenTrack||!cacheKey)return;let gone=false;void api<Detail>(`/videos/${videoId}/tracks/${encodeURIComponent(chosenTrack)}?cache_key=${encodeURIComponent(cacheKey)}`).then(x=>{if(!gone)setDetail(x)}).catch(e=>{if(!gone)setError(String(e))});return()=>{gone=true}},[videoId,chosenTrack,cacheKey,tracks?.complete]);
 const issues=useMemo(()=>{
  if(!detail)return [];
  const rows=listTrackIssues(detail.proposals).map(i=>({frame_index:i.kind==='gap'?i.start_frame!:i.frame_index,message:i.message}));
  for(const issue of detail.issues||[])if(!rows.some(i=>i.frame_index===issue.frame_index&&i.message===issue.reason))rows.push({frame_index:issue.frame_index,message:issue.reason});
  return rows.sort((a,b)=>a.frame_index-b.frame_index);
 },[detail]);
 const summary=tracks?.tracks.find(t=>t.id===chosenTrack);
 const selectedNow=selected?.frame_index===frame&&selected.video_id===videoId?selected:null;
 const active=project?.state.identities[activeId];
 const classNames=[...new Set(['person_visible',...(project?.classes||[])])].filter(c=>!['person_ext','person_extended','person_exteded'].includes(c.toLowerCase()));
 const accepted=new Map(Object.values(project?.state.observations||{}).flatMap(o=>o.video_id===videoId&&o.provenance.person_visible?.proposal_id?[[o.provenance.person_visible.proposal_id,o.identity_uuid] as const]:[]));
 const linkedId=detail?.proposals.map(p=>accepted.get(p.id)).find(Boolean);
 const linkedPerson=linkedId?project?.state.identities[linkedId]:undefined;
 async function action(fn:()=>Promise<void>){beforeAction();setBusy(true);setError('');try{await fn()}catch(e){setError(String(e))}finally{setBusy(false)}}
 function useTrack(target:string|null){if(!detail?.complete)return;beforeAction();s.acceptTrack(detail.proposals,target,target&&active?boxStyle(active,'person_visible').class_name:newClass);}
 function useFrame(){if(!selectedNow)return;beforeAction();useStore.setState({geometry:'person_visible'});let live=useStore.getState();if(!live.activeId){live.newPerson();live=useStore.getState();}if(currentObservation(live.project,videoId,frame,live.activeId)?.person_visible){s.toast('This person already has a box here. Drag or resize it to correct it.');return;}live.setBox('person_visible',selectedNow.box,selectedNow);}
 function chooseTrack(id:string){setChosenTrack(id);onSelect(null);const t=tracks?.tracks.find(t=>t.id===id);if(t){beforeAction();s.navigate(t.start)}}
 function nextIssue(){const issue=issues.find(i=>i.frame_index>frame)||issues[0];if(issue){beforeAction();s.navigate(issue.frame_index);s.toast(issue.message);}}
 return <div className="assistance-panel">
  <div className="assist-intro"><ScanLine size={20}/><div><h3>Detect & track people</h3><p>Find people throughout the video, then choose which tracks to keep.</p></div></div>
  <div className="assist-device">{runtime?runtime.available?(runtime.gpu||'CPU available · slower processing'):'AI runtime not installed':'Checking AI runtime…'}</div>
  {runtime&&!runtime.available&&<p className="muted">{runtime.error} Annotation JSON import is available below.</p>}
  <button className="primary assist-start" disabled={busy||!!running||!runtime?.available||video?.status!=='ready'} onClick={()=>void action(async()=>{const j=await post<Job>(`/videos/${videoId}/assist`,{model,tracker,device,imgsz:resolution,confidence:.1});setLocalJob(j);if(j.cache_key)setCacheKey(j.cache_key);setShow(true);s.toast(j.status==='completed'?'Loaded the saved AI pass.':'Detection and tracking queued. You can continue annotating.');})}><ScanLine size={16}/>{running?'Processing video…':'Detect all people'}</button>
  <details className="assist-settings"><summary>Processing settings</summary><label>Model<select aria-label="AI model" value={model} onChange={e=>setModel(e.target.value)}>{runtime?.models.map(m=><option key={m.name} value={m.name}>{m.label||m.name}{!m.installed?' · download on first use':''}</option>)}</select></label><label>Tracker<select aria-label="AI tracker" value={tracker} onChange={e=>setTracker(e.target.value)}>{(runtime?.trackers?.length?runtime.trackers:['botsort']).map(t=><option key={t} value={t}>{t==='botsort'?'BoT-SORT + appearance matching':'TrackTrack + appearance matching'}</option>)}</select></label><label>Device<select aria-label="AI device" value={device} onChange={e=>setDevice(e.target.value)}><option value="auto">Automatic (prefer GPU)</option><option value="0">GPU</option><option value="cpu">CPU</option></select></label><label>Processing image size<select aria-label="AI image size" value={resolution} onChange={e=>setResolution(Number(e.target.value))}><option value={640}>640 · less memory</option><option value={960}>960 · more detail</option><option value={1280}>1280 · most detail</option></select></label><p className="muted">Models download once. Changing settings creates a separate pass. Manual annotations stay in place.</p></details>
  {job&&<div className="assist-progress" role="status"><div><strong>{job.status==='completed'?'AI pass ready':job.status==='failed'?'AI pass failed':job.status==='cancelled'?'AI pass cancelled':job.phase||job.status}</strong><span>{job.progress} / {job.total||video?.frame_count||'?'}</span></div><progress max={job.total||video?.frame_count||1} value={job.progress}/>{job.error&&<p className="error">{job.error}</p>}{running&&<button disabled={busy} onClick={()=>void action(async()=>{await post(`/jobs/${job.id}/cancel`);s.toast('Stopping the AI pass…')})}>Cancel processing</button>}</div>}
  {error&&<p className="error" role="alert">{error}</p>}
  <section className="assist-section"><div className="assist-section-title"><h3>Suggestions</h3><label className="assist-toggle"><input type="checkbox" aria-label="Show AI suggestions" checked={show} onChange={e=>setShow(e.target.checked)}/><Eye size={15}/></label></div><label className="confidence-label" htmlFor="ai-confidence"><span>Display confidence</span><output>{Math.round(threshold*100)}%</output></label><input id="ai-confidence" aria-label="Display confidence" type="range" min={10} max={100} step={1} value={Math.round(threshold*100)} onChange={e=>setThreshold(Number(e.target.value)/100)}/><p className="assist-hint">Hides weaker suggestions only. Saved boxes and whole-track adoption are unaffected.</p>
   <div className="assist-detections" aria-label="Suggestions on this frame">{proposals.map((p,i)=><button key={p.id} aria-pressed={selected?.id===p.id} onClick={()=>{beforeAction();onSelect(p);setShow(true)}}><span>{p.track_id?'Track '+trackLabel(p.track_id):'Unlinked box '+(i+1)}</span><strong>{Math.round(p.confidence*100)}%</strong></button>)}</div>{!proposals.length&&<p className="muted">No unassigned suggestions at this confidence on frame {frame}.</p>}
  </section>
  {!!tracks?.tracks.length&&<section className="assist-section"><label>Tracks across the video<select aria-label="Suggested track" value={chosenTrack} onChange={e=>chooseTrack(e.target.value)}><option value="">Choose a track…</option>{tracks.tracks.map(t=><option key={t.id} value={t.id}>Track {trackLabel(t.id)} · frames {t.start}–{t.end} · {t.count} boxes</option>)}</select></label><p className="assist-hint">Includes people who enter later. A tracker number is a suggestion, not your person ID.</p></section>}
  {(selectedNow||chosenTrack)&&<section className="assist-section assist-selection"><h3>{chosenTrack?'Track '+trackLabel(chosenTrack):'Selected detection'}</h3>{summary&&<p>{summary.count} boxes · frames {summary.start}–{summary.end}</p>}{linkedPerson&&<p className="assist-linked">Linked to {linkedPerson.person_id?'Person '+linkedPerson.person_id:linkedPerson.name}</p>}
   {chosenTrack&&<><label>Class for a new person<select aria-label="AI new person class" value={newClass} onChange={e=>setNewClass(e.target.value)}>{classNames.map(c=><option key={c}>{c}</option>)}</select></label><button className="primary" disabled={busy||!detail?.complete} onClick={()=>useTrack(null)}>{linkedPerson?'Add missing boxes to linked person':'Use track as new person'}</button>{activeId&&activeId!==linkedId&&<button disabled={busy||!detail?.complete} onClick={()=>useTrack(activeId)}>Use track for {active?.person_id?'Person '+active.person_id:active?.name}</button>}{!detail?.complete&&<p className="assist-hint">Whole-track adoption is available after this pass finishes.</p>}<button disabled={!issues.length} onClick={nextIssue}><ChevronRight size={15}/>Next issue ({issues.length})</button><p className="assist-hint">Check crossings, gaps and entries even if no issue is flagged. Drag or resize accepted boxes; manual corrections take priority.</p></>}
   {selectedNow&&<button disabled={busy||!!currentObservation(project,videoId,frame,activeId)?.person_visible} onClick={useFrame}>Use only this frame{active?' for '+(active.person_id?'Person '+active.person_id:active.name):''}</button>}
  </section>}
  <section className="assist-section"><button className="assist-import" onClick={onImport}><Upload size={16}/>Import annotations (.json)</button><p className="assist-hint">Bring back a Frameinsight JSON export for this exact source video.</p></section>
 </div>;
}
