import {useEffect,useMemo,useState} from 'react';
import {ArrowLeft,Download,LoaderCircle,Plus,Scissors,Trash2,Upload} from 'lucide-react';
import {Button} from './components/ui/button';
import {Input} from './components/ui/input';
import {Slider} from './components/ui/slider';
import {api,post} from './api';
import {normalizeSections,type TrimSection} from './trim-sections';
type TrimJob={id:string;status:string;progress:number;total?:number;phase?:string;error?:string;metadata?:{name:string;frame_count:number;width:number;height:number;has_audio:boolean};download_url?:string;preview_url?:string;name?:string;frame_count?:number;duration_seconds?:number;audio_included?:boolean};
const storage='frameinsight:video-preparation';
function restored(){try{return JSON.parse(localStorage.getItem(storage)||'null')}catch{return null}}
export function TrimVideo({onBack}:{onBack:()=>void}){
 const [saved]=useState(restored),[scan,setScan]=useState<TrimJob|null>(saved?.scan||null),[result,setResult]=useState<TrimJob|null>(saved?.result||null),[sections,setSections]=useState<TrimSection[]>(saved?.sections||[]),[name,setName]=useState(saved?.name||'trimmed.mp4'),[preview,setPreview]=useState(0),[imageFrame,setImageFrame]=useState(0),[loaded,setLoaded]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[retry,setRetry]=useState(0);
 const info=scan?.metadata,scanning=!!scan&&['queued','running'].includes(scan.status),rendering=!!result&&['queued','running'].includes(result.status),working=busy||scanning||rendering;
 useEffect(()=>{try{localStorage.setItem(storage,JSON.stringify({scan,result,sections,name}))}catch{}},[scan,result,sections,name]);
 useEffect(()=>{const timer=setTimeout(()=>setImageFrame(preview),120);return()=>clearTimeout(timer)},[preview]);
 useEffect(()=>{if(!scan?.id)return;let gone=false,timer=0;const poll=async()=>{try{const next=await api<TrimJob>('/jobs/'+scan.id);if(gone)return;setScan(next);if(next.status==='completed'&&next.metadata&&!sections.length){setSections([{start:0,end:next.metadata.frame_count-1}]);setName(next.metadata.name.replace(/\.[^.]+$/,'')+'-trimmed.mp4');}if(['running','queued'].includes(next.status))timer=window.setTimeout(poll,700);}catch(e){if(!gone){setError(String(e));if((e as {status?:number}).status===404){setScan(null);setSections([]);setResult(null);}}}};void poll();return()=>{gone=true;clearTimeout(timer)}},[scan?.id,retry]);
 useEffect(()=>{if(!result?.id)return;let gone=false,timer=0;const poll=async()=>{try{const next=await api<TrimJob>('/jobs/'+result.id);if(gone)return;setResult(next);if(['running','queued'].includes(next.status))timer=window.setTimeout(poll,700);}catch(e){if(!gone){setError(String(e));if((e as {status?:number}).status===404)setResult(null);}}};void poll();return()=>{gone=true;clearTimeout(timer)}},[result?.id,retry]);
 const normalized=useMemo(()=>{try{return {rows:info?normalizeSections(sections,info.frame_count):[],error:''}}catch(e){return {rows:[],error:String(e)}}},[sections,info?.frame_count]);
 const selected=normalized.rows.reduce((sum,r)=>sum+r.end-r.start+1,0),count=info?.frame_count||1;
 const source=scan&&info?`/api/video-trims/${scan.id}/frames/${Math.min(imageFrame,count-1)}`:'';
 const addStart=[...sections].sort((a,b)=>a.start-b.start).reduce((n,r)=>r.start<=n?Math.max(n,r.end+1):n,0);
 function change(index:number,values:number[]){const [start,end]=values;setPreview(start!==sections[index].start?start:end);setSections(rows=>rows.map((r,i)=>i===index?{start,end}:r));setResult(null);}
 async function choose(file:File){setBusy(true);setError('');setResult(null);setSections([]);setPreview(0);setScan(null);try{const data=new FormData();data.append('file',file);setScan(await api<TrimJob>('/video-trims',{method:'POST',body:data}));}catch(e){setError(String(e));}finally{setBusy(false);}}
 async function create(){if(!scan||normalized.error)return;setBusy(true);setError('');try{setResult(await post<TrimJob>(`/video-trims/${scan.id}/render`,{sections:normalized.rows,name}));}catch(e){setError(String(e));}finally{setBusy(false);}}
 async function cancel(){const job=rendering?result:scan;if(!job)return;setBusy(true);try{const next=await post<TrimJob>('/jobs/'+job.id+'/cancel');if(rendering)setResult(next);else setScan(next);}catch(e){setError(String(e));}finally{setBusy(false);}}
 return <main className="flex min-h-0 flex-1 flex-col overflow-auto p-4 md:p-6" aria-label="Prepare a new video">
  <div className="mb-4 flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-3"><Button variant="ghost" size="icon-sm" aria-label="Back to videos" disabled={working} onClick={onBack}><ArrowLeft/></Button><div><h1 className="text-lg font-semibold">Trim sections</h1><p className="text-xs text-muted-foreground">Choose sections, save a new video, then upload it for annotation.</p></div></div><Button variant="outline" size="sm" disabled={working} onClick={onBack}>Back to videos</Button></div>
  <div className="mb-4 flex flex-wrap items-center gap-3"><label className="!m-0 relative inline-flex cursor-pointer items-center gap-2 rounded-full border border-border bg-card px-4 py-2 text-xs"><Upload className="size-4"/>{scan?'Choose another video':'Choose source video'}<Input className="absolute inset-0 cursor-pointer opacity-0" aria-label="Source video to trim" type="file" accept="video/*,.mkv" disabled={working} onChange={e=>{const f=e.target.files?.[0];if(f)void choose(f);e.target.value='';}}/></label><span className="truncate text-xs text-muted-foreground">{info?.name||scan?.name||'Your original file stays unchanged.'}</span></div>
  {(error||scan?.status==='failed'||result?.status==='failed')&&<div role="alert" className="mb-4 text-sm text-destructive">{error||scan?.error||result?.error}{error&&working&&<Button variant="outline" size="sm" className="ml-3" onClick={()=>{setError('');setRetry(n=>n+1)}}>Retry status</Button>}</div>}
  {working&&<div className="mb-4 flex items-center gap-3 rounded-xl border border-border p-4 text-sm" role="status"><LoaderCircle className="size-4 animate-spin"/><span>{busy?'Preparing…':(rendering?result:scan)?.phase||'Preparing…'} {((rendering?result:scan)?.total||0)>0&&`${Math.round(((rendering?result:scan)!.progress||0)/(rendering?result:scan)!.total!*100)}%`}</span>{!busy&&<Button variant="ghost" size="sm" className="ml-auto" onClick={()=>void cancel()}>Cancel job</Button>}</div>}
  {info&&scan?.status==='completed'?<div className="grid min-h-0 flex-1 gap-5 lg:grid-cols-[minmax(0,1fr)_360px]">
   <section className="flex min-h-0 flex-col overflow-hidden rounded-xl border border-border bg-card"><div className="flex justify-between px-4 py-3 text-xs"><span>{result?.status==='completed'?'New video preview':'Original video preview'}</span><span className="tabular-nums">{result?.status==='completed'?`${result.frame_count} frames`:`Source frame ${preview}`}</span></div>
    <div className="relative flex min-h-48 flex-1 items-center justify-center bg-black">{result?.status==='completed'?<video key={result.id} className="absolute h-full w-full object-contain" src={result.preview_url} controls aria-label="Trimmed video preview"/>:<><img className="absolute h-full w-full object-contain" src={source} alt={`Source frame ${imageFrame}`} onLoad={()=>setLoaded(source)} onError={()=>setError('The preview could not be loaded. Try a nearby frame or choose the source again.')}/>{(loaded!==source||imageFrame!==preview)&&<span className="absolute rounded-full bg-black/80 px-3 py-1 text-xs">Loading frame {preview}…</span>}</>}</div>
    {result?.status!=='completed'&&<div className="space-y-3 p-4"><Slider aria-label="Preview source frame" min={0} max={Math.max(1,count-1)} value={[preview]} disabled={count<2||working} step={1} onValueChange={v=>{setResult(null);setPreview(v[0]);}}/><div className="flex justify-between text-xs text-muted-foreground"><span>0</span><span>Original source frames</span><span>{count-1}</span></div></div>}
   </section>
   <aside className="flex min-h-0 flex-col gap-4"><div><h2 className="flex items-center gap-2 text-sm font-medium"><Scissors className="size-4"/>Sections to keep</h2><p className="mt-2 text-xs leading-relaxed text-muted-foreground">Drag the handles to set each section. The kept sections join into one new MP4 in source order; frame numbers start again at 0. Width, height and aspect ratio stay the same.</p></div>
    <div className="min-h-0 space-y-3 overflow-y-auto pr-1">{sections.map((r,i)=><section key={i} className="space-y-4 rounded-xl border border-border bg-card p-4" aria-label={`Section ${i+1}`}><div className="flex items-center justify-between text-xs"><strong>Section {i+1}</strong><div className="flex items-center gap-2"><span className="text-muted-foreground">{r.end-r.start+1} frames</span><Button variant="ghost" size="icon-xs" aria-label={`Remove section ${i+1}`} disabled={sections.length===1||working} onClick={()=>{setSections(rows=>rows.filter((_,n)=>n!==i));setResult(null);}}><Trash2/></Button></div></div>
     <Slider min={0} max={Math.max(1,count-1)} step={1} value={[r.start,r.end]} thumbLabels={[`Section ${i+1} start`,`Section ${i+1} end`]} disabled={count<2||working} onValueChange={v=>change(i,v)}/>
     <div className="grid grid-cols-2 gap-3">{(['start','end'] as const).map((key,n)=><label key={key} className="!m-0 !gap-1 text-xs text-muted-foreground">{n?'Last frame':'First frame'}<Input aria-label={`Section ${i+1} ${key} frame`} className="h-8 text-xs tabular-nums" type="number" min={0} max={count-1} value={r[key]} disabled={working} onFocus={()=>setPreview(r[key])} onChange={e=>{const value=Math.max(0,Math.min(count-1,Number(e.target.value)));change(i,n?[Math.min(value,r.start),value]:[value,Math.max(value,r.end)]);}}/></label>)}</div>
    </section>)}</div>
    <Button variant="outline" size="sm" disabled={working||sections.length>=100||addStart>=count} onClick={()=>{const end=Math.min(count-1,addStart+Math.max(1,Math.round(count/10))-1);setSections(rows=>[...rows,{start:addStart,end}]);setPreview(addStart);setResult(null);}}><Plus className="size-4"/>Add section</Button>
    <p className="text-xs leading-relaxed text-muted-foreground"><strong className="text-foreground">{selected.toLocaleString()} of {count.toLocaleString()} frames</strong> · {info.has_audio?'Audio is kept.':'Source has no audio.'} {info.width} × {info.height} pixels. Overlapping sections combine. No saved annotations are changed or copied.</p>
    <label className="!m-0 text-xs">New video filename<Input aria-label="New video filename" className="h-8 text-xs" value={name} maxLength={180} disabled={working} onChange={e=>setName(e.target.value)}/></label>
    {result?.status==='completed'?<div className="space-y-2 rounded-xl border border-border p-4"><strong className="text-sm">Your new video is ready.</strong><Button asChild className="w-full" size="sm"><a href={result.download_url+'?filename='+encodeURIComponent(name)} download={name}><Download className="size-4"/>Save new video (.mp4)</a></Button><p className="text-xs text-muted-foreground">After saving, go back to your project, click New video, and upload this MP4.</p></div>:<Button size="sm" disabled={working||!selected||!!normalized.error} onClick={()=>void create()}><Scissors className="size-4"/>Create new video</Button>}
    {normalized.error&&<p role="alert" className="text-xs text-destructive">{normalized.error}</p>}
   </aside>
  </div>:!working&&<div className="flex flex-1 flex-col items-center justify-center gap-3 rounded-xl border border-dashed border-border p-10 text-center"><Scissors className="size-8 text-muted-foreground"/><h2 className="text-base font-medium">Prepare your video before annotation</h2><p className="max-w-md text-sm text-muted-foreground">Choose a video above, keep the parts you need, and save a separate MP4. Upload that new file into any project.</p></div>}
 </main>;
}
